### ISSUE TITLE
Overriden RenderInterface::RenderGeometry() is not called into

### ISSUE THREAD

**Issue by IronicallySerious** [mikke89/RmlUi#100]
I have overridden this function in an implementation class of RenderInterface:
```cpp
void CustomRenderInterface::RenderGeometry(Rml::Core::Vertex* vertices, int num_vertices, int* indices, int num_indices, Rml::Core::TextureHandle texture, const Rml::Core::Vector2f& translation) 
{
...
}
```
I set it likewise:
```cpp
void UISystem::initialize(int width, int height)
{
	m_RmlSystemInterface.reset(new CustomSystemInterface());
	m_RmlRenderInterface.reset(new CustomRenderInterface());

	Rml::Core::SetSystemInterface(m_RmlSystemInterface.get());
	Rml::Core::SetRenderInterface(m_RmlRenderInterface.get());
	if (!Rml::Core::Initialise())
	{
		ERR("Could not initialize RmlUi UI rendering library");
	}
	loadFont("rootex/assets/fonts/Lato-Regular.ttf");
	m_Context = Rml::Core::CreateContext("default", Rml::Core::Vector2i(width, height));
}
```
For starters, I open the default.rml like this:
```xml
<rml>
	<head>
		<title>Demo</title>
		<style>
			body
			{
				width: 300px;
				height: 225px;
				
				margin: auto;
			}
			
			div#title_bar div#icon
			{
				display: none;
			}
			
			div#content
			{
				text-align: left;
			}
		</style>
	</head>
	<body template="window">
		This is a sample.
	</body>
</rml>
```
I load the document, show it, but my overrideen RenderGeometry() function is not called at anytime. RenderCompiledGeometry() is also not called

**Comment by mikke89** [comment]
Some things that come to mind, just to make sure:

- Use the override keyword on RenderGeometry to make sure there are no problems with the signature.
- Make sure the fonts are loaded. You could try creating a sized `div` element with a colored background in case there are any problems with the fonts.
- Make sure you call `Context::Update` and then `Context::Render` (in that order).
- Check the log output for any warnings or errors. There should also be some info when the fonts are loaded.
- There could also be some problems with the template, you could try removing that for testing purposes.

Let me know if any of this helps :)

**Comment by IronicallySerious** [comment]
I checked all of your suggestions, I still don't get draw calls for the text elements.
However I do get this warning:
```
No font face defined on element #text < body < #root#default. Please specify a font-family in your RCSS, otherwise make sure Context::Update is run after new elements are constructed, before Context::Render.
```
I tried to fix this by first, loading Lato font by:
```cpp
Rml::Core::LoadFontFace(rootex/assets/fonts/Lato-Regular.ttf)
```
Then adding this to demo.rml:
```
#text
			{
				font-family: "Lato";
			}
```
But the warning doesn't go away

**Comment by IronicallySerious** [comment]
I managed to get the font loaded (`#text` is wrong, I used a span to format the text to Lato font), but when I get a GenerateTexture() call, my image loading functions fail for some reason. I am using Windows Image Component for loading images like this:
```cpp
// imageData, size = (const char*)source, sourceDimensions.x * sourceDimensions.y * 4)
Microsoft::WRL::ComPtr<ID3D11ShaderResourceView> RenderingDevice::createTexture(const char* imageData, size_t size)
{
	Microsoft::WRL::ComPtr<ID3D11Resource> textureResource;
	Microsoft::WRL::ComPtr<ID3D11ShaderResourceView> textureView;
	if (FAILED(DirectX::CreateWICTextureFromMemory(m_Device.Get(), (const uint8_t*)imageData, size, textureResource.GetAddressOf(), textureView.GetAddressOf())))
	{
		ERR("Could not create texture from data of size: " + std::to_string(size));
	}

	return textureView;
}
```

**Comment by IronicallySerious** [comment]
I even managed to fix this too. Just redid my code that created textures from raw pixel data. This issue has long been sorted, I was not loading and using the fonts I wanted.
