### ISSUE TITLE
Content appearing vertically flipped in custom DirectX backend

### ISSUE THREAD

**Issue by IronicallySerious** [mikke89/RmlUi#101]
![image](https://user-images.githubusercontent.com/31801364/83311944-67afef00-a22e-11ea-8153-be4fb243bacc.png)
The .rml I have loaded is this:
```html
<rml>
	<head>
		<title>Demo</title>
		<style>
			p
			{
				font-family: "Lato";
				font-size: 100px;
				color: white;
			}
			body
			{
				width: 100%;
				height: 100%;
				
				margin: auto;
			}
			
			div#title_bar div#icon
			{
				display: none;
			}
			
			div#content
			{
				text-align: left;
			}
		</style>
	</head>
	<body>
		<p> This is a sample </p>
	</body>
</rml>
```
If I add an `<br /><img ... />` after the `<p> This is a sample </p>` then the image appears on the top of the text instead of appearing below it. Also, the image appears flipped vertically.
![image](https://user-images.githubusercontent.com/31801364/83312230-397edf00-a22f-11ea-90f0-4ec4bafeb40d.png)
I wonder if this is happening because it is running on DirectX, where texture origin is the top left-hand corner and maybe the RenderInterface is sending in texture data from an origin which is at the bottom left corner (and consequently the texture coordinates also start from the bottom left-hand corner). However, this is just speculation.
Would appreciate any help if possible :)

**Comment by IronicallySerious** [comment]
Fixed by flipping the Y axis coordinate of the incoming geometry in RenderGeometry() and disabling back face culling.

**Comment by mikke89** [comment]
Yes, you're right. I see you already figured this out. Just to clarify for anyone else: 

- The generated textures in RmlUi use the convention that the origin is at the bottom left corner. 
- The document layout on the other hand has the origin at the top left (in pixel coordinates).

You need to customize your transforms, shaders, or otherwise transform the data passed by the library to comply with the conventions of the graphics API you are using.

**Comment by IronicallySerious** [comment]
@mikke89 It would be nice to add this information to the docs/code-documentation. This library is awesome at first glance so I was compelled to write a renderer for it.

Also another thing I would like to add here: The reason why I had to flip the y axis coord of the incoming geometry is because DirectX uses a left handed coordinate system, whereas as APIs like OpenGL use a right handed system.

**Comment by mikke89** [comment]
I agree we could document this better. I'll add it to my todo-list :)

And yes, the OpenGL and DirectX conventions are flipped in this case, the library just happens to use the convention of the former. We should certainly document that better.
