### ISSUE TITLE
rem units incorrectly recognized as em units

### ISSUE THREAD

**Issue by aquawicket** [mikke89/RmlUi#102]
When using rem unit properties, RmlUi will incorrectly recognize them as em units.

_RmlUi will compute this as 16em_
`<a style="font-size:16rem;">Test</a>`

The issue is in PropertyParserNumber.cpp line 50
`if (units & Property::EM)` will evaluate to true. I believe this is because "em" is a substring of "rem".

Placing REM evaluation before EM will solve this issue, though i'm not sure this is the proper fix.
`if (units & Property::REM)
{
	unit_suffixes.push_back(UnitSuffix(Property::REM, "rem"));
}
if (units & Property::EM)
{
	unit_suffixes.push_back(UnitSuffix(Property::EM, "em"));
}`

**Comment by mikke89** [comment]
Thanks for reporting this! Looks like moving the order of the if-statements should fix it. But it's a bit error prone so I'm working on another solution to solve the underlying issue.

**Comment by mikke89** [comment]
Hopefully that fixes it for you :)
