### ISSUE TITLE
Trying to replicate Panorama UI ?

### ISSUE THREAD

**Issue by alinoctavian** [mikke89/RmlUi#104]
I think the best course for this project in my opinion is to replicate the panorama UI features . 
More info's here :

[Exploring Panorama](https://sandbox.facepunch.com/news/panorama-experiments)
[Dev Blog 3 - UI](https://sandbox.facepunch.com/news/devblog3)

**Comment by mikke89** [comment]
Looks interesting, thanks for the feedback. Anything in particular you are suggesting from this project?

On a related note, you should take a look at #83 which was just merged. It contains a model-view-controller approach similar to the one in Panorama by the looks of it.

**Comment by alinoctavian** [comment]
Yeah #83 looks good. 
A suggestion is to make the API a bit easier to use with a custom scripting language like (JS ([Duktape](https://duktape.org/))) or a programming like C# . Like implementing RmlUI in Unity or other engine will make the things more powerful.

A bit more about [Panorama](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Panorama)

**Comment by mikke89** [comment]
I know @uniquejack has been working on Duktape integration. So there are some efforts in this direction (and we already have Lua support of course). C# bindings and other languages would be nice. It's a bit too much work for me to handle now, but I would very much be interested in an effort from the community :)

Otherwise Panorama looks like a nice library to find some inspiration.

**Comment by alinoctavian** [comment]
Writing C# bindings isn't the hard part but integrating those bindings in a engine like Unity is the hardest part.
I know how to wrap RmlUI but i don't have any idea how to render the UI in a engine like unity , if is understandable what I mean.

**Comment by uniquejack** [comment]
I don't know about the c# wrappings, but it shouldn't be that hard to render the geometry on unity

**Comment by alinoctavian** [comment]
Does RmlUI support rendering textures ?

**Comment by mikke89** [comment]
Rendering to textures can easily be done on the user side, as RmlUi hands over all rendering calls directly to the user. Eg. in OpenGL you would just bind a framebuffer with a texture target before calling Context::Render().
