### ISSUE TITLE
RmlUI and Unity.

### ISSUE THREAD

**Issue by alinoctavian** [mikke89/RmlUi#105]
Unity current UI isn't that nice so i have in plan trying to implement RmlUI in Unity. 
I am not 100% sure how the whole process would work but from my understanding I would need to implement the abstract interfaces inside Unity using [LLNP ](https://docs.unity3d.com/Manual/NativePluginInterface.html ).

## Please correct me if I am wrong or there is something new to add.

**Comment by mikke89** [comment]
Sounds like a fun project :) I don't know anything about rendering in Unity, but the rendering API in RmlUi is quite basic, so I'm sure it should be doable. 

I'm interested in hearing updates, and will help out where I can if you encounter any issues.

**Comment by uniquejack** [comment]
I think you should generate the meshes by using the vertices and the indices you receive from rmlui and then set up the triangles.

**Comment by IronicallySerious** [comment]
Unity backend for RmlUi sounds really interesting. Makes me wonder what other kinds of backends could be written.
