### ISSUE TITLE
Link tag is too strict

### ISSUE THREAD

**Issue by aquawicket** [mikke89/RmlUi#113]
![image](https://user-images.githubusercontent.com/5370616/87848571-330ff980-c8a7-11ea-8851-391709d254e2.png)
Link tags are too strict and force the developer to include unnecessary attributes.

"Example: `<link rel="shortcut icon" id="favicon.ico" href="favicon.ico"></link>`
Error: This link will be denied because it has no type tag, even though it is a valid node.
Solution: Find and warn about missing attributes instead of asserts.

**Comment by mikke89** [comment]
I don't mind changing this to a warning. But that won't actually change its behavior though, what are you trying to accomplish?

Out of curiosity, why do you need this? If you want to handle other `link` behavior wouldn't you need to provide your own `XMLNodeHandler`?

**Comment by aquawicket** [comment]
I'm making a lite weight web browser with RmlUi. Sometimes I load pages that have link tags that might not have a type or href tag.

**Comment by mikke89** [comment]
Alright, I think that's the best way to go yes. Sounds like a fun project! :)
