### ISSUE TITLE
Context::Render() crash

### ISSUE THREAD

**Issue by rafadsm** [mikke89/RmlUi#114]
Hi, I'm trying to use RmlUi, but I'm having trouble calling the "void Context::Render()" function, it's causing a crash, I'm using the latest version published in this git
I'm trying to render it using DirectX9, I'm using the codes that were removed last year
I also don't think that the problem could be the dx9 functions that cause a problem, because there is a log indicating the call of each function and none of these functions are being triggered

I'm using visual studio 2019 win32
I am annexing the project images

the OnUpdate() function is called before the OnRender() function

![header](https://user-images.githubusercontent.com/25557084/88350629-08e88c80-cd2a-11ea-86ea-8cbbb960f1f1.png)
![cpp](https://user-images.githubusercontent.com/25557084/88350671-2ae20f00-cd2a-11ea-9884-13c880b25eb1.png)
![crash](https://user-images.githubusercontent.com/25557084/88350681-303f5980-cd2a-11ea-97e4-a5269c8aa22f.png)

**Comment by mikke89** [comment]
It seems you figured it out, but for anyone else reading: You need to make sure your interfaces are alive until after `Rml::Shutdown`. Here, they are destroyed after the return from your initialization function. Thanks for a well described issue by the way :)

Seems to be a rather common issue. Do you have any suggestions for improving the documentation on this?

**Comment by rafadsm** [comment]
the problem I had was quite strange, I copied the code from the example: https://github.com/mikke89/RmlUi/blob/master/Samples/basic/sdl2/src/main.cpp#L90
![rml1](https://user-images.githubusercontent.com/25557084/88402801-00cc3380-cda2-11ea-8a89-1a39cde2a479.png)
that kind of instantiation didn't work for m, so I changed it to type "*"
![rml2](https://user-images.githubusercontent.com/25557084/88403141-80f29900-cda2-11ea-9e46-5bd2737217cf.png)
and the interfaces worked normally, 

about the documentation, was very easy to understand and use
but to compile the source I had a problem
https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/building_with_cmake.html
you say `Create the directory RmlUi/Dependencies/freetype if it does not exist, and copy the FreeType files here.`
https://github.com/mikke89/RmlUi/blob/master/CMakeLists.txt#L92

but the correct directory is Dependency folder

![folder](https://user-images.githubusercontent.com/25557084/88407048-e9904480-cda7-11ea-9052-b5a9161abee8.png)

I am currently having a problem showing the image, but it might be a problem that I created
![gameimg](https://user-images.githubusercontent.com/25557084/88407340-5c012480-cda8-11ea-8552-724af061f399.png)
I'm also using the sample resources

**Comment by mikke89** [comment]
> the problem I had was quite strange, I copied the code from the example: 
> [...]

I see. The difference here is that the interfaces are declared in the main function and thus stay alive until the main function exits, When you refactor it into an initialization function the interfaces will be destroyed when returning from the initialization, leading to a crash when calling in to the RmlUi APIs later on.

> about the documentation, was very easy to understand and use
> but to compile the source I had a problem
> https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/building_with_cmake.html
> you say `Create the directory RmlUi/Dependencies/freetype if it does not exist, and copy the FreeType files here.`
> https://github.com/mikke89/RmlUi/blob/master/CMakeLists.txt#L92
> 
> but the correct directory is Dependency folder

Thanks for the feedback!

> I am currently having a problem showing the image, but it might be a problem that I created [...]

Yeah I'm not sure what's going on here. Looks like both the UVs and positions are way off.

**Comment by rafadsm** [comment]
is each component rendered individually? or do I get a texture with everything rendered inside?

**Comment by mikke89** [comment]
You render the draw calls submitted by RmlUi, see the [render interface documentation](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/interfaces/render.html) for details.
