### ISSUE TITLE
Clipping issues

### ISSUE THREAD

**Issue by rokups** [mikke89/RmlUi#116]
Moving my report from gitter and adding additional details.

i have a test window and when i resize it to contain all elements - scissors mess up:
![image](https://user-images.githubusercontent.com/19151258/89005698-c87ea500-d30d-11ea-975c-3d456a50bde5.png)
but if i reduce height so last element gets clipped it starts to work:
![image](https://user-images.githubusercontent.com/19151258/89005722-d2a0a380-d30d-11ea-9162-8c7fecd9eb5a.png)
i verified in renderdoc that indeed in broken variant scissor width is too wide for some reason.

Similar issue also manifests in official samples. For example this is what is visible in transform sample:
![image](https://user-images.githubusercontent.com/19151258/89005796-ffed5180-d30d-11ea-8ccb-69daff990c5b.png)

This is my sample window added to visual tests:
```html
<rml>
<head>
    <link type="text/rcss" href="../style.rcss"/>
    <title>Sample Window</title>
</head>

<body template="window" style="width: 100px;">
    <p>Sample Window</p>
    <div>
        <button>Click!</button>
        <input type="submit" disabled>Click!</input>
        <textarea>Foo...Foo...Foo...Foo...Foo...Foo...Foo...Foo...
Foo...
Foo...
Foo...
Foo...
Foo...
Foo...
Foo...
Foo...
Foo...</textarea>
        <b>Bold text</b>, <i>italic text</i>, <s><span>striked out text</span></s>.
        <hr/>
        <input type="checkbox"/> Greatness
        <br/>
        <input type="text"/>
        <select>
            <option>Foo</option>
            <option>Bar</option>
        </select>
    </div>
</body>
</rml>
```
![image](https://user-images.githubusercontent.com/19151258/89006197-d5e85f00-d30e-11ea-8e78-904b14a2aea1.png)

**Comment by mikke89** [comment]
Thanks a lot for the sample. I'll have a look at it :)

The transform sample is actually done like that intentionally (`clip: none`), so that it is visible as it spins around. But your own samples does look like a bug in RmlUi.

**Comment by rokups** [comment]
There is one more issue:
![image](https://user-images.githubusercontent.com/19151258/89781972-00ab9200-db1d-11ea-9d81-2fc85a3e897d.png)
If i resize window down to clip part of `<textarea>` or part of `<select>` at the bottom - that fixes clipping of sticking out element.

**Comment by mikke89** [comment]
Does this change work for you?

**Comment by rokups** [comment]
oh yes that fixes last issue i was having :+1:

**Comment by mikke89** [comment]
Great! The fixes have now been merged with master, so I'm closing this :)
