### ISSUE TITLE
RmlUi and Panda3D

### ISSUE THREAD

**Issue by MetaCitizenOffical** [mikke89/RmlUi#118]
Hello I'm trying to get Integrate RmlUi with Panda3D. I have successfully linked RmlUi to my project. When I build the project I get the following errors. 

Error
`1>R:\RmlUi\Include\RmlUi\Core\Event.h(147,22): error C2990: 'Factory': non-class template has already been declared as a class template
1>C:\Panda3D-1.11.0-x64\include\factory.h(34): message : see declaration of 'Factory'
1>R:\RmlUi\Include\RmlUi\Core\ElementDocument.h(179,22): error C2990: 'Factory': non-class template has already been declared as a class template
1>C:\Panda3D-1.11.0-x64\include\factory.h(34): message : see declaration of 'Factory'`

**Comment by mikke89** [comment]
Hm, looks like there is some bad mix-up with the panda3d factory, Had a quick look at their source code, and I see they don't put their classes in a namespace. Ugh. One approach is to not mix the RmlUi headers and panda headers in the same source files (at least not their factory), and rather create an intermediate file for when they need to interact. Does this work for you?

**Comment by mikke89** [comment]
Turns out this was a problem with a missing forward declaration combined with the friend class. Just learned that this is legal in C++.  Hopefully the commit fixes your issue.

**Comment by mikke89** [comment]
Closing this, as the referenced commit should fix the issue.
