### ISSUE TITLE
font-family does not apply in some circumstances

### ISSUE THREAD

**Issue by rokups** [mikke89/RmlUi#120]
```html
<rml>
    <head>
        <style>
            i
            {
                font-style: italic;
            }
            body
            {
                font-family: Blue Highway;
            }
        </style>
    </head>
    <body>
        <i>foo</i>
    </body>
</rml>
```

Produces warnings:
> No font face defined on element #text < i < body < #root#main. Please specify a font-family in your RCSS, otherwise make sure Context::Update is run after new elements are constructed, before Context::Render.
> No font face defined on element #text < i < body < #root#main. Please specify a font-family in your RCSS, otherwise make sure Context::Update is run after new elements are constructed, before Context::Render.

Warnings go away if `font-style: italic;` is removed.

**Comment by mikke89** [comment]
Did you load an italic version of the font as well as the regular font file? Otherwise I think you will get this error.

**Comment by rokups** [comment]
Opss that is right. I had fonts with italic version previously, but switched to different font set without italics. Sorry for the noise :blush:
