### ISSUE TITLE
Some attributes unusable with data binding

### ISSUE THREAD

**Issue by rokups** [mikke89/RmlUi#121]
I think we should deviate from spec a bit when it comes to attributes like `checked` or `disabled`. Currently their presence alone is enough for items to get checked or disabled. We need some attribute value that would negate that, something like `disabled="0"` would not disable element.

**Comment by mikke89** [comment]
Sounds reasonable to allow `=0` in these cases. Any other attributes like this we should look for?

**Comment by rokups** [comment]
`readonly` as well. Cant think of anything else.

**Comment by mikke89** [comment]
I looked at this a bit, and I actually think a better solution is to introduce a new data view:
```html
<input type="checkbox" data-attrif-checked="num_arms == 4"/> 
```
Because otherwise we both have to check whether or not we have the attribute and then inspect the value. It's easy to forget, has to be done in a lot of places, and the resulting code is not pretty.

**Comment by mikke89** [comment]
Does [this solution](https://mikke89.github.io/RmlUiDoc/pages/data_bindings.html#attribute-if) work for you?
