### ISSUE TITLE
textarea gets a horizontal scrollbar when it is not needed

### ISSUE THREAD

**Issue by rokups** [mikke89/RmlUi#122]
If we press enter in textarea 12 times, after last key press textarea gets a horizontal scrollbar even though there is no wide text content.

![textarea](https://user-images.githubusercontent.com/19151258/94255562-1b04c800-ff31-11ea-8f03-e4140547dafb.gif)

**Comment by mikke89** [comment]
Thanks for reporting, I'll have a look at this.

**Comment by mikke89** [comment]
I think that single-character change should fix it :)
