### ISSUE TITLE
Support lottie animations

### ISSUE THREAD

**Issue by diamondhat** [mikke89/RmlUi#125]
Hello. 

I just want to suggest lottie animation's support to your project. 

e.g. https://lottiefiles.com/

**Comment by mikke89** [comment]
Thanks for the suggestion. It looks cool. We want to stay as lightweight as possible, so this is not suitable for incorporation into the core library. Luckily, the library should be flexible enough to support this as a plugin. If the community wants to implement a plugin for this, I'll be fully supportive :)

**Comment by diamondhat** [comment]
And I would recommend to you open a discord server. Because you can achieve this:
1. Easy to use communication with others 
2. Many of big or non big projects use discord for communication and this can sometime intersects with you :) 
3. And for users will more likely use discord and you can collect big community for your project. 


And I really appreciate your project. Thank you for your work!

**Comment by mikke89** [comment]
We already have a [gitter room](https://gitter.im/RmlUi/community) for communication, feel free to join us there! And thanks for the kind words!

**Comment by diamondhat** [comment]
As I get it right you can just use rlottie library and attach to your project. 

Some point of tutorial: https://hermet.pe.kr/143
Library: https://github.com/samsung/rlottie

**Comment by mikke89** [comment]
rlottie looks pretty good. If anybody wants to implement this as a plugin in RmlUi, one approach is creating a custom element which calls into rlottie, similar to the [image element](https://github.com/mikke89/RmlUi/blob/master/Source/Core/Elements/ElementImage.h). Another approach is to use a custom decorator.

**Comment by mikke89** [comment]
See PR #134
