### ISSUE TITLE
Place already generated solution for Visual Studio

### ISSUE THREAD

**Issue by diamondhat** [mikke89/RmlUi#128]
So as every programmer should know how to use cmake, but sometimes it's quite an easy option just clone the repo and open the solution somewhere placed on windows. Because cmake can't find properly freetype dependency and it hurts enough.

And try to improve cmake generation to just writing something this: "cmake .". Because I don't remember any kind of instructions (on repositories) to use cmake-gui instead of console variant cmake.

And try to use submodules, they don't have any weight.

**Comment by rokups** [comment]
RmlUi uses CMake as it's build system. Output of CMake is not portable across systems and should not be used outside of system it was generated on. CMake cache folder even can not be moved to another folder on the same system. Given that, it would add a lot of weight maintaining multiple build systems for no real benefit.

**Comment by diamondhat** [comment]
> RmlUi uses CMake as it's build system. Output of CMake is not portable across systems and should not be used outside of system it was generated on. CMake cache folder even can not be moved to another folder on the same system. Given that, it would add a lot of weight maintaining multiple build systems for no real benefit.

Maybe, but cmake doesn't find freetype and I placed a folder to dependencies folder.

**Comment by mikke89** [comment]
Try to put the contents of the freetype folder directly into the `Dependencies` folder.

**Comment by diamondhat** [comment]
> Try to put the contents of the freetype folder directly into the `Dependencies` folder.

I placed all files from archive to dependency, but it's still doesn't work.

**Comment by mikke89** [comment]
You may need to rearrange the files a bit, see this post: https://github.com/mikke89/RmlUi/issues/114#issuecomment-663593635

**Comment by diamondhat** [comment]
> You may need to rearrange the files a bit, see this post: [#114 (comment)](https://github.com/mikke89/RmlUi/issues/114#issuecomment-663593635)

Doesn't work, I placed as cmake and without cmake content of freetype library.

**Comment by mikke89** [comment]
I updated the build instructions a bit now: https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/building_with_cmake.html
Try to follow it closely and let me know how it works :)

**Comment by diamondhat** [comment]
You were right. Thank you! 
Try to rewrite documentation like this: 
1. Download freetype from here
2. Place all folders to dependency folder
