### ISSUE TITLE
Samples for modern rendering backends

### ISSUE THREAD

**Issue by wh1t3lord** [mikke89/RmlUi#129]
It will be very cool if you (or someone) write examples on modern renderer APIs like Vulkan, Directx 12.

**Comment by mikke89** [comment]
Absolutely, this is something I'd like to see myself. This will be quite some work though, and right now I feel my time is better spent working on the main library features and fixes, I have too much on my todo list already ;) 

I'd be very happy to see a community effort though.

**Comment by wh1t3lord** [comment]
It's funny, but I close this issue by my pull request.
