### ISSUE TITLE
DataSource notifications crash at runtime

### ISSUE THREAD

**Issue by romanpunia** [mikke89/RmlUi#132]
Hi, i was integrating this amazing library into my engine and i found a bug with **DataSource** objects or i simply didn't understand how they work ¯\\_(ツ)_/¯. As pointed out in documentation there are 4 functions to update **DataSource** information:
```cpp
// Tells all attached listeners that one or more rows have been added to the data source.
void NotifyRowAdd(const String& table, int first_row_added, int num_rows_added);

// Tells all attached listeners that one or more rows have been removed from the data source.
void NotifyRowRemove(const String& table, int first_row_removed, int num_rows_removed);

// Tells all attached listeners that one or more rows have been changed in the data source.
void NotifyRowChange(const String& table, int first_row_changed, int num_rows_changed);

// Tells all attached listeners that the row structure has completely changed in the data source.
void NotifyRowChange(const String& table);
```

These functions work fine until first update of document. After first update **DataSourceListener** objects are attached. They cause access violation if you call any of **Notify** functions and it results to listener's removal. This happens for example if you remove last row from **DataGrid** and notify about the change with **NotifyRowRemove**.

![s1](https://user-images.githubusercontent.com/27789389/95393337-13ff9180-0903-11eb-8599-40ab1504d017.png)

I have fixed this behavior in my copy of RmlUi by guarding listener array in those functions, plus in destructor. It may be ugly but i didn't want to change the headers or to create new functions. Take a look:
```cpp
/* ./Source/Core/Elements/DataSource.cpp */

/* New destructor */
DataSource::~DataSource()
{
	Rml::UnorderedSet<DataSourceListener*> listeners_done;
	ListenerList listeners_copy;

notify:
	listeners_copy = listeners;
	for (ListenerList::iterator i = listeners_copy.begin(); i != listeners_copy.end(); ++i)
	{
		if (listeners_done.find(*i) != listeners_done.end())
			continue;

		(*i)->OnDataSourceDestroy(this);
		listeners_done.insert(*i);

		if (listeners_copy.size() > listeners.size())
			goto notify;
	}

	DataSourceMap::iterator iterator = data_sources.find(name);
	if (iterator != data_sources.end() &&
		iterator->second == this)
	{
		data_sources.erase(name);
	}
}

/* Changed function */
void DataSource::NotifyRowAdd(const String& table, int first_row_added, int num_rows_added)
{
	Rml::UnorderedSet<DataSourceListener*> listeners_done;
	ListenerList listeners_copy;

notify:
	listeners_copy = listeners;
	for (ListenerList::iterator i = listeners_copy.begin(); i != listeners_copy.end(); ++i)
	{
		if (listeners_done.find(*i) != listeners_done.end())
			continue;

		(*i)->OnRowAdd(this, table, first_row_added, num_rows_added);
		listeners_done.insert(*i);

		if (listeners_copy.size() > listeners.size())
			goto notify;
	}
}

/* Changed function */
void DataSource::NotifyRowRemove(const String& table, int first_row_removed, int num_rows_removed)
{
	Rml::UnorderedSet<DataSourceListener*> listeners_done;
	ListenerList listeners_copy;

notify:
	listeners_copy = listeners;
	for (ListenerList::iterator i = listeners_copy.begin(); i != listeners_copy.end(); ++i)
	{
		if (listeners_done.find(*i) != listeners_done.end())
			continue;

		(*i)->OnRowRemove(this, table, first_row_removed, num_rows_removed);
		listeners_done.insert(*i);

		if (listeners_copy.size() > listeners.size())
			goto notify;
	}
}

/* Changed function */
void DataSource::NotifyRowChange(const String& table, int first_row_changed, int num_rows_changed)
{
	Rml::UnorderedSet<DataSourceListener*> listeners_done;
	ListenerList listeners_copy;

notify:
	listeners_copy = listeners;
	for (ListenerList::iterator i = listeners_copy.begin(); i != listeners_copy.end(); ++i)
	{
		if (listeners_done.find(*i) != listeners_done.end())
			continue;

		(*i)->OnRowChange(this, table, first_row_changed, num_rows_changed);
		listeners_done.insert(*i);

		if (listeners_copy.size() > listeners.size())
			goto notify;
	}
}

/* Changed function */
void DataSource::NotifyRowChange(const String& table)
{
	Rml::UnorderedSet<DataSourceListener*> listeners_done;
	ListenerList listeners_copy;

notify:
	listeners_copy = listeners;
	for (ListenerList::iterator i = listeners_copy.begin(); i != listeners_copy.end(); ++i)
	{
		if (listeners_done.find(*i) != listeners_done.end())
			continue;

		(*i)->OnRowChange(this, table);
		listeners_done.insert(*i);

		if (listeners_copy.size() > listeners.size())
			goto notify;
	}
}
```

In original version you have **ListenerList** that copies **listeners** variable to loop safely through array that may change, but it's array of pointers so if it got changed, especially if one of listeners got deleted then local copy will contain invalid pointer to deleted object. You may use some container for listeners awaiting to be deleted. This way there will be no need to change those functions, mostly.

Thanks :)

**Comment by mikke89** [comment]
Thanks for the kind words :)

I think I understand the issue, removing a listener during notification seems to break some implicit (non-stated) contract. I do see it being useful to handle on the library side. In fact, we do something similar during event propagation. I'll take a look at it.

On a related note, can I ask you how you find the data grid and related elements? Now that we recently implemented `<table>` support, and data-bindings, I find this combination a lot more powerful and intuitive to use. I am hoping this can be a replacement for data grid. Won't remove it any time soon but I'd like to discourage the use of it.

If there are use cases where data-binding and tables are not a good replacement I'd like to hear about it. Mostly looking for any feedback in this direction. :)

**Comment by romanpunia** [comment]
Yes, you understood the problem correctly. So, i am new to this API and needed some way to present recursive tree of nodes for scene hierarchy and file system, i used [this example](https://mikke89.github.io/RmlUiDoc/pages/tutorials/datagrid_tree.html) that is referring to _Rocket Invaders_.  I agree that data-bindings are great, but i don't know how to use them for recursive structures yet, so i used data grids. Everything non-recursive and dynamic is done with data-bindings.

**Comment by mikke89** [comment]
Hm, you're right, a recursive tree might not work the best with data bindings. I need to think about that some more. Thanks for the feedback.

I tried to make a fix for the issue. Can you test it a bit to see how or if it works?

**Comment by romanpunia** [comment]
Brilliant! You have fixed the issue! I have tested all the cases that caused the crash. Amazing job man, that's rapid, thanks.
