### ISSUE TITLE
Element cloning

### ISSUE THREAD

**Issue by romanpunia** [mikke89/RmlUi#135]
Hello there, i have found a problem. I get access violation when i use **drag: clone;** on element with inner RML contents. Problem is caused by _Factory::InstanceElementText_ which wants to get document's base tag in order to parse RML. _Rml::Context_ cannot be fetched, so function fails. As i understand, there is no owner document of newly created element. I have a temporary fix that makes it work as expected:
```cpp
// Line 416
String tag = parent->GetContext()->GetDocumentsBaseTag();

// Line 416 (fix)
String tag = (parent->GetContext() ? parent->GetContext()->GetDocumentsBaseTag() : "body");
```
I used **body** as default tag in that case, maybe there should be something else, i don't really know.
Thanks for lib :)

**Comment by mikke89** [comment]
Thanks for reporting, that indeed looks like a bug :)

**Comment by romanpunia** [comment]
Thanks
