### ISSUE TITLE
Outdated docs about length formats.

### ISSUE THREAD

**Issue by eugeneko** [mikke89/RmlUi#141]
This page says:
https://mikke89.github.io/RmlUiDoc/pages/rcss/syntax.html

> Note that as RCSS is designed solely for outputting to a computer monitor, it does not recognize the physical measurements in, cm, mm, pt or pc.

However, these formats are actually supported by RmlUI. Luckily I forgot that they are not supported and accidently used them. Would be sad if I didn't try.

**Comment by mikke89** [comment]
Thanks for letting me know. I've updated the docs now.

By the way, I'd appreciate any help I can get with updating the docs. If anyone comes over anything that is incorrect or out of date, they can conveniently edit the page directly on GitHub. There's a handy "Edit on GitHub" link on all pages.
