### ISSUE TITLE
overflow in absolutely positioned input not always clipped

### ISSUE THREAD

**Issue by kim8823** [mikke89/RmlUi#143]
Hi,

I've found an issue that I couldn't quite figure out, thought I'd bring it to your attention:

An `<input>` with a too long value starts out overflowing. When selecting some text in it, then removing the selection (by clicking, arrow key, home/end or taking the focus out) the text does get clipped. Now when something else needs clipping, the `<input>` overflows again.
It only happens when the `<input>` is `position: absolute`.

This RML can reproduce the bug in my app:
```
<rml>
  <head>
    <style>
      body
      {
        font-family: "Lato";
        font-size: 20dp;
        background: white;
        color: black;
      }
      input
      {
        background: #aaaaff;
        position: absolute;
      }
      div
      {
        display: block;
        width: 50dp;
        background: #aaffaa;
      }
      div:hover
      {
        overflow: hidden;
      }
    </style>
  </head>
  <body>
    <input type="text" value="a bunch of text that's longer than the input" />
    <br />
    <div>hover here</div>
  </body>
</rml>
```
Just as described above. The 'un-clipping' happens when hovering over the text below.

**Comment by mikke89** [comment]
Thanks for posting the issue, it was easy to reproduce it for me with the RML you posted.

I'm not sure what's going on here, I will have to do a deeper dive when I have some time. In the meantime, a work-around that seemed to work for me is to wrap the input in an absolutely positioned div, and leave input's `position` alone.

**Comment by kim8823** [comment]
That workaround doesn't seem to work in my app, but the layout there isn't quite as simple as the example.

**Comment by mikke89** [comment]
This seems to fix the issue for the RML you posted. Let me know if it works for the more complicated cases.

**Comment by kim8823** [comment]
works wonderfully :100:
you rock!

**Comment by mikke89** [comment]
Great! Thanks ;)
