### ISSUE TITLE
GetOwnerDocument returns null in InstanceEventListener

### ISSUE THREAD

**Issue by actboy168** [mikke89/RmlUi#148]
I want to know which document it comes from when the event listener is initialized. But at this time the element has not been added to the document, so GetOwnerDocument returns null.
I noticed that InstanceElement has a parameter, Element parent. Does this mean that the element already has an owner?

**Comment by mikke89** [comment]
It doesn't really have an owner at that point. I'm not even sure why `parent` is passed in there. It's the calling code to `InstanceElement` that determines whether or not it gets attached to the document after being instanced.

**Comment by actboy168** [comment]
Many plugin callbacks occur in InstanceElement, which means I cannot know which element, which document and which context it belongs to.It's too bad for me.

**Comment by actboy168** [comment]
I think it is very useful for plugins that do not have a global shared state. For example, for data binding, each context has an independent datamodel namespace, but the current context cannot be obtained in <script> (for the above reasons), so the datamodel can only be created by hard-coding the context.

e.g.
``` html
<script>
	datamodel = rmlui.contexts["main"]:OpenDataModel("options", {
		enable = false,
	})
</script>
```

**Comment by mikke89** [comment]
Hm, the context should be available during the script loading phase. Perhaps we could add a global variable `document` and/or `context` to the Lua plugin, at least for inline and external scripts?

I'm not sure if this would work for the element `on..` scripts, since they are not attached to a document on execution. At least it should solve the problem in your example.

**Comment by actboy168** [comment]
In order to do this, luaplugin may need to be modified, such as preparing a separate lua global table for each context. This is also more similar to the behavior of html/js in the browser. But before that, it is necessary to get the current document at the script initialization stage.

**Comment by mikke89** [comment]
Just to be clear. The context is available on the C++-side when loading scripts (from the `<script>` tag), although they're not exposed to the Lua code. In a sense, it should be possible to just add a `context` variable to the Lua scripts. Maybe I don't completely understand the problem.

For the `on...` scripts the context is available through `document.context`.

**Comment by actboy168** [comment]
Yes, this is also the purpose of this issue.

**Comment by mikke89** [comment]
Do you mean something like that, does it solve the problem?

**Comment by actboy168** [comment]
The global variable document is only correct during the script loading phase.So this will cause errors like this

a.rml:
```
<script>
function dosomething()
print(document)
end
print(document) <-- a
dosomething()   <-- a
</script>
```
b.rml:
```
<script>
print(document) <-- b
dosomething()   <-- b
function load()
dosomething()   <-- nil
end
</script>
<body onload="load()" />
```

**Comment by actboy168** [comment]
For the `on...` scripts,I made an optimization. The current payload script, element and document are constructed during the script execution phase. In fact, they can be constructed as early as the script loading stage.

``` lua
return function (event,element,document)
   -- code
end
```

``` lua
local element,document = ...
return function (event)
   -- code
end
```

The element can be obtained during the loading phase, and the document cannot be obtained during the loading phase because GetOwnerDocument returns null.

**Comment by actboy168** [comment]
I think SetOwnerDocument should be called in InstanceElement. Or move to BindEventAttributes after calling SetOwnerDocument.

In fact, there are many differences between instantiating ElementDocument and instantiating Element. There will be two BindEventAttributes calls for ElementDocument. The first call, the attribute is empty, so nothing is done. SetOwnerDocument will be called before the second call, so it is fine. For Element, there is only one BindEventAttributes call, and there is no onwer document.

No matter what the changes are, I think the instantiation of ElementDocument and Element should be the same.

**Comment by mikke89** [comment]
We cannot set the owner document in InstanceElement, as the element has not yet been attached to the document tree, and this is not the right place to do so either.

Binding the event attributes after SetOwnerDocument is also problematic. This will repeatedly be called as the element is detached and attached to the document tree. Thus, now we need a way to remove the event attributes whenever the element is removed (and only them, not the other attached events bound through the C++ API), and then rebind them as we attach the element to the same or another document tree again. As you can understand, this quickly becomes complicated.

An important consideration is that elements can in principle be moved between documents, they are not tied to any specific one. 

I'd prefer it if we could resolve this without modifying Core. I think my suggestions in my previous post should be workable, even if it is not ideal. However, if you do not find that solution suitable, what we could do is send along the `parent` element to `EventListenerInstancer::InstanceEventListener` which you should be able to retrieve the document from in the typical case.

**Comment by actboy168** [comment]
Thank you for your clarification. I had some wrong understanding before. Allowing elements to move between different documents does limit this.

I plan to make script and html+js behave more similarly. This is my motivation for making these changes.

I found a way to solve it. Register an instancer for all elements, and then call SetOwnerDocument in my instancer. This is valid for elements other than ElementDocument.

**Comment by mikke89** [comment]
Alright, I'm glad you found a work-around. :)
