### ISSUE TITLE
Document building on Windows

### ISSUE THREAD

**Issue by IngwiePhoenix** [mikke89/RmlUi#149]
So I just came across this and went in blind and did my usual `mkdir build; cd build; cmake -GNinja ..; ninja -j24` to see what happens. I was immediately noted that there was no FreeType available - which, due to the nature of Windows, was not exactly in a standard location. In fact, I don't think I have it installed.

What is the recommended way to build RmlUI on Windows?

Thanks in advance!

**Comment by mikke89** [comment]
Hi! You can have a look at the [build documentation](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/building_with_cmake.html). If there is anything that is unclear, please let me know :)

**Comment by IngwiePhoenix** [comment]
Thanks, I got it to work! :) 

Question is though, why aren't you adding FreeType as a direct dependency via Git module and use FreeType2's CMake interface?

This, specifically: https://github.com/aseprite/freetype2/blob/master/CMakeLists.txt#L339-L344

Not a big deal, but just a thing of curiosity :) I have a few more questions but before I ask those, I will try to see if I can find my answers in the docs first. Thanks for this awesome project!

**Comment by mikke89** [comment]
Great! And thanks!

The main reason for that is that some users prefer to use FreeType from a package manager or their system repository, or they are already using FreeType in their project. In which case they avoid having two copies of the library. Git submodules aren't a good substitution for package managers, but of course we all wish this whole situation was better in the C++ world.
