### ISSUE TITLE
Unable to update image

### ISSUE THREAD

**Issue by actboy168** [mikke89/RmlUi#153]
The code looks like this:
```html
<div data-for="img: imgs">
    <div data-style-decorator="img.value" />
</div>
```
Or
```c++
element->SetProperty("decorator", "image(\"test.png\")");
```

It seems that when the image property is updated, the property needs to provide a PropertySource.

**Comment by mikke89** [comment]
I see, this is indeed something we should fix, thanks for letting me know. I have a solution for this working locally now, will test it some more tomorrow and upload.

**Comment by mikke89** [comment]
Hope this works for you, let me know.

**Comment by actboy168** [comment]
Thanks, it's working now. 

Can you merge it into the `data_bindging` branch?

**Comment by mikke89** [comment]
Great, just merged it :)
