### ISSUE TITLE
Deprecating things

### ISSUE THREAD

**Issue by mikke89** [mikke89/RmlUi#16]
I think this is a good time to deprecate things that seem really out-of-date. For example, the docs mention Python 2.5 (!) support only. Generally I think Lua is the better way for our audience, being a lot easier to integrate. My impression is that Lua is much more wide-spread in the game-dev community at least.

A list of things which I suggests we remove completely:

- Python support
- SFML 1 (but keep SFML 2)
- DirectX 9
- Ogre3d? (It seems the supported version is really out of date, dating back almost a decade)
- Removing the datagrid. This is already broken as of now, and to me it never did work so well. I think implementing table support instead would be a better approach perhaps?

**Comment by viciious** [comment]
What is exactly broken in the datagrid? I think it's an essential widget, regardless of its performance.
The rest I don't care for really, feel free to cut it out :P

**Comment by viciious** [comment]
The Clipboard thing should be deprecated in favour of two new additional API calls Get/SetClipboardData. The way it operates now isn't portable and it has always looked like a hack to me.

**Comment by mikke89** [comment]
Right now, they don't expand to the table width. Not sure where I broke it :P Okey, let's keep it. Hopefully the new performance improvements coming up will improve it as well.
Great, I'll go get my scythe then!

Agreed on the Clipboard get/set!

**Comment by barotto** [comment]
After the recent mouse cursor changes, Python support is now broken:
```
Source/Core/Python/ContextInterface.cpp:52:27: error: ‘AddMouseCursor’ is not a member of ‘Rocket::Core::Context’
   .def("AddMouseCursor", &Context::AddMouseCursor, python::return_value_policy< python::return_by_value >())
                           ^
```

I think the Ogre3D sample is also broken for the same reason.

I think it's time to remove Python support and the SFML 1, DirectX 9, and Ogre3d samples.

(would be nice to add Vulkan & DX12 samples instead....)

**Comment by mikke89** [comment]
You're right, it's time to remove them. I'll be out traveling for the rest of the week, but will get around to it next week.

And Vulkan/DX12 samples would be really sweet. I have no experience with these, so if anyone is up to the challenge... :)

**Comment by mikke89** [comment]
Closing this, deprecated features were removed in #26.

The old clipboard get/setters have been replaced by system interface calls in the performance branch, commit 9ec34390be75bc17245c34bd0187a3e477c5e72c.

As for Vulkan/DX12 samples, this will have to be a longer term goal.
