### ISSUE TITLE
File path normalization creates leading "/" in some cases

### ISSUE THREAD

**Issue by noam-c** [mikke89/RmlUi#161]
### Reproduction

Initialize an `img` element with `src="data/gui/../../data/images/icons/blue.png"`, or otherwise create a `Url` object with that string as a path.

#### Expected
Path normalizes to `data/images/icons/blue.png`

#### Actual
Path normalizes to `/data/images/icons/blue.png`, which is unlikely to successfully resolve in the filesystem because it is an absolute path.

### Analysis
As far as I can tell, my program was able to successfully resolve the path a few years ago on libRocket, but cannot now on RmlUi 3.3.  The normalization algorithm hasn't fundamentally changed since 2010 when it was initially authored, though I do see a couple of tweaks have been made since forking.

My hypothesis at the moment is that [fixing an off-by-one error](https://github.com/mikke89/RmlUi/commit/603fd40568ead2233cd4129de2a3e371366b7cfe) made it possible to encounter this problem, and that this algorithm was likely incomplete since its inception 10 years ago. A standard algorithm for normalization is detailed on cppreference.com in the [std::filesystem::path](https://en.cppreference.com/w/cpp/filesystem/path) page. Excerpted here:

1. If the path is empty, stop (normal form of an empty path is an empty path)
2. Replace each directory-separator (which may consist of multiple slashes) with a single `path::preferred_separator`.
3. Replace each slash character in the root-name with `path::preferred_separator`.
4. Remove each dot and any immediately following directory-separator.
5. Remove each non-dot-dot filename immediately followed by a directory-separator and a dot-dot, *along with any immediately following directory-separator*.
6. If there is root-directory, remove all dot-dots and any directory-separators immediately following them.
7. If the last filename is dot-dot, remove any trailing directory-separator.
8. If the path is empty, add a dot (normal form of ./ is .)

I believe that the issue is in step 5 -- only one occurrence of "/.." is removed at [this line](https://github.com/mikke89/RmlUi/blob/7727bbbbd67ecfa30466bbb0f43ccd9edfd4b24b/Source/Core/URL.cpp#L233), which means any immediately following directory-separator is left behind and potentially becomes a leading "/".

### Unrelated aside
RmlUi has been really amazing so far. I deeply appreciate all the effort that the maintainers have put into using the STL instead of reinventing it, using modern C++ features (especially `std::shared_ptr`!), and above all the excellent quality of the documentation. It took me only a day to port my project from 2013-era libRocket to RmlUi, because of the thorough changelog and Getting Started docs. Thank you!

**Comment by mikke89** [comment]
First of all, thanks a lot for great issue report, it's a breeze to read. And also for the kind words, I've put a lot of effort into the documentation so I'm happy to hear your appreciation :)

I've mostly tried to stay away from the URL stuff, just because I've been worried about breaking peoples code. I see I didn't entirely succeed, heh. Although I have actually wanted to remove the URL class entirely for some time now, and replace it with two functions that I'm pretty sure would cover all the needs of this library: `NormalizePath` and `JoinPath`. They should both be overloadable by users (one of which already is). Maybe it's time to do that.

The `std::filesystem::path` is a great resource. I'm not sure if we should follow it precisely though. Eg URLs starting with `file://` would be shortened to `file:/`. Then again, I'm not sure how useful it is to have protocols like that in this library, we're not trying to access the web, although it could be useful for users to use protocols to load from different places.

I made a pretty big list of unit tests, and I can certainly spot the problem you have there. Relative paths sometimes become absolute paths.

I'll post the tests below. We certainly don't pass all of these right now. If you and anyone else could provide feedback on these tests, that would be great, I'm not sure how best to handle all cases. Then I can integrate these two functions mentioned above, make sure they pass the tests, and replace the URL class entirely. What do you think?

```cpp
	CHECK(Normalize("blue") == "blue");
	CHECK(Normalize("blue.png") == "blue.png");
	CHECK(Normalize("/blue.png") == "/blue.png");
	CHECK(Normalize("/data/blue.png") == "/data/blue.png");
	CHECK(Normalize("../data/blue.png") == "../data/blue.png");

	CHECK(Normalize("data/blue.png") == "data/blue.png");
	CHECK(Normalize("data/../blue.png") == "blue.png");
	CHECK(Normalize("./data/blue.png") == "data/blue.png");
	CHECK(Normalize("./data/../blue.png") == "blue.png");

	CHECK(Normalize("x./data/blue.png") == "x./data/blue.png");
	CHECK(Normalize("x./data/../blue.png") == "x./blue.png");
	CHECK(Normalize("/x./data/blue.png") == "/x./data/blue.png");
	CHECK(Normalize("/x./data/../blue.png") == "/x./blue.png");

	CHECK(Normalize("/data/blue.png") == "/data/blue.png");
	CHECK(Normalize("/data/../blue.png") == "/blue.png");
	CHECK(Normalize("/./data/blue.png") == "/data/blue.png");
	CHECK(Normalize("/./data/../blue.png") == "/blue.png");

	CHECK(Normalize("data/../../blue.png") == "../blue.png");
	CHECK(Normalize("data/../../../blue.png") == "../../blue.png");
	CHECK(Normalize("./data/../../blue.png") == "../blue.png");
	CHECK(Normalize("./data/../../../blue.png") == "../../blue.png");

	CHECK(Normalize("data/gui/../../data/images/icons/blue.png") == "data/images/icons/blue.png");
	CHECK(Normalize("/data/gui/../../data/images/icons/blue.png") == "/data/images/icons/blue.png");

	CHECK(Normalize("") == "");
	CHECK(Normalize("./") == "");
	CHECK(Normalize("../") == "../");
	CHECK(Normalize("/") == "/");
	CHECK(Normalize("/../") == "/../");

	CHECK(Normalize("data//blue.png") == "data/blue.png");
	CHECK(Normalize("data//./blue.png") == "data/blue.png");
	CHECK(Normalize("data//../blue.png") == "blue.png");

	CHECK(Normalize("file://data/blue.png") == "file://data/blue.png");
	CHECK(Normalize("file://data/../blue.png") == "file://blue.png");
	CHECK(Normalize("file:///data/../blue.png") == "file:///blue.png");

	CHECK(Normalize("file://data/blue.png") == "file://data/blue.png");
	CHECK(Normalize("file://data/blue.png") == "file://data/blue.png");
	CHECK(Normalize("file://data/../blue.png") == "file://blue.png");

	CHECK(Normalize("C:/data/blue.png") == "C:/data/blue.png");
	CHECK(Normalize("C:/data/./blue.png") == "C:/data/blue.png");
	CHECK(Normalize("C:/data./blue.png") == "C:/data./blue.png");
	CHECK(Normalize("C:/data/../blue.png") == "C:/blue.png");

	CHECK(Normalize(R"(C:\data\blue.png)") == "C:/data/blue.png");
	CHECK(Normalize(R"(C:\data\.\blue.png)") == "C:/data/blue.png");
	CHECK(Normalize(R"(C:\data.\blue.png)") == "C:/data./blue.png");
	CHECK(Normalize(R"(C:\data\..\blue.png)") == "C:/blue.png");

	CHECK(JoinPath("data/gui/d.rml", "../../data/images/icons/blue.png") == "data/images/icons/blue.png");
	CHECK(JoinPath("/d.rml", "../data/images/icons/blue.png") == "/../data/images/icons/blue.png");
	CHECK(JoinPath("/data/d.rml", "../images/icons/blue.png") == "/images/icons/blue.png");
	CHECK(JoinPath("/data/d.rml", "../../images/icons/blue.png") == "/../images/icons/blue.png");

	CHECK(JoinPath("data/gui/d.rml", "/../../images/icons/blue.png") == "/../../images/icons/blue.png");
	CHECK(JoinPath("data/gui/d.rml", "/images/icons/blue.png") == "/images/icons/blue.png");
	CHECK(JoinPath("/data/gui/d.rml", "/../../images/icons/blue.png") == "/../../images/icons/blue.png");
	CHECK(JoinPath("/data/gui/d.rml", "/images/icons/blue.png") == "/images/icons/blue.png");

	CHECK(JoinPath("data/gui/d.rml", "./../images/icons/blue.png") == "data/images/icons/blue.png");
	CHECK(JoinPath("/d.rml", "./data/images/icons/blue.png") == "/data/images/icons/blue.png");
	CHECK(JoinPath("/data/d.rml", "./images/icons/blue.png") == "/data/images/icons/blue.png");
	CHECK(JoinPath("/data/d.rml", "./../images/icons/blue.png") == "/images/icons/blue.png");
	CHECK(JoinPath("/data/d.rml", "./../../images/icons/blue.png") == "/../images/icons/blue.png");

	CHECK(JoinPath(R"(C:\data\d.rml)", R"(blue.png)") == R"(C:/data/blue.png)");
	CHECK(JoinPath(R"(C:\data\d.rml)", R"(../blue.png)") == R"(C:/blue.png)");
	CHECK(JoinPath(R"(C:\data\d.rml)", R"(..\blue.png)") == R"(C:/blue.png)");
	CHECK(JoinPath(R"(C:\data\d.rml)", R"(../../blue.png)") == R"(C:/../blue.png)");

	CHECK(JoinPath(R"(C:\data\d.rml)", R"(/blue.png)") == R"(/blue.png)");
	CHECK(JoinPath(R"(C:\data\d.rml)", R"(/../blue.png)") == R"(/../blue.png)");
	CHECK(JoinPath(R"(C:\data\d.rml)", R"(/..\blue.png)") == R"(/../blue.png)");
	CHECK(JoinPath(R"(C:\data\d.rml)", R"(/../../blue.png)") == R"(/../../blue.png)");

	CHECK(JoinPath("file://C:/data/d.rml", "img/blue.png") == "file://C:/data/img/blue.png");
	CHECK(JoinPath("file://data/d.rml", "img/blue.png") == "file://data/img/blue.png");
	CHECK(JoinPath("file://C:/data/d.rml", "img/../blue.png") == "file://C:/data/img/blue.png");
	CHECK(JoinPath("file://data/d.rml", "img/../../blue.png") == "file://blue.png");

	CHECK(JoinPath("file://data/d.rml", "file://C:/data/blue.png") == "file://C:/data/blue.png");
	CHECK(JoinPath("file://data/d.rml", "file://C:/data/../blue.png") == "file://C:/blue.png");

	CHECK(JoinPath("file://data/d.rml", "file://data/blue.png") == "file://data/blue.png");
	CHECK(JoinPath("file://data/d.rml", "file://data/../blue.png") == "file://blue.png");
	CHECK(JoinPath("file://data/d.rml", "file:///data/../blue.png") == "file:///blue.png");
	CHECK(JoinPath("file://data/d.rml", "file://data/../blue.png") == "file://blue.png");
```

**Comment by noam-c** [comment]
Thank you for the quick and thorough response, @mikke89!
I'll give the tests a look, but before I do, the API that you're proposing gave me an idea that I wanted to run by you.

I think it makes sense to let the client interpret the paths since the work to load those resources _also_ happens on the client. However, `Normalize` and `JoinPath`, are really specific functionality. One can easily implement `Normalize` and `JoinPath`, but if RmlUi is delegating that responsibility then it means we are making the assertion that interpreting a path string is complicated and client-specific.

I wonder if what RmlUi really needs is a more general interface (same functions, more general names). For example, renaming `JoinPath` to `GetResourcePath(rmlPath, resourcePath) ` returns a path that the client can understand, whatever that may be. This would make it useful for implementing features like:
* Custom resource schemes if someone wanted to implement custom protocols (e.g. a client could put `"spritesheet://titlemenu"` into their RCSS or RML, and then internally map it to `"data/spritesheets/titlemenu.png"`)
* Web URL support, for those clients that need it -- if a client needs `file://` _and_ `http://` then it's up to them

Alternatively, RmlUi can get out of the business of path interpretation entirely, passing the path to methods like `LoadTexture` without any normalization or joining (but pass the originating RML file). This reduces the surface area of RmlUi and makes fewer assumptions about the client code's needs, but also makes implementing a `RenderInterface` more complex.

What do you think?

**Comment by mikke89** [comment]
I do like the purity of your latter proposed solution. However I feel it would be very invasive in the API, especially considering that most users would just want to do path merging as today. Plus, it would break pretty much everyone's builds. Another consideration is that we would need to figure out how to do doubly linked resources (eg. image files in external style sheets). And in that sense I feel like `JoinPath` makes the most sense.

Ideally, I think our approach should support the following out of the box:

- Windows-style absolute paths
- Unix-style absolute paths
- URI-style path with protocol, but without support for `?` and `#` parts
- And relative paths to all of the above.

But what do we do if eg. an URI path `file://gui/document.rml` meets a path of the type `/styles/style.rcss`? In URI land that should result in `file://gui/styles/style.rcss`, but it's also an absolute path on Unix, so in that sense we should just return it.

Maybe we're overthinking this and should just fix the original bug you had :P In a sense, we kind of support most of these schemes already, although some of it is very hacked together, and the URL class is really large and complex and only used for normalization I believe.

**Comment by noam-c** [comment]
Hmm, I agree that plucking it out of the API now would break quite a few builds. What would be the plan after rolling out this change? Would you retain the legacy `Url`-based normalization as a default, or eventually deprecate it?

In any case, I don't want to let perfect become the enemy of good here -- your proposal is a solid step forward.

I've looked at the normalize tests so far and most of them make sense to me. The only one I object to might be on subjective grounds. ;)

I'll add another comment with the `JoinPath` tests this week, but I think this all makes sense so far.

# Normalize Tests

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"blue"` | `"blue"` | ✔️ |
|`"blue.png"` | `"blue.png"` | ✔️ |
|`"/blue.png"` | `"/blue.png"` | ✔️ |
|`"/data/blue.png"` | `"/data/blue.png"` | ✔️ |
|`"../data/blue.png"` | `"../data/blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"data/blue.png"` | `"data/blue.png"` | ✔️ |
|`"data/../blue.png"` | `"blue.png"` | ✔️ |
|`"./data/blue.png"` | `"data/blue.png"` | ✔️ |
|`"./data/../blue.png"` | `"blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"x./data/blue.png"` | `"x./data/blue.png"` | ✔️ |
|`"x./data/../blue.png"` | `"x./blue.png"` | ✔️ |
|`"/x./data/blue.png"` | `"/x./data/blue.png"` | ✔️ |
|`"/x./data/../blue.png"` | `"/x./blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"/data/blue.png"` | `"/data/blue.png"` | ✔️ |
|`"/data/../blue.png"` | `"/blue.png"` | ✔️ |
|`"/./data/blue.png"` | `"/data/blue.png"` | ✔️ |
|`"/./data/../blue.png"` | `"/blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"data/../../blue.png"` | `"../blue.png"` | ✔️ |
|`"data/../../../blue.png"` | `"../../blue.png"` | ✔️ |
|`"./data/../../blue.png"` | `"../blue.png"` | ✔️ |
|`"./data/../../../blue.png"` | `"../../blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"data/gui/../../data/images/icons/blue.png"` | `"data/images/icons/blue.png"` | ✔️ |
|`"/data/gui/../../data/images/icons/blue.png"` | `"/data/images/icons/blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`""` | `""` | ✔️ |
|`"./"` | `""` | IMO, not equivalent. Returning `"./"` makes sense, though. |
|`"../"` | `"../"` | ✔️ |
|`"/"` | `"/"` | ✔️ |
|`"/../"` | `"/../"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"data//blue.png"` | `"data/blue.png"` | ✔️ |
|`"data//./blue.png"` | `"data/blue.png"` | ✔️ |
|`"data//../blue.png"` | `"blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"file://data/blue.png"` | `"file://data/blue.png"` | ✔️ |
|`"file://data/../blue.png"` | `"file://blue.png"` | ✔️ |
|`"file:///data/../blue.png"` | `"file:///blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"file://data/blue.png"` | `"file://data/blue.png"` | ✔️ |
|`"file://data/blue.png"` | `"file://data/blue.png"` | Duplicate of above? |
|`"file://data/../blue.png"` | `"file://blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`"C:/data/blue.png"` | `"C:/data/blue.png"` | ✔️ |
|`"C:/data/./blue.png"` | `"C:/data/blue.png"` | ✔️ |
|`"C:/data./blue.png"` | `"C:/data./blue.png"` | ✔️ |
|`"C:/data/../blue.png"` | `"C:/blue.png"` | ✔️ |

|Input|Output|Comments|
|:-----|:------|:--------:|
|`R"(C:\data\blue.png)"` | `"C:/data/blue.png"` | ✔️ |
|`R"(C:\data\.\blue.png)"` | `"C:/data/blue.png"` | ✔️ |
|`R"(C:\data.\blue.png)"` | `"C:/data./blue.png"` | ✔️ |
|`R"(C:\data\..\blue.png)"` | `"C:/blue.png"` | ✔️ |

**Comment by noam-c** [comment]
I lied -- I went through them immediately afterwards. ;)

Two notes: Like you mentioned, I have no idea what the expected behavior should be for `file://`. Is that currently supported in RmlUi? If so, then the proposals seem sensible to me, but I wonder: what would be the expected output for `JoinPath("file://data/gui/d.rml", "file://../icons/blue.png")`? In other words, do we always treat file protocol as absolute, or is it just the exact same path with the `file://` removed?

Another issue is one I didn't catch before, but comes up again in the second `JoinPath` test case and others. Going "out of" the root directory shouldn't be possible, right? So any `../` segments that try to escape root (or the drive root) should be normalized out. What do you think?

# JoinPath Tests

|Origin|Path|Output|Comments|
|:-----|:------|:------|:--------:|
| `"data/gui/d.rml"` | `"../../data/images/icons/blue.png"` | `"data/images/icons/blue.png"` | ✔️ |
| `"/d.rml"` | `"../data/images/icons/blue.png"` | `"/../data/images/icons/blue.png"` | `/..` doesn't make sense though, right? You can't go above root? So really, `Normalize("/../")` would become `"/"`? |
| `"/data/d.rml"` | `"../images/icons/blue.png"` | `"/images/icons/blue.png"` | ✔️ |
| `"/data/d.rml"` | `"../../images/icons/blue.png"` | `"/../images/icons/blue.png"` | See case 2 |

|Origin|Path|Output|Comments|
|:-----|:------|:------|:--------:|
| `"data/gui/d.rml"` | `"/../../images/icons/blue.png"` | `"/../../images/icons/blue.png"` | ✔️ |
| `"data/gui/d.rml"` | `"/images/icons/blue.png"` | `"/images/icons/blue.png"` | ✔️ |
| `"/data/gui/d.rml"` | `"/../../images/icons/blue.png"` | `"/../../images/icons/blue.png"` | ✔️ but this case makes me think we need a name other than `JoinPath`, since two absolutes don't actually become "joined" |
| `"/data/gui/d.rml"` | `"/images/icons/blue.png"` | `"/images/icons/blue.png"` | ✔️ |

|Origin|Path|Output|Comments|
|:-----|:------|:------|:--------:|
| `"data/gui/d.rml"` | `"./../images/icons/blue.png"` | `"data/images/icons/blue.png"` | ✔️ |
| `"/d.rml"` | `"./data/images/icons/blue.png"` | `"/data/images/icons/blue.png"` | ✔️ |
| `"/data/d.rml"` | `"./images/icons/blue.png"` | `"/data/images/icons/blue.png"` | ✔️ |
| `"/data/d.rml"` | `"./../images/icons/blue.png"` | `"/images/icons/blue.png"` | ✔️ |
| `"/data/d.rml"` | `"./../../images/icons/blue.png"` | `"/../images/icons/blue.png"` | See case 2 |

|Origin|Path|Output|Comments|
|:-----|:------|:------|:--------:|
| `R"(C:\data\d.rml)"` | `R"(blue.png)"` | `R"(C:/data/blue.png)"` | ✔️ |
| `R"(C:\data\d.rml)"` | `R"(../blue.png)"` | `R"(C:/blue.png)"` | ✔️ |
| `R"(C:\data\d.rml)"` | `R"(..\blue.png)"` | `R"(C:/blue.png)"` | ✔️ |
| `R"(C:\data\d.rml)"` | `R"(../../blue.png)"` | `R"(C:/../blue.png)"` | Can't go "above" `C:\` |

|Origin|Path|Output|Comments|
|:-----|:------|:------|:--------:|
| `R"(C:\data\d.rml)"` | `R"(/blue.png)"` | `R"(/blue.png)"` | ✔️ |
| `R"(C:\data\d.rml)"` | `R"(/../blue.png)"` | `R"(/../blue.png)"` | See case 2 |
| `R"(C:\data\d.rml)"` | `R"(/..\blue.png)"` | `R"(/../blue.png)"` | See case 2 |
| `R"(C:\data\d.rml)"` | `R"(/../../blue.png)"` | `R"(/../../blue.png)"` | See case 2 |

|Origin|Path|Output|Comments|
|:-----|:------|:------|:--------:|
| `"file://C:/data/d.rml"` | `"img/blue.png"` | `"file://C:/data/img/blue.png"` | ✔️ |
| `"file://data/d.rml"` | `"img/blue.png"` | `"file://data/img/blue.png"` | ✔️ |
| `"file://C:/data/d.rml"` | `"img/../blue.png"` | `"file://C:/data/img/blue.png"` | Expected `"file://C:/data/blue.png"` |
| `"file://data/d.rml"` | `"img/../../blue.png"` | `"file://blue.png"` | ✔️ |

|Origin|Path|Output|Comments|
|:-----|:------|:------|:--------:|
| `"file://data/d.rml"` | `"file://C:/data/blue.png"` | `"file://C:/data/blue.png"` | ✔️ |
| `"file://data/d.rml"` | `"file://C:/data/../blue.png"` | `"file://C:/blue.png"` | ✔️ |

|Origin|Path|Output|Comments|
|:-----|:------|:------|:--------:|
| `"file://data/d.rml"` | `"file://data/blue.png"` | `"file://data/blue.png"` | ✔️ |
| `"file://data/d.rml"` | `"file://data/../blue.png"` | `"file://blue.png"` | ✔️ |
| `"file://data/d.rml"` | `"file:///data/../blue.png"` | `"file:///blue.png"` | ✔️ |
| `"file://data/d.rml"` | `"file://data/../blue.png"` | `"file://blue.png"` | ✔️ |

**Comment by noam-c** [comment]
Fixing the bug in a targeted way for 4.0 makes a lot of sense, so that sounds good to me!

If you're saving the larger change for 5.0, do you plan for it to still look like your current proposal, or are you open to a deeper change like the other ideas we discussed in the thread? I can see an argument for either approach.

**Comment by mikke89** [comment]
Alright, great!

Everything we have discussed here will be very useful for 5.0. I won't make promises now, but I'm open to most of the things we've discussed.

**Comment by mikke89** [comment]
This was put on the back burner for a while, but I've finally gotten around to trying to fix the issue originally reported. Let me know if there are any issues.

**Comment by mikke89** [comment]
I'm closing this for now as we fixed the initial bug. We can open a new issue for the other improvements discussed when desired.

**Comment by noam-c** [comment]
@mikke89 I apologize for the delay in response -- I finally got some time to migrate to RmlUi 4.0, and confirmed that the issue has been fixed. I can specify the paths as I'd expect them to work, without needing the workarounds that I applied while using RmlUi 3.3. Thank you so much for your help. And, of course, thanks for the straightforward upgrade guide. 🙂
