### ISSUE TITLE
Transition: all fails to compile

### ISSUE THREAD

**Issue by Dakror** [mikke89/RmlUi#163]
The RCSS property `transition` does not support the `all` value correctly. Looking into the history of the PropertyParserAnimation, this must have broken when changing from property names to ids, since the parsing error arises here: https://github.com/mikke89/RmlUi/blob/9f195446f8d6e4405d936ba718e0901affd8086e/Source/Core/PropertyParserAnimation.cpp#L334

Back when strings were used, a property with name "all" was added to the property list [1], which now is empty

[1] https://github.com/mikke89/RmlUi/commit/93dd452fbd0c67a348e1a5c5df15ee155815d48e#diff-563e418bcc69ad0b05163f26c0174b84ff59c845532cf151cbfc5c5e903d5427L266

When i tried the small change of altering the parser validation to `if ((!transition_list.all && target_property_ids.Empty()) || transition.duration <= 0.0f || transition.reverse_adjustment_factor < 0.0f || transition.reverse_adjustment_factor > 1.0f)`
a vector out of bounds occurs as soon as we try to run the transition.

**Comment by mikke89** [comment]
Alright, I made an effort at fixing this. Let me know if it doesn't work or any other issues appear.

**Comment by Dakror** [comment]
looks fixed to me.
