### ISSUE TITLE
Issues for RmlUiDoc

### ISSUE THREAD

**Issue by barotto** [mikke89/RmlUi#18]
Can you enable GitHub's Issues for RmlUiDoc?

**Comment by mikke89** [comment]
Ah, of course, didn't realize it wasn't enabled.

**Comment by barotto** [comment]
Nice thanks!

**Comment by mikke89** [comment]
I see you started working on it, thanks a ton! :)

**Comment by barotto** [comment]
I'm can't really contribute to main code, so I'll try to improve docs and do some Linux testing.

**Comment by mikke89** [comment]
Helping out where you can, it's all very much appreciated!
