### ISSUE TITLE
Scroll bar performance issues

### ISSUE THREAD

**Issue by liupan1890** [mikke89/RmlUi#181]
RmlUi 3.3 RmlUi-win64-samples-only.zip  

### 1. windows10 2004 Scroll bar performance issues

When the UI contains scrollbars, the CPU utilization is abnormally high (24%)

When the UI does not contain scrollbars, the CPU utilization is normal (1-2%)

When the window is not activated and there is no operation (that is, when the UI does not need to be refreshed), the CPU utilization rate has not been reduced to 0%, and has been maintained at about 1%

I think when the UI doesn't need to be refreshed, the CPU utilization should be 0%

-----
![屏幕截图25](https://user-images.githubusercontent.com/67817756/112792735-98eb8c80-9096-11eb-86a2-915622ffc47e.png)
-----
![屏幕截图help25](https://user-images.githubusercontent.com/67817756/112792744-9be67d00-9096-11eb-889d-a18c92a85b7d.png)
-----
#### RmlUi-win64-samples-only\invaders.exe
Above image is invaders.exe Help page, including scroll bar, cpu25%
Below image is invaders.exe Scores page, does not contain scrollbars, CPU1.8%

-----
![屏幕截图scores1 6](https://user-images.githubusercontent.com/67817756/112792769-a6087b80-9096-11eb-93f5-382997b9216d.png)
-----
![屏幕截图2aaa](https://user-images.githubusercontent.com/67817756/112792758-a1dc5e00-9096-11eb-9062-5cb0ec67d936.png)
-----
![屏幕截图1](https://user-images.githubusercontent.com/67817756/112792777-a99c0280-9096-11eb-8a6d-d1c79944e50e.png)

### 2. windows7 sp1 (in vmware) performance issues

For all windows, the CPU utilization rate is abnormally high (20-24%)

-----
![屏幕截图 win7 20](https://user-images.githubusercontent.com/67817756/112792786-ae60b680-9096-11eb-9fb6-cc17c2bfacdd.png)

**Comment by Dakror** [comment]
Try again on master, RmlUi has changed a lot since 3.3. Also maybe perform some profiling to investigate it further?

**Comment by liupan1890** [comment]
Sorry, I just want to quickly preview the final effect through samples before I decide to use it.



I just found it https://github.com/mikke89/RmlUi/releases V3.3 released on June 29, 2020



Why hasn't any v4.0 samples been released in the past nine months?



I know that the final development of v4.0 may not be completed, but we should release the preview version samples regularly for other users to preview, right?



Please release the preview program of the latest version of v4.0 samples. I don't want to configure various environments and compile v4.0 just to see the running effect



I think it helps others as well

**Comment by liupan1890** [comment]
> Try again on master, RmlUi has changed a lot since 3.3. Also maybe perform some profiling to investigate it further?


I can't find the releases on master

I just found it https://github.com/mikke89/RmlUi/releases V3.3 released on June 29, 2020

**Comment by mikke89** [comment]
Alright, I did some investigation into this.

What I want to say first is that we do not make any attempt at reducing power consumption in the sample shell implementation. That has just not been a priority. Since users of the library are in full control of the rendering loop, ultimately they decide how they deal with such matters. Since our shell doesn't even say whether or not to use vsync, pretty much everything in terms of power usage depends on the GPU driver.

On the weird performance differences you see, I can generally see the same kind of overall trends that you observed. Some profiling reveals that the CPU is hogged during some arbitrary external GPU drawing commands. This has nothing to do with the scrollbar or any particular library usage, seems to generally depend on the complexity of the scene / number of draw calls perhaps? Not sure exactly what is triggering this, but seems quite clear that this is a GPU driver quirk. This seems to only happen on my Nvidia GPU, and some further research indicates [there might be some quirks there](https://stackoverflow.com/a/21929019). My AMD GPU does not display this behavior and uses a lot less CPU when vsync is enabled.

So what can or should we do about this? In my opinion, nothing. This is not a library issue, and power consumption is not important for a few sample applications. Furthermore, users will have differing performance vs power consumption requirements, thus any solution we propose will not be useful for all. Ultimately, controlling power consumption is a client-side task.

FYI, you can download the samples of every commit [on appveyor](https://ci.appveyor.com/project/mikke89/rmlui/history), see artifacts therein.

**Comment by liupan1890** [comment]
Thank you very much for your reply

My computer uses

NVIDIA GeForce GTX 1050

Intel (R) core (TM) i5-8300h CPU @ 2.30ghz (four cores and eight threads)




As shown in the screenshot,

When running **bitmapfont.exe** It's just a very simple static text display (with scroll bar), without any complex operation or any complex graphic transformation.



Cpu25% means that a thread is 100% occupied, such as infinite message loop, dead loop, or infinite refresh. Only in this case can the thread be 100% occupied, which shows that the CPU single core is full, that is, cpu25%



When running **animation.exe** There are multiple complex animations running (no scroll bar), but only CPU2%




Sample programs are very simple to show the application, no complex code logic.



#### Simple text static display 2%, complex animation run 25%



I don't think it can be simply classified as this is a GPU driver quirk

So I doubt whether there is a dead loop in the code part of the scroll bar control




I'm not demanding to hope how good the performance of the library is, but I'm shocked by the simple static text display of cpu25%, which is obviously abnormal. It's not necessary for users to control of the rendering loop, and you also need to check whether there are bugs

**Comment by liupan1890** [comment]
As a test,I try to modify RmlUi-win64-samples-only\basic\bitmapfont\data\bitmapfont.rml 

### 1. after modify  CPU 1.2%
``````
<body template="window">
	<p>This is a bitmap font sample!</p>
	<p>Lorem ipsum dolor sit amet</p>
	<p>Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. </p>
</body>
``````
![屏幕截图 nos](https://user-images.githubusercontent.com/67817756/112926181-a744b180-9145-11eb-9916-97f428defd5c.png)


### 2.Restore to original content CPU 27%
``````
<body template="window">
	<p>This is a bitmap font sample!</p>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna neque viverra justo nec ultrices dui sapien eget mi. Risus quis varius quam quisque id. Amet est placerat in egestas erat imperdiet. Velit egestas dui id ornare arcu odio ut sem. Aliquet porttitor lacus luctus accumsan tortor posuere. Et malesuada fames ac turpis egestas integer eget. Enim nunc faucibus a pellentesque sit amet porttitor eget. Nunc pulvinar sapien et ligula. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Dolor sit amet consectetur adipiscing. Congue eu consequat ac felis donec et odio pellentesque. Nunc non blandit massa enim nec dui nunc mattis.</p>
	<p>Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Quam pellentesque nec nam aliquam sem et. Et tortor consequat id porta nibh venenatis. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Magna ac placerat vestibulum lectus mauris ultrices eros. Amet purus gravida quis blandit turpis cursus. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Pellentesque elit ullamcorper dignissim cras. Nunc eget lorem dolor sed viverra ipsum nunc. Ac felis donec et odio pellentesque diam volutpat commodo.</p>
</body>
``````
![屏幕截图 s](https://user-images.githubusercontent.com/67817756/112926185-a90e7500-9145-11eb-9d1d-6a5c4c66299b.png)


### I think this shows that it's really a bug, not a performance problem

**Comment by barotto** [comment]
> I think this shows that it's really a bug, not a performance problem

I don't know RmlUi's innards, but if it's similar to other libraries, every letter on screen is a draw call, so the more the letters the higher the CPU's load.
If so, this is definitely not a bug but I guess an interesting optimization problem.

**Comment by liupan1890** [comment]
> > I think this shows that it's really a bug, not a performance problem
> 
> I don't know RmlUi's innards, but if it's similar to other libraries, every letter on screen is a draw call, so the more the letters the higher the CPU's load.
> If so, this is definitely not a bug but I guess an interesting optimization problem.

while i look at the source code
master/Samples/basic/bitmapfont/src/main.cpp :137
``````
Shell::EventLoop(GameLoop);
``````
``````
void GameLoop()
{
	context->Update();

	shell_renderer->PrepareRenderBuffer();
	context->Render();
	shell_renderer->PresentRenderBuffer();
}
``````


Then I understood why the CPU 25% ,Because of the Sample in loop rendering
It's not a bug , i will close this issue

**Comment by skorver** [comment]
Hi 1890， I am a member in Aliyunpan Team, We are highly interested in your process of white sheep version 
it inspires our dev team~ we d love to support developers 
Shall we have a further talk? my wechat ID：korver24

**Comment by skorver** [comment]
> > > I think this shows that it's really a bug, not a performance problem
> > 
> > 
> > I don't know RmlUi's innards, but if it's similar to other libraries, every letter on screen is a draw call, so the more the letters the higher the CPU's load.
> > If so, this is definitely not a bug but I guess an interesting optimization problem.
> 
> while i look at the source code
> master/Samples/basic/bitmapfont/src/main.cpp :137
> 
> ```
> Shell::EventLoop(GameLoop);
> ```
> 
> ```
> void GameLoop()
> {
> 	context->Update();
> 
> 	shell_renderer->PrepareRenderBuffer();
> 	context->Render();
> 	shell_renderer->PresentRenderBuffer();
> }
> ```
> 
> Then I understood why the CPU 25% ,Because of the Sample in loop rendering
> It's not a bug , i will close this issue

Hi 1890， I am a member in Aliyunpan Team, We are highly interested in your process of white sheep version
it inspires our dev team~ we d love to support developers
Shall we have a further talk? my wechat ID：korver24
