### ISSUE TITLE
RmlUi on Conan

### ISSUE THREAD

**Issue by ZombieRaccoon** [mikke89/RmlUi#183]
I'd like to start off by saying that I really like the project and the direction it's headed and I'd like to thank you guys for keeping it going. The feature that really got my attention lately was data binding, so I'm excited about the next major version. I'm already using its actual state available from the master branch.

In order to ease integration I created a [Conan](https://conan.io) recipe for RmlUi 3.3 (https://github.com/conan-io/conan-center-index/pull/5122) and as a result the library is now available through Conan's official repository at https://conan.io/center/rmlui. I'm planning on updating the recipe for 4.0 as well, once it's released.

Availability on Conan might be worth mentioning in the readme.

**Comment by mikke89** [comment]
Oh, this is awesome, thank you!

I'll happily add it to the readme. Since I'm not very familiar with Conan, can you perhaps add a small description on how to consume the library through Conan, and from the official repository in particular? Something short and sweet that fits in the readme.

By the way, Zinchenko on our gitter channel has also been working on a conan recipe, you might want to compare notes:
https://gitlab.com/b110011/conan-rmlui

**Comment by ZombieRaccoon** [comment]
In general, once one has Conan properly set up it should be miraculously easy to consume any available package. Since it's in setting up Conan that one might be most likely to require some measure of guidance, my recommendation would be to include a link to Conan's [Getting Started](https://docs.conan.io/en/latest/getting_started.html) guide, along with a quick link to the [package itself](https://conan.io/center/rmlui). If you'd like, I can think of a way to squeeze this into https://github.com/mikke89/RmlUi#integrating-rmlui.

In the recipe you linked the different components (Core, Controls, Debugger etc.) of the library are defined individually. If there's indeed a use-case for such an approach then I'd suggest that Zinchenko contribute some of those elements to [conan-center-index](https://github.com/conan-io/conan-center-index).

**Comment by mikke89** [comment]
I think it's reasonable to expect people to already know Conan if they want to consume it that way, so I added a link to the package as you suggested.

Maybe we could have a longer description in the documentation, eg. after [Building on mac/linux](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/building_with_cmake.html)? If you have some suggestions, I'd appreciate it (or a PR) :)

**Comment by ZombieRaccoon** [comment]
I certainly agree that it could have a place somewhere in the documentation. I took a look around and I think that the "Setting up the build environment" part of [Integrating RmlUi into your application](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/integrating.html) could be more fitting in this case. This is definitely debatable, because Conan actually performs both. What do you think?

For starters, one would be remiss not to include an explanation of the options available - or lack thereof - similar to the one seen in Zinchenko's repository. If we agreed on the context I'd more than happily put something together.

**Comment by mikke89** [comment]
Alright great, I agree the "Integrating RmlUi" might be a more suitable place. In this case I'd also add a section to "Building RmlUi" just mentioning Conan and linking to the description on the next page. And an overview of options would also be nice indeed. Thanks!

**Comment by ZombieRaccoon** [comment]
I think that we're good as far as Conan support and a bit of related documentation goes. If you'd like we can close this issue for now. Just out of pure curiosity, if you don't mind such a question: how far along 4.0 is, do you think?

**Comment by mikke89** [comment]
Yup, looks all good to me, thanks again for the contributions!

No worries, I don't mind at all. It's only a matter of getting 4.0 out the door at this point, keep an eye out for it in the coming week or two, hopefully ;)

**Comment by ZombieRaccoon** [comment]
I'm glad to have contributed. I'll make sure to check back regularly. Best of luck!
