### ISSUE TITLE
nested opacity not working correctly

### ISSUE THREAD

**Issue by kim8823** [mikke89/RmlUi#185]
Consider the following:
```HTML
<div style="opacity: 0.1">
  <div style="opacity: 1">this should be almost invisible</div>
</div>
```
RmlUi renders the text in the child node with opacity = 1 instead of 0.1 like browsers.

The culprit is in `ElementStyle::ComputeValues`:
```C++
		case PropertyId::Opacity:
			values.opacity = p->Get<float>();
			break;
```
That should be `*=` to properly combine with the parent's value.

Just thought I'd mention it 😉

**Comment by mikke89** [comment]
Hi, I appreciate the comments.

This is mainly a matter of RmlUi differing from the CSS behavior. In fact, getting transparency correct is a bit more tricky, ideally we would render the element with all descendants to texture, and only then render that texture with transparency (or some equivalent behavior). This of course would require a more complex rendering API.

Once we have filtering support it will be possible for clients to implement a better transparency, which would behave more like the CSS opacity. For now, I think we should leave opacity as is, with the limitations it has. Your suggestion might make it closer to what is expected in some cases, but not for all cases, and comes with its own issues.

**Comment by kim8823** [comment]
Yeah you're right, my suggestion still doesn't work with overlapping translucent things. The parent having a background for instance would already break it.

In my case I needed it for an otherwise invisible parent wrapping a few side by side items and it works perfectly for that, even if its a global change in behavior.

Offscreen rendering would be the proper fix but yeah, that'd be a bigger change.

**Comment by mikke89** [comment]
Just to be clear, in RmlUi opacity is inherited. So if I understand your case correctly, if you drop `opacity: 1` from the child elements it might already work as you intend. I might not understand your case exactly though, if you need that multiplicative behavior it is always possible to set them in CSS rules, although it might be a bit inconvenient sometimes.

**Comment by kim8823** [comment]
Exactly, the issue is only there when the child specifies its own `opacity`. Without that it is inherited as expected.

I'm using the parent to `transition: opacity` some buttons invisible (when the mouse stays still for a while), and the buttons themselves already have `opacity` set. Additionally one of the buttons needs a `transition: opacity` between two images on hover. Its probably not possible to do this 100% correctly during the transitions with just CSS rules, but the multiplication change definitely makes it way easier and it doesn't break anything else in this app. On the other hand, its not like these are super long transitions, so no one would notice anyways...

I'm not trying to fight you on this, no need to exchange one quirky behavior for another. Just documenting as it was unexpected.

**Comment by mikke89** [comment]
Ah, yes, I see, when transitions are involved it will probably be more complicated indeed.

I'm glad you brought it up here, as I'm sure it'll be useful for others searching for related issues. All in all, sounds like we agree on basically doing nothing for now then ;)

Keep an eye out for filter support in the future, it's on the todo list.
