### ISSUE TITLE
Missing sprites when using Element::Clone

### ISSUE THREAD

**Issue by Dakror** [mikke89/RmlUi#191]
Since Clone creates a detached copy, Elements like ElementImage fail when looking up sprites that were registered in the stylesheet of the owner document.

Is there another way to currently duplicate an Element inside the same owner document or refresh the image after the fact? If not, it might be worth to add a `clone->SetOwnerDocument(GetOwnerDocument());` inside Element::Clone

**Comment by mikke89** [comment]
Does this only occur during drag cloning?

**Comment by Dakror** [comment]
I was manually calling Element::Clone in my application

**Comment by mikke89** [comment]
Hm, that seemed to work fine when I tested it?

**Comment by Dakror** [comment]
Nope that did not fix it

**Comment by Dakror** [comment]
This is the code I'm using:

```cpp
auto ptr = document->GetElementById("list-selection");
listSelection = document->AppendChild(ptr->Clone());
```

**Comment by mikke89** [comment]
Hm, strange, that is working well for me. Here is the full example:
```cpp
static const String document_img_rml = R"(
<rml>
<head>
	<title>Test</title>
	<link type="text/rcss" href="/assets/rml.rcss"/>
	<link type="text/rcss" href="/assets/invader.rcss"/>
	<style>
		body
		{
			left: 0;
			top: 0;
			right: 0;
			bottom: 0;
		}
	</style>
</head>

<body>
<img sprite="icon-invader"/>
</body>
</rml>
)";


TEST_CASE("Element.clone")
{
	Context* context = TestsShell::GetContext();
	REQUIRE(context);

	ElementDocument* document = context->LoadDocumentFromMemory(document_img_rml);
	REQUIRE(document);
	document->Show();

	context->Update();
	context->Render();

	Element* element = document->GetChild(0);
	REQUIRE(element);
	REQUIRE(element->GetTagName() == "img");

	document->AppendChild(element->Clone());

	TestsShell::RenderLoop();

	document->Close();
	TestsShell::ShutdownShell();
}
```

This renders two images side by side.

**Comment by Dakror** [comment]
does it play a role that the element i require was inside a template included into the document maybe?

**Comment by mikke89** [comment]
I'm not sure why that would be a problem, but it would be something to investigate.

**Comment by mikke89** [comment]
@Dakror Did you ever figure this out?

**Comment by Dakror** [comment]
I actually haven't continued to investigate it, busy with other things.

**Comment by mikke89** [comment]
Closing this for now due to inactivity and inability to reproduce. Please do re-open if further investigations show issues in the library.
