### ISSUE TITLE
Samples - A way to disable

### ISSUE THREAD

**Issue by paulo-coutinho** [mikke89/RmlUi#192]
Hi,

First, thanks for this great work man!

Can you add an option for CMake to disable some samples? Because im trying checking some samples, but it build all samples, that required sdl2, sfml2 etc.

Thanks.

**Comment by Dakror** [comment]
CMake only generates the project files to build the samples, you just need to use the proper commands to only build what youre interested in after that.

**Comment by paulo-coutinho** [comment]
It is not true. When you will generate it requires some libraries installed, like sfml2 and sdl2 and the project files are not generated because this.

```
cmake ../ -DBUILD_SAMPLES=ON
```

**Comment by mikke89** [comment]
Hi, and thank you!

The CMake configuration will only generate SFML and SDL samples if CMake finds their respective libraries. The other samples will still be generated if it cannot find these libraries. If you have problems generating the CMake configuration, could you post the CMake output?
