### ISSUE TITLE
Text field keyboard shortcuts broken on Linux

### ISSUE THREAD

**Issue by nyanpasu64** [mikke89/RmlUi#210]
Running RmlUi master 747d73c0b68fdbf3fca2c206d0842f52373e3e98 built from source, on Linux KWin X11. In the `demo` app's "Forms" tab, I cannot use keyboard shortcuts like Ctrl-C or Ctrl-V in text areas; it instead types "c" or "v". Copying and pasting works on Windows.

Operating System: Arch Linux
KDE Plasma Version: 5.22.3
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.12.15-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 730/PCIe/SSE2

**Comment by mikke89** [comment]
We haven't implemented system clipboard in the Linux and macOS shells, now they only copy and paste internally in the application. This feature should be a good exercise for someone familiar with these platforms.

With that said, filling of the text (c/v) should not occur when typing a shortcut key. Thanks for letting me know, that one should be fixed now.

**Comment by mikke89** [comment]
I think we should open a new issue for the system clipboard feature if this is desired. The main issue here is considered the unintended c/v text pasting and should now be fixed.
