### ISSUE TITLE
Lua GC crash

### ISSUE THREAD

**Issue by nimble0** [mikke89/RmlUi#216]
I've had trouble getting easy reproduction of this but maybe what I've worked out will help:

- [EventDispatcher::DispatchEvent](https://github.com/mikke89/RmlUi/blob/85bbd93a5313e039cfeaee39503da35b1fbd7bec/Source/Core/EventDispatcher.cpp#L168) creates an event (with C++ new).
- The event gets sent to Lua with [LuaType<T>::push](https://github.com/mikke89/RmlUi/blob/85bbd93a5313e039cfeaee39503da35b1fbd7bec/Source/Lua/LuaEventListener.cpp#L130), marked not to delete when GCed.
- The event is deleted on the C++ side.
- A new object which is deleted when GCed (e.g. ElementStyleProxy) is created at the same address as the event.
- The new object gets sent to Lua with [LuaType<T>::push](https://github.com/mikke89/RmlUi/blob/85bbd93a5313e039cfeaee39503da35b1fbd7bec/Source/Lua/Element.cpp#L497), marked to delete when GCed, overwriting the original mark not to delete when GCed.
- The new object gets GCed calling [LuaType<T>::gc_T, which deletes the object in C++](https://github.com/mikke89/RmlUi/blob/85bbd93a5313e039cfeaee39503da35b1fbd7bec/Include/RmlUi/Lua/LuaType.inl#L178).
- The event gets GCed calling LuaType<T>::gc_T, which deletes the same address in C++ causing a segfault.

**Comment by mikke89** [comment]
So if I understand correctly, everything sounds fine here until the last point. The bug is that the event gets garbage collected even though the argument is false on push? And this only happens if by pure random chance shares address with another later created and GCed object?

**Comment by nimble0** [comment]
Yes, that's correct. Although I might be more inclined to attribute the problem to Lua holding references to deleted objects. I imagine there might be some strange behaviour if an event object reference was kept and later accessed (in Lua) as well.

**Comment by mikke89** [comment]
So I had another look at this. I'm no Lua wizard, but I wonder if we can solve this simply by setting the lua table value to `1` (= do not call delete) after the line where the object is [garbage collected and deleted](https://github.com/mikke89/RmlUi/blob/85bbd93a5313e039cfeaee39503da35b1fbd7bec/Include/RmlUi/Lua/LuaType.inl#L179)?

Since it's impossible in C++ that two live objects share the same address, the next time garbage collection is called on the same pointer it must already have been destroyed in C++. However, one assumption here is that Lua calls `gc_T` in reverse order of construction.  Do you know whether this is true? Eg. in you example it would mean that `gc_T("new object")` is always called before `gc_T(event)`.

Can you test the commit with the proposed fix? I can't really reproduce the issue, so I will need some help to determine if this really works at all. If you know Lua well, I would appreciate any feedback on my code as well, thanks!

**Comment by nimble0** [comment]
The stack index in that commit should be -3 instead of -2.

> However, one assumption here is that Lua calls gc_T in reverse order of construction. Do you know whether this is true?

I think that is the case. "... the finalizers for objects are called in the reverse order that they were marked for collection, among those collected in that cycle ..." (https://www.lua.org/manual/5.2/manual.html#2.5.1)

However, this would still leave references to freed memory hanging around in Lua. I think bugs relating directly to this might be easier to reproduce, I tried holding onto an Event in Lua and crashed immediately in a quick test.

**Comment by mikke89** [comment]
Thanks, I changed the stack index now.

> However, this would still leave references to freed memory hanging around in Lua. I think bugs relating directly to this might be easier to reproduce, I tried holding onto an Event in Lua and crashed immediately in a quick test.

I'd consider that a related, but separate issue. To me it doesn't really make sense to hold onto events, what kind of use cases are we talking about here?

**Comment by nimble0** [comment]
It's not use cases I'm thinking of. I think Lua should be sandboxed for safety and security.

**Comment by mikke89** [comment]
The library is pretty much built with the presumption of using known and trusted sources. Other cases have never been the goal and it would take a monumental effort to harden the library for such use cases at this point.

**Comment by nimble0** [comment]
I thought that was the case but I still think it's preferable to try and eliminate vulnerabilities when discovered even if there's no coordinated effort to try to remove all of them. And the safety aspect does apply even when the data is trusted, it's not expected to encounter memory bugs when using a garbage collected language.

**Comment by mikke89** [comment]
Yeah, that is fair and I generally agree. I'm not the most experienced with Lua but I will certainly review and accept pull requests if you or anyone else have ideas to solve such issues. Meanwhile, I consider the original issue fixed now.
