### ISSUE TITLE
WOFF fonts cause double free on exit

### ISSUE THREAD

**Issue by nimble0** [mikke89/RmlUi#217]
Reproducing:
- Add a WOFF font, such as [Xolonium](https://fontlibrary.org/en/font/xolonium), to Samples/assets
- Add `{ "Xolonium-Regular.woff",    false },` to the font faces list in [Shell.cpp](https://github.com/mikke89/RmlUi/blob/04533bea4e8482213d2f8a280263a4c71a9d34fe/Samples/shell/src/Shell.cpp#L51)
- Launch and close any sample

Looks like [FreeType::ReleaseFace](https://github.com/mikke89/RmlUi/blob/04533bea4e8482213d2f8a280263a4c71a9d34fe/Source/Core/FontEngineDefault/FreeTypeInterface.cpp#L102) expects FT_Face->stream->base to hold a pointer to the data pointer that was passed in but in the case of WOFF fonts it doesn't.

**Comment by mikke89** [comment]
Thank you for reporting this! The `FT_Face->stream->base` pointer must certainly have been a hack, I've restructured a bit and it should be fixed now, much safer. Let me know if there are any issues.
