### ISSUE TITLE
position:absolute doesn't work for tables

### ISSUE THREAD

**Issue by barotto** [mikke89/RmlUi#221]
Opening this issue following a discussion on gitter.

When an element with `display:table;` also has `position:absolute;` then any children element with table-related `display` values like `table-row` or `table-cell` inside of it will generate the following error:
```
Element has a display type 'table-row', but is not located in a table. It will not be formatted.
```
I don't have much experience with the source code, but this problem appears to happen because when a table has absolute position it's added as such in the `block_context_box` object at [LayoutEngine.cpp:157](https://github.com/mikke89/RmlUi/blob/36fd9d784b2e537ed12dda2394f550056c28bd89/Source/Core/LayoutEngine.cpp#L157)  but the [`LayoutTable::FormatTable()`](https://github.com/mikke89/RmlUi/blob/36fd9d784b2e537ed12dda2394f550056c28bd89/Source/Core/LayoutTable.cpp#L40)  function won't be called in the `CloseAbsoluteElements()` called at [LayoutEngine.cpp:94](https://github.com/mikke89/RmlUi/blob/36fd9d784b2e537ed12dda2394f550056c28bd89/Source/Core/LayoutEngine.cpp#L94)

As a workaround you can put a table inside a `div` element set with `position:absolute;`

**Comment by mikke89** [comment]
Thanks! I figured this also happens with floated tables.

You're on the right track there. I managed to hack some solution together, but really it needs some more structural changes to handle this properly. And I don't think it's worth spending too much time on that right now.  Instead, I figured the best course of action is to warn and provide the suggested workaround to the user.

**Comment by mikke89** [comment]
I'm closing this for now with the improved warnings and workarounds. I suspect this might be an issue with flexboxes as well when they are ready, so we might want to revisit this issue then for a proper fix.
