### ISSUE TITLE
what is the size of hello world program

### ISSUE THREAD

**Issue by kalbhairab** [mikke89/RmlUi#225]

**Comment by mikke89** [comment]
The core dll is a bit less than 1.5 MB, so that should give you an idea (MSVC x64 release).

**Comment by kalbhairab** [comment]
can it be compiled with mingw compiler

**Comment by mikke89** [comment]
Yes it can, we have mingw in our CI.

**Comment by kalbhairab** [comment]
sir i will be grateful if you provide link to tutorial

**Comment by mikke89** [comment]
The documentation should have everything you need to get started: https://mikke89.github.io/RmlUiDoc/
