### ISSUE TITLE
Scrolling sometimes breaks table formatting

### ISSUE THREAD

**Issue by nimble0** [mikke89/RmlUi#230]
This is what it looks like:
![rmlui-scroll-bug](https://user-images.githubusercontent.com/9959776/130637202-56d2255f-75fc-4700-bb29-0ea5989a1db7.gif)

Reproducing:
- Open demo sample
- Go to sandbox tab
- Paste this in rml box:
```
<table>
	<tr>
		<td />
		<td />
		<td />
	</tr>
	<tr>
		<td />
		<td />
		<td />
	</tr>
	<tr>
		<td />
		<td />
		<td />
	</tr>
	<tr>
		<td />
		<td />
		<td />
	</tr>
</table>
```
- Paste this in rcss box:
```
table
{
	width: 100%;
	gap: 10px;
}

tr
{
	height: 200px;
}

td
{
	background-color: #00f;
}
```
- Scroll until formatting breaks.

I have a suspicion this is due to multiple ProcessMouseMove calls per Update call. I haven't seen it happen after I limited it to one ProcessMouseMove call per Update call. This is very much just a guess though, I haven't looked at what's actually happening in the code!

**Comment by mikke89** [comment]
I've tried a whole lot now and I still haven't been able to recreate this issue on my side.

Maybe, could I suggest that we try to record all the input and commands to RmlUi? This way I can replay the commands on my end. Then I should be able to see whatever you're seeing.

We should probably log all the calls to `ProcessMouse...()` (with mouse positions and buttons), as well as `Update` and `Render`. Are you willing to try this, I can create a patch if you'd like?

**Comment by nimble0** [comment]
Sure, I'd be happy to record it if there was a patch to do so. Would be useful for debugging other issues as well.

One detail that I missed: the scrolling has to be using the scrollbar, not the mouse wheel.

**Comment by barotto** [comment]
> One detail that I missed: the scrolling has to be using the scrollbar, not the mouse wheel.

When the pointer is inside the `sandbox_target` area I can reproduce with the mouse wheel as well, albeit not as easily.
If you look closely you can see lines moving with some jerkiness even when scrolling slowly.

**Comment by mikke89** [comment]
Great, I'll consider it fixed then! Thanks for reporting and both of you for testing :)

I'll leave a patch here for the command logger and replay mode, in case it might prove useful in the future:
https://gist.github.com/mikke89/5a302e35a958674d00f3940d08947a23
