### ISSUE TITLE
Incompatible with latest LunaSVG

### ISSUE THREAD

**Issue by Ravbug** [mikke89/RmlUi#232]
LunaSVG [recently made a breaking change](https://github.com/sammycage/lunasvg/releases/tag/v2.3.0) that renames `document.h` to `lunasvg.h`, so the RmlUi SVG plugin does not compile with it.

The issue can be fixed by changing `#include <document.h>` to `#include <lunasvg.h>` in `ElementSVG.cpp`.

**Comment by mikke89** [comment]
Thanks for reporting, let me know if there are any more issues!
