### ISSUE TITLE
Databinding for collections not working in my engine

### ISSUE THREAD

**Issue by DerickThePoney** [mikke89/RmlUi#241]
Hi there, 

I have integrated RMLUI in my engine, and it looks like i'm unable to have databinding work on custom structs and collections (aka std::vector...). Here is what I have: I have a list of resources with associated quantity and I want to display them dynamically in a window.

So basically in the .h private part of the class controlling the window I have the following:
```cpp
    struct Resource
    {
        GameResource::Type Res = GameResource::LENGTH;
        Rml::String ResourceName;
        int Quantity = 0;
    };
    
    struct Data
    {
        std::map<GameResource::Type, u32> FResourceToIndex;
        std::vector<Resource> FResourceView; //<-- I want to show this dynamically
    };
    
    Data data;
```

In the cpp, I have the following:
```cpp
   Rml::DataModelConstructor ctr2 = RmlUiManager::Instance().CreateDataModel("resourcesModel");

    // Registration of the Resource struct
    if (auto handle = ctr2.RegisterStruct<Resource>())
    {
        // registration of the members i need
        handle.RegisterMember("name", &Resource::ResourceName);
        handle.RegisterMember("quantity", &Resource::Quantity);
    }

    ctr2.RegisterArray<decltype(data.FResourceView)>();

    ctr2.Bind("resources", &data.FResourceView);

    FDataModelWrapper = RmlDataModelWrapperFactory::CreateDataModelWrapper(ctr2.GetModelHandle()); <-- this is a dummy wrapper. Don't worry abt this

    // Document loading
    FDocument = RmlUiManager::Instance().LoadDocument("UI\\ResourcesPanel\\ResourcesPanel.rml");
    FDocument->GetElementById("title")->SetInnerRML(FDocument->GetTitle());
```

And finally in the Rml I use this like so:
```
<body template="window" data-model="resourcesModel">
    <div data-for="resource : resources">
        <p class="resource">{{ resource.name }}: {{ resource.quantity }}</p>
    </div>
</body>
```

To me it seems that I haven't done anything wrong... 
But here is what I get in the end...
![2021-10-03_15h13_42](https://user-images.githubusercontent.com/7872231/135755203-40f8ce4b-771e-4f2d-9a50-f9bd3404ede7.png)

It looks like the model creation did not work... Does anyone have any idea what I did wrong? This is not the only model I have, it's just the first one that behaves like this...

Thanks in advance,
Best regards!

**Comment by mikke89** [comment]
Hi!

There [is a limitation](https://mikke89.github.io/RmlUiDoc/pages/data_bindings.html) that you should be aware of:

*Putting the `data-model` attribute on the `<body>` tag may cause issues when combined with templates.*

I suggest that you try to add a wrapper div around your `data-for` element and move the `data-model` attribute to that one. Let me know how it goes :)

**Comment by DerickThePoney** [comment]
Like a charm. The answer was right in front of my eyes...

Thanks a lot :)

**Comment by mikke89** [comment]
Great! No problem, I'm glad it's working now. I'll see if we can fix that limitation at some point or at least warn about it.
