### ISSUE TITLE
Sample program to render to offscreen image buffer

### ISSUE THREAD

**Issue by zcream** [mikke89/RmlUi#242]
The main.cpp examples all seem to render to a window. Is there an example where the user can supply an image buffer that can be rendered to? This is all offscreen and the data will be displayed separately.

**Comment by mikke89** [comment]
Hi.

All the rendering commands from RmlUi are passed to the user, so this is trivial to do in most graphics API. Eg. in OpenGL you would just bind your framebuffer with `glBindFramebuffer` before drawing the commands from RmlUi.
