### ISSUE TITLE
Enumeration conflicts with Windows header files

### ISSUE THREAD

**Issue by xoxoooooo** [mikke89/RmlUi#258]
Source File ==> Source\Core\PropertyParserAnimation.cpp

enum Type { NONE, TWEEN, ALL, ALTERNATE, INFINITE, PAUSED } type;

ALTERNATE, INFINITE ==> These two values conflict with the windows header

This is my solution:

#ifdef ALTERNATE
#undef ALTERNATE
#endif
#ifdef INFINITE
#undef INFINITE
#endif

If you are sure that this is a problem, you can add it to your source code.

English is not good, from machine translation, I wish you a happy life.

**Comment by mikke89** [comment]
Hi. Thanks for reporting.

These enum declarations are in a private source file, what I don't understand is how your windows headers are finding their way into this source file? Things are bound to go wrong when including the windows header into all source files like that.

With that said, I'm all okay with changing these enum names, I'll go ahead and do that.

**Comment by xoxoooooo** [comment]
The reason I think is because my project depends on 'libressl' and I integrated this library into my build space. The header file include path of the library'libressl' has replaced some standard header files, and the replaced files include "Windows.h", which caused this error.
Thank you for your time and greetings.

**Comment by mikke89** [comment]
Alright, I hope the last commit solved the issue for you, cheers.
