### ISSUE TITLE
Modernize OpenGL in samples

### ISSUE THREAD

**Issue by EhWhoAmI** [mikke89/RmlUi#261]
The sample OpenGL renderer uses `glPushMatrix()` and `glPopMatrix`, which is deprecated since OpenGL 3.0 I believe. Are there any plans to modernize it to OpenGL 3.1 or beyond?

**Comment by mikke89** [comment]
Yeah, this has been discussed for a long time. We just need somebody to actually put in the time to do this work. See also #129 and https://github.com/mikke89/RmlUi/issues/239#issuecomment-971663028. Any help is appreciated! :)

Currently I'd recommend users to create their own renderer for whichever backends they are using. There are some open source examples around, see eg. #186.

**Comment by mikke89** [comment]
Closing this as completed, an OpenGL 3 backend is now included with RmlUi 5.0.
