### ISSUE TITLE
Position relative uses old dimensions after resize

### ISSUE THREAD

**Issue by nimble0** [mikke89/RmlUi#262]
Reproducing:

- Open demo sample
- Go to sandbox tab
- Paste this in rml box:
```
<div />
```
- Paste this in rcss box:
```
div
{
width: 100%;
height: 100%;
background-color: red;
position: relative;
left: 100%;
}
```
- It should look like this:
![position-relative-1](https://user-images.githubusercontent.com/9959776/146136086-d427dab0-c2b2-4a74-8bc2-95df0556b8d3.png)
- Make the window full screen. The red box should remain aligned with the right of white boxes, but instead it looks something like this:
![position-relative-2](https://user-images.githubusercontent.com/9959776/146136081-b4efcbb6-f5d1-4e39-990c-b68c891ee4b6.png)

Resizing the window also exhibits the bug but it's less visible.

**Comment by mikke89** [comment]
Thanks for the easy reproducible! I'll look into this.

**Comment by mikke89** [comment]
A fix has been published, let me know if there are any other related issues.
