### ISSUE TITLE
Font engine separation

### ISSUE THREAD

**Issue by jack9267** [mikke89/RmlUi#266]
Just a thought after seeing the define for no default font engine. What if the font engine is a separate lib so if the app wants to static link freetype zlib and libpng it can also use a static lib for the default font engine and use RmlCore as a dll.

**Comment by mikke89** [comment]
This is one of those things that nobody can completely agree on, and really a never-ending debate. Some people want monolibs, others want to split the library into several pieces. I say we pick one approach and don't change it, then at least things are stable.
