### ISSUE TITLE
JavaScript support?

### ISSUE THREAD

**Issue by insraq** [mikke89/RmlUi#268]
Hi, this is just a general question since I've searched the old issues but cannot find relevant discussions. What's the current thinking on providing JavaScript support? I know Lua is easy to write, but providing JavaScript support has several advantages:

- It might potentially open the door to the huge web ecosystem (even if some existing frameworks need modification)
- It will allow developers to take advantage of top tier toolings (IDE, type checker, etc)

There are several embedded JS engines out there. [Duktape](https://duktape.org/) and [QuickJS](https://bellard.org/quickjs/) are designed for embedded environments. Even embedding [v8](https://v8.dev/) is possible as well.

**Comment by aquawicket** [comment]
[DKDom](https://github.com/aquawicket/DigitalKnob/tree/master/DKPlugins/DKDom)
This is something I've been working on for my own libraries. I'm hoping to pull it out into a standalone library of it's own in the future, but you can dig through the current source code to get a basic idea for your own implementation.

**Comment by mikke89** [comment]
There has been some discussion on this topic on [our gitter chat](https://gitter.im/RmlUi/community). I know @uniquejack has made bindings for Duktape previously, so it's certainly possible.

If anyone creates JS bindings, I'd be happy to take a PR. However, I won't actively work on it or maintain it as I'm just not personally interested in that direction.

**Comment by jack9267** [comment]
I think one specific language is a bit odd and perhaps having a generic wrapper that works for any language is better suited.

**Comment by mikke89** [comment]
Closing this as there will not be any official JavaScript support anytime soon. It's certainly possible to add thirdparty support, and I'd be happy to see someone do that.
