### ISSUE TITLE
drag: clone element doesn't respect transform: translate

### ISSUE THREAD

**Issue by martonp96** [mikke89/RmlUi#269]
Hello,

When using `transform: translate(50%,-50%);` to center a div, the cloned element attached to the cursor appears on the wrong place, like the transform was not used on the item at all.

RML for testing: https://pastebin.com/CwtAPrnz

**Comment by mikke89** [comment]
Hi. Thanks again for the easy reproducible.

I've made a fix for this now. Of course, the situation becomes a bit unwieldy if you make more complex transforms with rotations and so on. We don't try to replicate such a complicated chain of transforms on the cloned element, instead, we only move it to the proper initial location. This approach solves the problem in you test.

I also discovered some issues with auto- and percentage-margins which should also be resolved.

**Comment by martonp96** [comment]
@mikke89 thank you for the quick response, i will test them as soon as i have time.

**Comment by mikke89** [comment]
Closing this now, considered fixed unless otherwise notified.
