### ISSUE TITLE
opacity doesn't work on font-effect: outline

### ISSUE THREAD

**Issue by martonp96** [mikke89/RmlUi#270]
Hello,

I know the font-effect doesn't exist in browser, instead we can use font-shadow for outlining, however in browser opacity works on the shadow. 

Some of our users were confused about it, because for example a white text with black outline and with opacity: 0 shows the text as black and they assumed opacity doesn't work.

```
RML:
.text3
{
      color: #FFFFFF;
      opacity: 0;
      font-effect: outline(1px black);
}

HTML:
.text3
{
	color: #FFFFFF;
	opacity: 1;
	text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;
}
```

**Comment by mikke89** [comment]
Thanks, guess I never really tried this. I took a stab at adding it, let me know how it works for you.

**Comment by mikke89** [comment]
Closing this, considered fixed unless otherwise notified.
