### ISSUE TITLE
Set the "real" minimum cmake version in CMakeLists.txt

### ISSUE THREAD

**Issue by jonesmz** [mikke89/RmlUi#277]
The github actions CI is using Ubuntu 20.04, and Mac OS X 11, both of which come pre-installed with
Cmake 3.22.2
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md

But the CMakeLists.txt is set to the minimum version of 

cmake_minimum_required(VERSION 3.1)

I recommend determining what the oldest platform you think you want to support is, and picking the CMake version from that platform.

**Comment by mikke89** [comment]
Thanks, this is probably a good idea indeed. However I will defer this to #198 and let it be a part of that work.
