### ISSUE TITLE
SDL2 Example and Window Resizing

### ISSUE THREAD

**Issue by dougreichard** [mikke89/RmlUi#288]
I was trying to get the SDL2 example working and it was fine except for resizing the windows the RMLUI was clipped.  After a lot of googling and head scratching that ended with no help.  I tried to set the mRender_w and mRender_h values in the SetScissorRegion function. This worked for me, however I don't know if this was the proper place to fix this.

``` C++
void RmlUiSDL2Renderer::SetScissorRegion(int x, int y, int width, int height)
{
    int w_width, w_height;
    SDL_GetWindowSize(mScreen, &w_width, &w_height);
   // My change
    mRenderer_w = w_width;
    mRenderer_h = w_height;
   // end of my change
    mRectScisor.x = x;
    mRectScisor.y = w_height - (y + height);
    mRectScisor.w = width;
    mRectScisor.h = height;
}
```

**Comment by aquawicket** [comment]
You should detect the size change in your SDL events loop and set the rml context size. The render interface will detect it.  Something like 

```
SDL_RenderClear(mSdlRenderer);

//adjust the Context if the window is resized
SDL_GetWindowSize(mSdlWindow, &mWidth, &mHeight);
if (mWidth != mRmlContext->GetDimensions().x || mHeight != mRmlContext->GetDimensions().y)
{
    mRmlContext->SetDimensions(Rml::Vector2i(mWidth, mHeight));
}

mRmlContext->Render();
```

And your SetScissorRegion should actually look like this.  Don't flip the y axis.
That was probably a (copy + paste) mistake from the original coder. 

```
// Called by RmlUi when it wants to change the scissor region.		
void RenderInterface::SetScissorRegion(int x, int y, int width, int height)
{
    mRectScisor.x = x;
    mRectScisor.y = y;
    mRectScisor.w = width;
    mRectScisor.h = height;
}
```

I'm been upgrading the RmlUi SDLRenderer a bit, just havn't created a PR yet.  have a look.
[aquawicket/SDL2RendererRml](https://github.com/aquawicket/SDL2RendererRml)

**Comment by dougreichard** [comment]
I modified my copy to use your, SetScissorRegion and everything works. I also borrowed parts of your  RenderGeometry and to get rid of the SDL_RenderSetViewport which was also part of the problem. I was calling SetDimensions with an event filter but I like your detection better than mine too. Thanks. Looks like there is some interesting enhancements coming by the looks of the rest of your code.
