### ISSUE TITLE
Can we use raw text for Element::InnerRML?

### ISSUE THREAD

**Issue by xxshady** [mikke89/RmlUi#294]
For example if we set inner RML to "example" with `Element::SetInnerRML`, `Element::GetInnerRML` will return an empty string, is it possible this is a bug?

**Comment by xxshady** [comment]
and also, I can't say for sure that I get this result directly from rmlui, but alt:V developer [says](altmp/altv-issues#1427) that this behavior is more likely to be related to rmlui itself

**Comment by mikke89** [comment]
Hi.

Thanks for the report, this is supposed to work as you expect. And indeed, everything seems to be working fine on the RmlUi end. Here are the [unit tests](https://github.com/mikke89/RmlUi/blob/master/Tests/Source/UnitTests/Element.cpp) I tested with:

```cpp
	SUBCASE("SetInnerRML1")
	{
		ElementPtr element = document->CreateElement("div");
		CHECK(element->GetInnerRML() == "");
		element->SetInnerRML("text");
		CHECK(element->GetInnerRML() == "text");
	}

	SUBCASE("SetInnerRML2")
	{
		Element* element = document->GetFirstChild();
		CHECK(element->GetInnerRML() == "This is a <span>sample</span>.");
		element->SetInnerRML("text");
		CHECK(element->GetInnerRML() == "text");
	}
```

Which succeeds:

```
[doctest] doctest version is "2.4.6"
[doctest] run with "--help" for options
===============================================================================
[doctest] test cases:   30 |   30 passed | 0 failed | 0 skipped
[doctest] assertions: 2762 | 2762 passed | 0 failed |
[doctest] Status: SUCCESS!
```

**Comment by xxshady** [comment]
Thanks for your quick response,  i will close issue then
