### ISSUE TITLE
Add a Luau plugin

### ISSUE THREAD

**Issue by mundusnine** [mikke89/RmlUi#295]
Since [luau](https://luau-lang.org/) offers :
- Sandboxing
- Is made to be fast(i.e. because it's used in games)
- Can be strictly or loosely typed

It could be valuable to add a luau plugin.

**Comment by mikke89** [comment]
Thanks for the suggestion. Certainly looks like an interesting project. Additional language bindings are better implemented by thirdparty support, and won't be worked on officially. If anyone wants to take on this task I'll be happy to assist with any questions on the library side.
