### ISSUE TITLE
Odd SVG rendering?

### ISSUE THREAD

**Issue by g40** [mikke89/RmlUi#300]
Hello, and thanks for a very interesting project.

Windows 10, Vs 2022, all code including LunaSVG built from source (master). Invaders works a treat.

Trying out the SVG example results in some odd coloration. Using the svg => png test in LunaSVG results in this rendering of Tiger:

![tiger svg](https://user-images.githubusercontent.com/812250/163062380-e51dd976-195a-4b8c-92ca-126f611f4430.png)
 
Running the SVG example results in this faux coloring:

![image](https://user-images.githubusercontent.com/812250/163062559-8739c44f-d629-4641-875f-60b137ed6a56.png)

**Comment by mikke89** [comment]
Hi, and thanks for reporting. Looks like they changed the bitmap format recently: https://github.com/sammycage/lunasvg/commit/0d3e6a2897a76c907becbe48c1726685531ab455.

Until they release a new version at least, I think we should better let things be for compatibility. Unfortunately, there doesn't seem to be a simple compile-time switch we could use to handle both versions simultaneously.

So for now, I suggest to use the supported version of LunaSVG, and we'll revisit this in the future.

**Comment by g40** [comment]
Thanks. Have sorted something pro tem. Closing.
