### ISSUE TITLE
Just a thought ...

### ISSUE THREAD

**Issue by g40** [mikke89/RmlUi#301]
is there a way to add the various HTML/CSS/asset files to the cmake script(s) such that they appear in VS/XCode projects? It makes browsing and the like a lot faster.

**Comment by mikke89** [comment]
I appreciate the suggestion, but I'm not sure how much sense it makes to add asset files like that to the projects, or even how well CMake supports that. What works well for me is just using a tool like Everything, then any asset is just some quick typing away.
