### ISSUE TITLE
[Documentation] Lua version

### ISSUE THREAD

**Issue by LoneBoco** [mikke89/RmlUi#302]
The documentation shown [here](https://mikke89.github.io/RmlUiDoc/pages/lua_manual/getting_started.html) says that Lua 5.x is supported.  This turns out to be incorrect as you use functions that were only added in Lua 5.2.  I forked RmlUi and added some functions from the [compat-5.2](https://github.com/keplerproject/lua-compat-5.2) library so it would work on Lua 5.1 (and therefore LuaJIT), but I'm not entirely sure what ramifications it would have yet (I'm still early on in my implementation).

I would suggest either changing the documentation or adding and testing the compat functions.
My changes: f785414de86d8c1ac19f708d329301f9fc8a2ca0

**Comment by mikke89** [comment]
Hi.
It would be nice if we could make it work with 5.1. I see that there exists a compatibility layer already for 5.2 just below your changes. Could you perhaps put the changes you made behind a version macro next to the existing compatibility layer, and then submit this as a PR? That would be greatly appreciated, thanks!

**Comment by mikke89** [comment]
I see, hopefully it doesn't require too many changes. Let us know how it goes.

**Comment by LoneBoco** [comment]
@mikke89 Unfortunately, I think there is just way too behind the scenes differences between Lua 5.1 and 5.2+ and I was unable to get it working.  My best guess is that it is due to changes in metatable functionality.  I would recommend that you update the documentation instead and mention you need Lua 5.2+.

In related news, I made an RmlUi plugin that binds everything via the [sol3 project](https://github.com/ThePhD/sol2).  You can find it here:
https://github.com/LoneBoco/RmlSolLua

By leveraging sol3, I was able to support LuaJIT.  I almost have the whole RmlUi Lua API covered.  All I'm missing right now is the data binding functionality.  It's a work in progress and I haven't tested everything yet, but what I have tested works great.

**Comment by mikke89** [comment]
Hey, that's really awesome! Good job.

I have updated the [documentation](https://mikke89.github.io/RmlUiDoc/pages/lua_manual/getting_started.html) now to mention Lua 5.2+, and also added a link to your plugin. I'll also add a link to it in the thirdparty resources.

I took a brief look at your repository, and it looks really clean and well written. Well done!
