### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by paulocoutinhox** [mikke89/RmlUi#309]
Hi,

Im trying compile for Android, but get this error:

```
In file included from /Users/paulo/Developer/workspaces/cpp/nativium-rmlui/nativium/modules/game/implementation/cpp/nativium/game/ApplicationCoreImpl.cpp:10:
In file included from /Users/paulo/Developer/workspaces/cpp/nativium-rmlui/nativium/modules/game/implementation/cpp/shell/include/ShellRenderInterfaceOpenGL.h:33:
/Users/paulo/Developer/workspaces/cpp/nativium-rmlui/nativium/modules/game/implementation/cpp/shell/include/ShellOpenGL.h:44:10: fatal error: 'GL/glx.h' file not found
#include <GL/glx.h>
         ^~~~~~~~~~
```

Can you add support for it?

Thanks for the great project.

**Comment by mikke89** [comment]
Hi, yeah, it shouldn't be too much trouble to add an Android backend. There are plenty of people already using the library on Android, but it would be nice to have support for the included samples.

It would be great with a contribution, maybe you could add support for this @paulocoutinhox?

In any case it would make sense to add it as a new backend in the `backends` branch targeting RmlUi 5.0, see #307 and the [existing backends](https://github.com/mikke89/RmlUi/tree/backends/Backends).

**Comment by paulocoutinhox** [comment]
Hi,

Im trying make a sample for all platforms (including android), but the error is about opengl dependency:

```
In file included from /Users/paulo/Developer/workspaces/cpp/nativium-rmlui/nativium/modules/game/implementation/cpp/nativium/game/ApplicationCoreImpl.cpp:10:
In file included from /Users/paulo/Developer/workspaces/cpp/nativium-rmlui/nativium/modules/game/implementation/cpp/shell/include/ShellRenderInterfaceOpenGL.h:33:
/Users/paulo/Developer/workspaces/cpp/nativium-rmlui/nativium/modules/game/implementation/cpp/shell/include/ShellOpenGL.h:44:10: fatal error: 'GL/glx.h' file not found
#include <GL/glx.h>
         ^~~~~~~~~~
```

**Comment by paulocoutinhox** [comment]
The most problem is with SHELL.

I think that Shell need be compatible with GLES/Vulkan/Metal/Etc.

**Comment by hero2002** [comment]
I was able to use Rml on android using raylib and some custom backend for the rendering and it was easy enough

**Comment by mikke89** [comment]
In the time since this issues was reported, we have completely reworked our CMake implementation, and other changes making the initial post not fully relevant anymore. We also have reports of it working fine on Android. Thus, I am closing this one. Any related issues on the newest version of RmlUi should be posted in new issues.
