### ISSUE TITLE
Rml::Debugger::Shutdown crashes RmlUi

### ISSUE THREAD

**Issue by LoneBoco** [mikke89/RmlUi#322]
I've been trying to figure out the best way to use the debugger and while experimenting I discovered that `Rml::Debugger::Shutdown()` always ends up resulting in a crash.

What happens is that `Shutdown()` cleans up everything and deletes the `DebuggerPlugin`.  This ends up being a problem as all those debugger elements end up getting thrown into `Context::unloaded_documents`.  When `Context::ReleaseUnloadedDocuments()` rolls around, it tries to clean up all the event listeners.  `DebuggerPlugin::LoadMenuElement()` had added event listeners and bound them to `this`, which is the `DebuggerPlugin`, as the handler.  Except `Shutdown()` deleted the `DebuggerPlugin`.  So `documents[i]->GetEventDispatcher()->DetachAllEvents();` inside `Context::ReleaseUnloadedDocuments()` tries to grab the event dispatcher, which was deleted, and call a function on it.  This results in a crash.  Whoops.

**Comment by LoneBoco** [comment]
`Shutdown()` should also end up calling `DebuggerPlugin::SetContext(nullptr)` so we remove the "click" and "mouseover" event listeners.  Those also end up causing a crash.

**Comment by mikke89** [comment]
You're right, looks like this is crashing indeed, thanks for making the issue. Manually shutting down the debugger isn't usually necessary, this was added mainly to support re-initialization on another host context. But obviously it shouldn't crash like this so we need to get it fixed.

Looks like you have a good grasp on it already, would you like to make a pull request?

**Comment by LoneBoco** [comment]
@mikke89 I found some time to fix this up today.  I submitted the PR.
