### ISSUE TITLE
Registering a struct twice causes an error in debug

### ISSUE THREAD

**Issue by DerickThePoney** [mikke89/RmlUi#326]
Hi there,

First of all, thanks for the library, it's awsome and it integrated nicely in my hobby engine ! 

That being said, I have a small issue that one of you might be able to help me with. The issue is only apparent when using the Debug library. First of all, I use the static library, not the dynamic one, and I use /MTd in debug and /MT in release. 

So here is the problem. I have a struct that I use to store specific data for views that I want to use in several views. Therefore in one cpp file I do the folowing:

```cpp
void ResourcePanelController::VirtualInit()
{
    UIController::VirtualInit();

    // creates a Rml::DataModelConstructor 
    Rml::DataModelConstructor ctr2 = RmlUiManager::Instance().CreateDataModel("resourcesModel");

    // register the struct UIResourceView that's in its own header file
    if (auto handle = ctr2.RegisterStruct<UIResourceView>())
    {
        handle.RegisterMember("name", &UIResourceView::ResourceName);
        handle.RegisterMember("quantity", &UIResourceView::Quantity);
    }

    // register an array of UIResourceView
    ctr2.RegisterArray<std::vector<UIResourceView>>();

    ctr2.Bind("resources", &FResourceView);

    // wrapper around the model
    FDataModelWrapper = RmlDataModelWrapperFactory::CreateDataModelWrapper(ctr2.GetModelHandle());

    // Load the document
    FDocument = RmlUiManager::Instance().LoadDocument("UI\\ResourcesPanel\\ResourcesPanel.rml");
    AssertRelease(FDocument != nullptr);
    FDocument->GetElementById("title")->SetInnerRML(FDocument->GetTitle());

   // Fine and dandy !
}
```

and in another cpp file, called AFTER the previous snippet, I do the exact same thing more or less (the data model is a bit different):
```cpp
void BuildingSelectionPanelController::VirtualInit()
{
    UIController::VirtualInit();

    Rml::DataModelConstructor ctr2 = RmlUiManager::Instance().CreateDataModel("buildingResourcesModel");

    // register the struct --> Error: struct already defined
    if (auto handle = ctr2.RegisterStruct<UIResourceView>())
    {
        handle.RegisterMember("name", &UIResourceView::ResourceName);
        handle.RegisterMember("quantity", &UIResourceView::Quantity);
    }
    ctr2.RegisterArray<std::vector<UIResourceView>>();
    if (auto handle = ctr2.RegisterStruct<BuildingSelectionPanelDataView>())
    {
        handle.RegisterMember("has_resources", &BuildingSelectionPanelDataView::HasResources);
        handle.RegisterMember("has_recipe", &BuildingSelectionPanelDataView::HasRecipe);
        handle.RegisterMember("produces_energy", &BuildingSelectionPanelDataView::ProducesEnergy);
        handle.RegisterMember("energy_produced", &BuildingSelectionPanelDataView::EnergyProduced);
        handle.RegisterMember("resources", &BuildingSelectionPanelDataView::FResourcesInCurrentBuilding);
    }

    ctr2.Bind("buildingResourcesModel", &FDataView);

    FDataModelWrapper = RmlDataModelWrapperFactory::CreateDataModelWrapper(ctr2.GetModelHandle());

    FDocument = RmlUiManager::Instance().LoadDocument("UI\\BuildingSelectionPanel\\BuildingSelectionPanel.rml");
    AssertRelease(FDocument != nullptr);
    FDocument->GetElementById("title")->SetInnerRML(FDocument->GetTitle());
}
```

Doing this in debug, I get the error box telling me the struct `UIResourceView` has already been registered, which I understand, even though it's quite anoying to have the popup. Everything works correctly after that if I just ignore the issue. Note that I also register the array twice, and I don't get the error on the array. 

I tried to circumvent the error by not registering the struct the second time around, but this time, nothing works and I get an error when registering the array telling me the struct `UIResourceView` was not previously defined... I narrowed it down to this bit of code in Traits.h:
```cpp
template<typename T>
class Family : FamilyBase {
public:
	// Get a unique ID for a given type.
	// Note: IDs will be unique across DLL-boundaries even for the same type.
	static FamilyId Id() {
		static int id = GetNewId();  // <-- gives different results if I register the struct a second time
		return static_cast<FamilyId>(id);
	}
};
```
If register the struct a second time, I get the same id for the type. However, if I don't, when registering the array, the id is different, as if it was never called before.
Same thing, if I don't register the array the second time around, it's telling me the array has not been previously defined...

Do you have an idea of why this is working this way ? My guess would be that it is either because they are in different compile units or because I use the static library. Or something completely different 😄 . Both documents are opened using the same context... IMO one should either have to register the types once and for all, or registered the types twice should just return a null handle, not pop an error ?

Thanks in advance for your help !

**Comment by mikke89** [comment]
Thanks for the detailed description, it's well written.

With that said, hmm, this is a weird and quirky one. When putting the data types registration in different translation units it is really up to the linker to de-duplicate the calls to `Family<T>::Id()` so that we get the same ID. Here that seems to go wrong for some reason. 

Are you seeing the full definition of the type from both translation units? I suspect there might be issues if it only sees a forward declaration. There could also be some other compiler/linker settings at play here too. Although I don't think the static runtime library has anything to do with it.

I think the obvious simple solution here is to put them in the same translation unit. For the sake of organization, you could do this while keeping the two files separate, just don't compile these files directly but rather include both of them in a new single translation unit like you would for a unity build. Alternatively you will have to investigate more into how your compiler does these things, I don't think there is anything more we can do on the library side here?

Regarding the error messages you get, you can safely ignore them if you know what you're doing. Sometimes this may be unintentional so we submit the warning to help the user understand what went wrong. The idea is that you register the types once and for all. The warning is in a sense to notify of a breach of this contract. I guess we could reconsider the error messages but I also believe they can be helpful and they do point to a non-ideal situation as the second call has no effect.

**Comment by mikke89** [comment]
Hah, yeah, I can see how that can be hurtful to a programmer's heart. Let us know if you figure something out, I'm sure it might be useful to others as well.

**Comment by DerickThePoney** [comment]
Hi again,

I have found that by instantiating Rml::Family<Type> after the definition of Type in the .h of the type seems to work for the type itself but not for the array:
```cpp
#pragma once

#ifndef RMLUI_STATIC_LIB
#define RMLUI_STATIC_LIB
#endif

#include "RmlUi/Core/Traits.h"

namespace ECSEngine
{
namespace UI
{
struct UIResourceView
{
    GameResource::Type Resource = GameResource::LENGTH;
    std::string ResourceName;
    int Quantity = 0;
};
using UIResourceArray = std::vector<UIResourceView>;
} // namespace UI
} // namespace ECSEngine

template struct Rml::Family<ECSEngine::UI::UIResourceView>;
template struct Rml::Family<ECSEngine::UI::UIResourceArray>;
```

All in all, it seems that it is a translation unit problem... I don't understand why the vector part did not do the trick 🤔 I get two different Id in two different translation units. But it works 😄 Before you ask, instantiating the vector class did not work 😄 

If this trick works for structs shared between ui views, it would be cool. If I have to do it again I'll update you if it does not. 

Cheers !

**Comment by DerickThePoney** [comment]
Hey.

I'll give a test in my specific configuation. My build system is using fastbuild, which basically amounts to "Compile all cpp files with these options", then link all necessary obj files together to put out an exe ^^'. I know I have inline in debug option set for perf, I'll see if it's something like that that's happening...

**Comment by mikke89** [comment]
Hi. Did you figure this one out in the end?

**Comment by DerickThePoney** [comment]
Hi, no sorry i haven't had time to investigate this one further....

Best regards,

Cédric

**Comment by mikke89** [comment]
I understand, no worries. I don't think there is anything we can do on the library side, so I'm closing this one now. If you do find a solution later on then it would be very helpful if you could let us know.
