### ISSUE TITLE
RML/HTML Y-axis padding and margins are ignored

### ISSUE THREAD

**Issue by hobyst** [mikke89/RmlUi#336]
RmlUi (latest master) doesn't respect the default way of rendering HTML paragraphs `p` by making a line break for each new paragraph when used in standalone applications:
- `window.rcss`
```css
body {
    font-size: 20px;
}
```
- `hello_world.rml`
```html
<rml>

    <head>
        <title>Hello world</title>
        <link type="text/rcss" href="window.rcss" />
    </head>

    <body>
        <h1>RmlUi</h1>
        <p>Hello world!</p>
        <p>Goodbye!</p>
    </body>

</rml>
```
Result:
| Standalone | RmlUi demo sandbox |
| --- | --- |
![imagen](https://user-images.githubusercontent.com/48522412/180644856-00d72e85-1423-4108-a936-99d9ec9ad1b0.png) | ![imagen](https://user-images.githubusercontent.com/48522412/180644874-a895da43-44ff-4e07-a987-a5aebc50137c.png)

Neither it respects Y-axis margins and paddings when manually set in RCSS:
- `window.rcss`
```css
body {
    font-size: 20px;
}

p {
    margin: 100px;
}
```
- `hello_world.rml`
```html
<rml>

    <head>
        <title>Hello world</title>
        <link type="text/rcss" href="window.rcss" />
    </head>

    <body>
        <h1>RmlUi</h1>
        <p>Hello world!</p>
        <p>Goodbye!</p>
    </body>

</rml>
```
Result:
| Standalone | RmlUi demo sandbox |
| --- | --- |
![imagen](https://user-images.githubusercontent.com/48522412/180644501-0a5a7a9b-94a2-4f3b-9d99-79718e497cb0.png) | ![imagen](https://user-images.githubusercontent.com/48522412/180644621-28d89faa-1ed0-4164-a6de-b992296b12d4.png)

**Comment by mikke89** [comment]
The document has to be sized before getting the layout you expect. Set the width and height, or top/left/bottom/right properties on the body.

We don't have any built-in styles in RML, so by default the width and height of the document is zero, which gives these results.

**Comment by hobyst** [comment]
> The document has to be sized before getting the layout you expect. Set the width and height, or top/left/bottom/right properties on the body.

Setting `width` and `height` forces the text to stack as expected but just because there's too little space for all the text to fit in one line, so the moment the dimensions are big enough the problem appears again. Setting `top`, `bottom`, `right` and `left` did the job of making the margins to take effect on both axis, but still makes RmlUi to render all paragraphs in the same line.

> We don't have any built-in styles in RML, so by default the width and height of the document is zero, which gives these results.

This however was the key for everything. Checking the default CSS properties for HTML and setting `display` property to `block` for the `p` HTML element made everything work as expected.

**Comment by mikke89** [comment]
Ah I see, yes. You can find a recommended stylesheet here: https://mikke89.github.io/RmlUiDoc/pages/rml/html4_style_sheet.html
