### ISSUE TITLE
Vertex format question

### ISSUE THREAD

**Issue by YTN0** [mikke89/RmlUi#339]
Starting to integrate RmlUi into my app and have a question about the vertex format. 

Is there any easy way to specify a custom vertex format? Specifically, I want to change the format to match the format used by ImGui, since I have already written a framework around that, and it would be nice if I could swap out the renderers and make them interchangeable (by abstracting a couple pieces). 

The main difference with the formats being that ImgGui has position, texcoord and then color, whilst RmlUi has position, color and then texcoord.

I could try modifying the format in the RmlCore header file, and rebuilding RmlUi, but would that have any weird side-effects or issues? Since it's passthrough, I am assuming not. 

I would prefer not to modify the RmlUi original source if possible i.e. if there's a cleaner way to change the vertex format.

Thanks.

**Comment by mikke89** [comment]
Nice to hear from new people integrating the library. We don't have any built-in support for custom vertex formats. I guess changing the header should work, at least I can't think of any reason it shouldn't, but I would advise against it. Now you have a separate fork of RmlUi that you need to maintain.

My suggestion is to reconsider the abstraction level over the two libraries. You will probably want different shaders for each of them, and there are a different set of commands to implement. The way I see it, setting up two different vertex formats for these two libraries is a minor part of the differences that need to be considered.

**Comment by YTN0** [comment]
Thanks... that's the approach I decided to go with.
