### ISSUE TITLE
Comments in <style> element cannot contain text like "<something>"

### ISSUE THREAD

**Issue by eugeneko** [mikke89/RmlUi#341]
This RML file cannot be parsed because parsing `<>` happens before parsing `/**/`, so it *doesn't* ignore `<body>` tag in the comment.

This snippet is considered valid by https://validator.w3.org/ tho

```
<rml>
    <head>
        <style>
            body {
                /* <body> */
                width: 100%;
                height: 100%;
            }
        </style>
    </head>
    <body>
    </body>
</rml>
```

**Comment by mikke89** [comment]
It is tempting to say "don't do that", but the fix seemed to be very easy (see commit) so I went ahead with it.

Let me know if this change works for you or there are any issues.

**Comment by xland** [comment]
Does this commit incur runtime costs?

**Comment by mikke89** [comment]
No, at least nothing that is measurable.
