### ISSUE TITLE
Renaming performance branch to develop

### ISSUE THREAD

**Issue by mikke89** [mikke89/RmlUi#35]
This change should make it more clear that we will be merging this into master once everything is ready. Develop branch will become RmlUi v3.0.

Also, just letting you know I'm leaving for vacation next week, so there will be less activity from me for the following three weeks.
Happy coding :)

**Comment by viciious** [comment]
Alright, have fun! :P

**Comment by mikke89** [comment]
Thanks! :)

**Comment by barotto** [comment]
Been busy with irl stuff lately, just wanted to give my compliments for the v2.0 release! Which btw works fine on my system. Looking forward to the v3.0 release with all the performance improvements!

**Comment by mikke89** [comment]
Glad to hear it's working fine for you. Very much appreciate the feedback, thanks!
