### ISSUE TITLE
SVG element doesn't update texture when source changes unless the dimensions also change

### ISSUE THREAD

**Issue by Illation** [mikke89/RmlUi#361]
In `ElementSVG.cpp`
```cpp
void ElementSVG::UpdateTexture()
{
	if (!svg_document || !texture_size_dirty)
		return;
	// etc...
}
```
Probably just need to add another check here to not return early if the document was reloaded

My current workaround is resizing the svg element by 1 pixel back and fourth when the source changes

**Comment by mikke89** [comment]
Thanks for reporting the issue.

I've made a fix that seems to work for me, let me know how it goes for you :)
