### ISSUE TITLE
How to create C# plugin?

### ISSUE THREAD

**Issue by Guyiming** [mikke89/RmlUi#363]
> All of this directly from C++, or optionally from scripting languages using plugins. 

> Programming Documentation
[C++ Manual](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual.html)
[Lua Manual](https://mikke89.github.io/RmlUiDoc/pages/lua_manual.html)

I know RmlUi supports C++ and Lua, and I want to know how to create C# plugin?  Any guidance?

**Comment by YTN0** [comment]
@Guyiming I got it integrated into my codebase by creating a C++ CLR project and then referencing the RMLUi C++ code (include file and lib) from that project.  

I was pretty new to this stuff as well, so read some docs online for guidance.

See:

https://learn.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp?view=msvc-170 

https://learn.microsoft.com/en-us/cpp/dotnet/walkthrough-compiling-a-cpp-program-that-targets-the-clr-in-visual-studio?view=msvc-170

**Comment by Guyiming** [comment]
Ok, thanks @mikke89 @YTN0
