### ISSUE TITLE
Removing an element containing data model expression does not restore old expression

### ISSUE THREAD

**Issue by Dakror** [mikke89/RmlUi#365]
When removing an element from its parent, the child's data model gets cleared and all the views deleted. 
But the text of the element, which was set to the output of the data view after parsing and applying, is not reverted to contain the original expression.

My affected scenario:
Embedding a document inside another document, and dynamically detaching and attaching it. After the first attach - detach, the data views cannot be constructed since the element text is not an expression anymore.
Workaround: Completely re-load the embedded document, or use data-rml instead of data-text.

**Comment by mikke89** [comment]
Following the discussion in #366, this is considered unsupported (and documented as such) and something that would require a larger effort to support safely. For now at least we won't work on this.
