### ISSUE TITLE
Can't have bound variable in style tag

### ISSUE THREAD

**Issue by YTN0** [mikke89/RmlUi#368]
There's probably a simple solution for this, but I can't see to have a bound variable inside a style tag. I am trying to do the following inside a div tag:

`style="display : {{display}};"`

However, this generates a parse error:

`Syntax error parsing property declaration 'display: {{display;' in : 0.`

I am basically trying to programatically control the visibility of a div.

Note, the data model is defined on the same div viz.

`<div data-model="MyModel" style="display : {{display}};">`
`</div>`

Thanks.

**Comment by mikke89** [comment]
Hey. I think this is what you want to do:

```html
<div data-model="MyModel" data-style-display="display">
</div>
```

**Comment by YTN0** [comment]
@mikke89 Thanks... that works!

On a slightly different note, getting this to worked surfaced another hurdle with the C# -> C++ bridge. In RmlUi, the bind variables are std strings (Rml::String).

The problem is that these don't map to any C# object, so I create the Rml::String on the C++ side, and return a reference to the c_str so I can then use the value from C#. Whilst that works fine for reading the value on the C# side, if I need to update the string in c#, things get complicated, since just updating the c_str value doesn't actually update the std::string in c++ (specifically, whilst the characters are updated, the string length stays the same).

In order to correctly resolve this, I would like to be able to look up a model bound variable, so I can create a method like UpdateString(model, field, value). In that way, I can then just look up the already bound std::string and assign a new value.

I have a workaround right now which is to maintain a separate dictionary / map of the field name to the std::string, but that is clunky, since the data model is already maintaining this, and it would just be a matter of exposing a new method to look up the std::string bound variables.

**Comment by mikke89** [comment]
Hmm, to me it sounds like what you are doing already is illegal. You're not allowed to change `std::string` contents through the `c_str()` or `data()` pointer.

With that said, the client is responsible for providing the mapping from a given name to its variable. Thus, the library can expect the client to keep track of this themselves when the client needs to. Also remember that the client owns the string and is responsible for telling the library when the string has changed. Thus, I believe such functionality is outside the responsibility of the data model.

**Comment by YTN0** [comment]
I managed to find a clean way to solve this with a wrapper.
