### ISSUE TITLE
Some glyphs appear to sit slightly above or below the baseline

### ISSUE THREAD

**Issue by HyperLightResearch** [mikke89/RmlUi#369]
RmlUi 4.4
Windows 11 21H2 (22000.1098)
D3D11
GTX 3080 Ti

I'm integrating RmlUi into our engine and in the simplest use case, some text glyphs appear to not sit on the baseline.  I'm using hello_world.rml, rml.rcss, and window.rcss from the samples, and the rendering is straightforward - we don't change what gets passed into RenderInterface::RenderGeometry except for inverting V in UVs because it's D3D.  Screenshot attached.  You can see in the 'd', 'g', and 'q' glyphs that they're cropped.  Looks like the UVs are slightly off, but for the life of me can't find where our code is going wrong.

![rmlui](https://user-images.githubusercontent.com/54191963/198691172-01b2f003-36e9-44ca-9bde-b6caf3fd5c93.png)

**Comment by mikke89** [comment]
Hm, it's hard to say based on this alone. Looks a bit like you've flipped the vertical vertex position? May also be related to your UV flipping. The fact that everything renders from bottom to top indicates that the geometry position is applied in the wrong direction too.

You could also try with a different font just to rule that out, e.g. if you have the debugger loaded and initialized then it's just a matter of setting `font-family: rmlui-debugger-font;`.

**Comment by HyperLightResearch** [comment]
Hey, thanks for the quick reply.  I was incorrect, we actually don't flip UVs.  We do however horizontally flip geometry, but the problem persists even when geometry isn't flipped:

![image](https://user-images.githubusercontent.com/54191963/199081570-6fbab5b9-ebdb-48ca-9b58-7e6ebe3d9c99.png)

Here's our Rml init code, although I don't expect it to yield any insights:

```
Rml::SetSystemInterface(t.m_SystemImpl);
Rml::SetRenderInterface(t.m_RenderImpl);

Rml::Initialise();

m_Impl->m_Instancer = new UIEventListenerInstancer();
Rml::Factory::RegisterEventListenerInstancer(m_Impl->m_Instancer);

// Create a context to display documents within.
m_Impl->m_RmlContext = Rml::CreateContext("main", Rml::Vector2i(1904, 1041));
Rml::Context* context = m_Impl->m_RmlContext;

// Tell RmlUi to load the given fonts.
Rml::LoadFontFace("fonts/LatoLatin-Regular.ttf");

Rml::LoadFontFace("fonts/cour.ttf");

// Fonts can be registered as fallback fonts, as in this case to display emojis.
Rml::LoadFontFace("fonts/NotoEmoji-Regular.ttf", true);

// Set up data bindings to synchronize application data.
if(Rml::DataModelConstructor constructor = context->CreateDataModel("animals"))
{
	constructor.Bind("show_text", &t.m_ShowText);
	constructor.Bind("animal", &t.m_Animal);
}

// Now we are ready to load our document.
Rml::ElementDocument* document = context->LoadDocument("ui/Rml/hello_world.rml");
m_Impl->m_UIDocument = document;
document->Show();

// Replace and style some text in the loaded document.
Rml::Element* element = document->GetElementById("world");
if(nullptr != element)
{
	element->SetInnerRML(reinterpret_cast<const char*>(u8"🌍"));
	element->SetProperty("font-size", "1.5em");
}

element = document->GetElementById("Heading");
if(nullptr != element)
{
	element->AddEventListener(Rml::EventId::Mousemove, m_Impl->m_EventListener, true);
}
```

This is one of the atlases from a RenderDoc capture:

![image](https://user-images.githubusercontent.com/54191963/199083165-d6cfd317-5502-443e-9cc4-70f3edb48f5d.png)

I can't say the atlas is wrong since it's reasonable to have unique UV pairs for each glyph, but just in case, there it is.

Tangentially, I have Courier New being loaded from cour.ttf but I can't figure out how to reference it from rcss or rml.  How can I find the string to use to reference fonts, other than finding how it's referenced in Rml's internal dictionary?

**Comment by HyperLightResearch** [comment]
Fixed it.  It was us.  I moved all our geo fixup to the vertex shader and magically it's all gone away.  We were normalizing geo positions separately from normalizing translation, and then combining them later, so maybe floating point error was causing slight shifts, but that seems unlikely.  Anyway, for future reference, it's probably recommended to apply translation to positions and then normalize for screen space, in case anyone else runs into this issue in the future.

Another tangential question: what's the best way to get the width and height of the document?  I'd like to be able to positions documents dynamically and knowing dimensions is necessary to center it at a given point.  Thanks in advance!

**Comment by mikke89** [comment]
Alright, good to hear.

You can find the font name from the log output.

To get the size of the document, you can get its client width and height using the [DOM interface](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/elements.html#dom-interface). Btw, in RmlUi you can use `margin: auto` to center if the element size is well defined.

**Comment by HyperLightResearch** [comment]
Awesome, thank you for the pointers!
