### ISSUE TITLE
Single memory leak after first event is handled and Context::Update() is called

### ISSUE THREAD

**Issue by HyperLightResearch** [mikke89/RmlUi#371]
RmlUi 4.4
x86 Debug build
Windows 11 21H2 (22000.1098)
D3D11
GTX 3080 Ti

Repro:
1) Load a document
2) Attach a handler (that does nothing) to any element to handle 'click' or 'mousemove'.
3) Handle the event with the appropriate Context method
4) Call Context::Update()
5) Exit app

I'm seeing a memory leak, just one, that I've traced to when an event like 'click' or 'mousemove' is handled by Context and then Context::Update() is called.  The leak happens on the first event, and happens only once no matter how many more events or calls to Update() happen.  When no listeners are invoked, the leak doesn't occur.

From MSVC leak reporting:

```
{23283} normal block at 0x0B988108, 2052 bytes long.
 Data: <                > 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{23282} normal block at 0x0B9B38E0, 8 bytes long.
 Data: <        > 0C 81 98 0B 00 00 00 00 
{23281} normal block at 0x0B49B838, 28 bytes long.
 Data: <         8      > 80 00 00 00 01 CD CD CD E0 38 9B 0B 00 00 00 00 
```

Block addresses change of course, but the amount of memory leaked is the same no matter what event is raised.  The leak happens even when RmlCore.dll is unloaded before app exit (meaning static objects in RmlCore.dll, if any, should be deallocated when the module is unloaded and therefore not count towards memory usage).  The way I have leak reporting set up in win32 is at the start of winmain before any other work is done:

```
_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF)
_CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_DEBUG);
```

When the app exits, Visual Studio will dump leaks to the Output window.  If you want output to go elsewhere, check out alternatives to _CRTDBG_MODE_DEBUG.

**Comment by mikke89** [comment]
Hey, thanks for reporting.

Are you able to reproduce this in the built-in samples and provide the diff? That would be very helpful.

**Comment by HyperLightResearch** [comment]
It happens in the demo sample:

```
Detected memory leaks!
Dumping objects ->
{66397} normal block at 0x000002599B7AB060, 4104 bytes long.
 Data: <                > 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{66396} normal block at 0x000002599B82E320, 16 bytes long.
 Data: <h z Y           > 68 B0 7A 9B 59 02 00 00 00 00 00 00 00 00 00 00 
{66395} normal block at 0x000002599B7DADF0, 40 bytes long.
 Data: <            Y   > 80 00 00 00 01 CD CD CD 20 E3 82 9B 59 02 00 00 
Object dump complete.
```

In main.cpp, add this:

```
#include <crtdbg.h>
...
_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);    // at the top of WinMain
_CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_DEBUG);                        // at the top of WinMain
```

**Comment by mikke89** [comment]
Thanks for the instructions.

I can't replicate it on my end. Not getting any leaks. I did try to make a simple test by running `new int[4]` just to make sure the tool is working, and that was reported as a leak. But otherwise, nothing.

I tried both with static and shared libraries. Tested on Visual Studio 2022 v17.3.5.

**Comment by HyperLightResearch** [comment]
I've been trying to shake out actual lines of code that trace allocation as described here: https://learn.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2022 but have not had any luck.

I'm building with Visual Studio 2022 v17.3.6 but I don't think that should matter.  This is a debug x86 build, however, and RmlUI is a DLL that is loaded by another DLL that is manually loaded and unloaded before app exit. Everything uses MSVCP140D.dll and VCRUNTIME140D.dll.

**Comment by HyperLightResearch** [comment]
Also, we're having a similarly cryptic issue with another library, so it's possible we're doing something goofy, but we run with leak reports always dumped by default during development and maintain a zero-leak policy. Still, we may be doing something wrong, so we will continue to look on our end.

**Comment by mikke89** [comment]
I see, if you can track it down then let me know, I don't know this tool well enough. I'm regularly testing with valgrind and I'm not getting any leaks there either on my end.

**Comment by mikke89** [comment]
Closing this for now as I cannot reproduce it and the issue being stale. If you do track down a concrete issue in the library then please don't hesitate to report it again.
