### ISSUE TITLE
Is main stable enough to start using or is it better to wait for 5.0?

### ISSUE THREAD

**Issue by DomRe** [mikke89/RmlUi#382]
I've noticed a large number of improvements, especially to the rendering backend. Was wondering if it was stable/complete enough to start using, or is it better waiting for 5.0. Not in a particular rush.

**Comment by mikke89** [comment]
Hey there. Yeah, the current master branch should be quite stable right now, I'm about to release 5.0 soon with only small changes.

**Comment by DomRe** [comment]
Thanks for all your work!
