### ISSUE TITLE
RMLUI_ASSERT(open_inline_box == inline_box) error

### ISSUE THREAD

**Issue by ghexian** [mikke89/RmlUi#392]
hi, i found one assert error.
you can easily reproduce this error by the code below:
\<div style="display:inline;">
 \<div style="display:inline;">
      \<div style="display:block;">\</div>
 \</div>
 \<div style="display:inline;">
      \<div style="display:block;">\</div>
 \</div>
\</div>
when you run this code, you will get error below:
RMLUI_ASSERT(open_inline_box == inline_box) in LayoutLineBox.cpp:187
can anyone sovle this?

**Comment by mikke89** [comment]
Hey, thanks for reporting. I'm looking into this, for now it doesn't seem to cause any further issues for me, so you might just ignore it. I'm taking a closer look.

**Comment by mikke89** [comment]
This one is fixed with the large layout engine improvements in 4742dda07d9e21c414391d952df118baf04d0d4f, now merged into the master branch.

**Comment by ghexian** [comment]
oh, it's a pretty good job.

> This one is fixed with the large layout engine improvements in [4742dda](https://github.com/mikke89/RmlUi/commit/4742dda07d9e21c414391d952df118baf04d0d4f), now merged into the master branch.

**Comment by ghexian** [comment]
oh, I checked the code and tested. I found a new issue. you can try this code `div.flex {display: flex;width:200px;height:50px;border:1px;} <div class="flex">aaaa</div>` . and you will get text "aaaa" not displayed.

**Comment by mikke89** [comment]
Hi. We don't allow anonymous flex items in RCSS. In this situation you can wrap the text in another `div` element.

I have made a note to submit a warning in this case.

**Comment by ghexian** [comment]
ok, thanks for your work ^_^. I'll try implementing this.
