### ISSUE TITLE
[Request] Mutation events

### ISSUE THREAD

**Issue by LoneBoco** [mikke89/RmlUi#416]
It would be great if we could get some sort of basic mutation events around nodes being inserted, removed, or changed.  I'm not advocating for anything complex like supporting `MutationObserver`, just at least something basic that can be used with data models.

For my use case, I want to be able to bind some Lua that gets called whenever my `data-for` adds, removes, or changes elements.  Since this document is not always visible, the only workaround I can think of is to put a `show` event on the `body` and manually parse through the elements each time.  As far as I can see, there is no way to know that a data model bound in C++ was dirty and got updated.

If, for example, `Element::InsertBefore` spawned an `Inserted` event, I could do something like `data-attr-oninserted="concatenate('RegisterTags(event,\'', item.tags, '\')')"`.  Then as my data model adds new items, I could generate some Lua to execute that would register the item tags so I could update a filter list.  Of course, if the data model just changes element attributes instead (add and remove an item so the count stays the same), the above wouldn't work.  But there could be a `ModelUpdated` event that bubbles up to the `data-model` node (or is just called on the node).  Then that event could be caught and you could, for example, just issue `Inserted` events to all the children.

With just the inserted, removed, or model-changed events, I could more easily created a UI that reacts to changes in my data model.

**Comment by mikke89** [comment]
Hey, appreciate the suggestion. However, I feel like the suggested approach breaks the expected chain of events. Data views are intended to read data and display them, not modify data or run scripts. To me, starting to mess with this order feels like walking down the wrong path, and I would be worried that it leads to a cluttered design.

Additionally, events are just too slow to emit every time the DOM is modified, or when data models are updated. The client tells the data model that the list is dirty, so it already knows about the dirty list. There should be other approaches to solving this using that information.
