### ISSUE TITLE
Move Caret to End of Input Box

### ISSUE THREAD

**Issue by Stuyk** [mikke89/RmlUi#419]
I can't find any relevant information on this and the traditional functions that are utilized in normal javascript aren't available here.

Any options for this?

**Comment by mikke89** [comment]
Yeah, I can see this as being useful. I'm sure we could add an API for that. Do you have a suggestion?

As a work-around in the mean time, you could possibly get away with sending a keydown event to the element with the `KI_END` key.

**Comment by Stuyk** [comment]
Thank you for the tip on that. That being said a general API for determining where to place the caret based on length of the content inside would probably be sufficient. 👍🏻

**Comment by mikke89** [comment]
Alright, I am trying to understand your needs more clearly. Can you give more details on the suggested general API, or do you mean simply a `MoveCaretToEnd()` function with no inputs?

Can you point me to the related DOM/Javscript functions?

**Comment by Stuyk** [comment]
I think this would be sufficient. It allows you to select a range of text; or simply just move the selection to the very end of the input box.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange

Alternatively setting a value on an `input` box and moving the cursor to the end automatically could be sufficient for the input box behavior as well.

**Comment by mikke89** [comment]
Hey, I tried to implement this API now. Could you test it out, and let me know how it works for you?
If you find any issues, or some of its behavior could be improved, please let me know.

I didn't implement automatic movement of the cursor to the end. I'm a bit worried about how it plays out together with data bindings, and I figured it's safer to give that control fully to the user.

**Comment by ShawnCZek** [comment]
Being able to move the input caret around is really useful. And at least in my case scenario, it works perfectly fine 🚀 

Would it also be possible to add a getter for the current text selection? In JavaScript, which was referenced earlier, this is done by calling `window.getSelection()`. It returns a complex object with all kinds of stuff. Doing something similar is overkill for this library, in my opinion, and just returning a pair of integers for the start and end index will be good enough.

Similarly, are there any plans for adding these functions to Lua? 👀

**Comment by mikke89** [comment]
Great, I've merged it into master now :)
