### ISSUE TITLE
[Request] Scrolling element using scroll button

### ISSUE THREAD

**Issue by igorsegallafa** [mikke89/RmlUi#422]
It would be great if we could scroll the element when pressing the scroll button.

![](https://puu.sh/JAsQ3/e064299be7.gif)

**Comment by igorsegallafa** [comment]
I did a PR just for testing purpose. It works really similar for the feature I mentioned here, but I'm still have some doubts how the RmlUi Core works, then I have to find the properly way to do it.

**Comment by igorsegallafa** [comment]
We can let this issue open and close when we deal with these items:

- [ ] The minimum scroll speed is 1px/frame. This can actually be quite fast, depending on DPI and FPS. We could accumulate subpixel movement, and submit them once they are greater than one.
- [ ] It feels very sensitive near the reference, while opposite far away from the reference. Maybe it would feel better with a nonlinear speed vs distance? Try to square it? And perhaps add a deadzone near zero. This is mostly about tuning and feeling, we can tune this more later on as well.

**Comment by mikke89** [comment]
Hey, I've made some effort at improving this further. I've added a deadzone, quadratic distance-velocity model, two-axis scrolling, and subpixel velocity. I also refactored it a bit, and figured this feature is called autoscroll elsewhere, so I try to use that name consistently now. 

Can you test it, and let me know how it works and feels for you?

**Comment by igorsegallafa** [comment]
Oooh pretty cool, the auto scroll looks smoother for me and the code is very understandable. LGTM! 
Do you think we can mark this issue as completed?

**Comment by mikke89** [comment]
Cheers, glad you like it!

Yeah, let's consider this done. I'm also working on smooth scrolling while we're at it, so keep an eye out for that. I'll ping you for some feedback when it's done if you don't mind :)
