### ISSUE TITLE
[Request] RCSS letter-spacing property

### ISSUE THREAD

**Issue by zziger** [mikke89/RmlUi#426]
Would be nice to have ability to specify letter-spacing for text

**Comment by mikke89** [comment]
This could be useful, and I think it should be fairly easy to implement. However, it will require a breaking change in the font engine interface, so we will have to do this in a new major version of the library.

For reference, [CSS `letter-spacing` specification](https://w3c.github.io/csswg-drafts/css-text/#letter-spacing-property).

**Comment by igorsegallafa** [comment]
I've created a PR to deal with this feature, but any help is very welcome, thank you.

**Comment by mikke89** [comment]
This feature is now merged into the master branch.
