### ISSUE TITLE
Document doesn't receive the "Load" event

### ISSUE THREAD

**Issue by viciious** [mikke89/RmlUi#43]
This one is weird but it seems that on the develop branch, the document element never receives the "load" event. I can see the call to DispatchEvent alright but it just doesn't work for me for some reason. Things like "focus" and "blur" do make it to ProcessDefaultAction though.

**Comment by viciious** [comment]
Never mind, figured this one out.

**Comment by viciious** [comment]
I think the following condition evaluates to false:

```
	const bool do_default_action = ((unsigned int)phase & (unsigned int)default_action_phase);

	// Do the default action unless we have been cancelled.
	if (do_default_action && event.IsPropagating())
```

The event wasn't interrupted at that point.

**Comment by viciious** [comment]
It appears that the restrictive event specification for certain events is the culprit here:

```
		{EventId::Load          , "load"          , false , false , DefaultActionPhase::None},
		{EventId::Unload        , "unload"        , false , false , DefaultActionPhase::None},
		{EventId::Show          , "show"          , false , false , DefaultActionPhase::None},
		{EventId::Hide          , "hide"          , false , false , DefaultActionPhase::None},
```

**Comment by viciious** [comment]
I have since found a workaround for this so I don't mind if you just close the issue :)

**Comment by mikke89** [comment]
Yeah, the default action has changed a bit from how it worked previously. I will leave this open to remember to comment it a bit better. There is some more information in the readme.

**Comment by mikke89** [comment]
Improved comments in 469512f.
