### ISSUE TITLE
unresolved external symbols Freetype

### ISSUE THREAD

**Issue by IsGris** [mikke89/RmlUi#431]
i am trying to build rmlui library but i am getting error
to make build i'm using this command:

cmake -B Build -S . -DBUILD_SAMPLES=ON -DCMAKE_TOOLCHAIN_FILE="C:/Users/MyProf/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake" -DFREETYPE_LIBRARY=C:\Users\MyProf\Downloads\vcpkg\packages\freetype_x86-windows\lib -DFREETYPE_INCLUDE_DIRS=C:\Users\MyProf\Downloads\vcpkg\packages\freetype_x86-windows\include

and when I type cmake --build Build console I get this error:

FreeTypeInterface.obj : error LNK2019: reference to an unresolved external symbol FT_Init_FreeType in function "bool __cdecl
Rml::FreeType::Initialise(void)" (?Initialise@FreeType@Rml@@YA_NXZ). [C:\Users\MyProf\Downloads\RmlUi\Build\RmlCore.vcx
proj]

**Comment by mikke89** [comment]
Hi, and welcome.

It looks like the freetype libraries are not linked correctly. If you have installed freetype through vcpkg, you should not need to pass the `-DFREETYPE_...` arguments to CMake.

Please take a careful look at the documentation for [building RmlUi](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/building_with_cmake.html).
