### ISSUE TITLE
The new smooth scrolling modifications always consume the mousewheel event

### ISSUE THREAD

**Issue by Dakror** [mikke89/RmlUi#433]
With the changes to the mouse wheel event processing, the function never returns true, yielding the mouse wheel event to the rest of the application.

**Comment by mikke89** [comment]
Thanks for letting me know, I think this should solve it.

I'm still looking for feedback on the smooth scrolling mechanisms, how do you like it? Let me know if there are other issues, or room for improvements and tweaks.

**Comment by Dakror** [comment]
Thanks for the light-speed fix.

I'm personally more of a fan of instant scrolling especially on PC, but on mobile the smooth scroll is a good choice i think. Don't know how hard or feasible it would be, but adding the "overscrolling" Android can do could be pretty neat.
