### ISSUE TITLE
OpenGL backends & RmlUi should restore originally existing state after modification.

### ISSUE THREAD

**Issue by DomRe** [mikke89/RmlUi#437]
To maintain compatibility and prevent issues, if a state change occurs, such as when enabling scissor test or stencil test, changing framebuffers, etc, the backend should first query the existing state setting i.e. enabled/disabled and store that, then after the backend state changes are finished, restore to the original state.

**Comment by mikke89** [comment]
Yeah, I generally agree with this, it would make it simpler to get started. At least during Begin/EndFrame, probably not during render calls, that would be excessive. Perhaps we could make it possible to disable it with a compile time flag.

Would you be willing to submit a PR implementing this?
