### ISSUE TITLE
warning C4324: 'Rml::Core::Variant': structure was padded due to alignment specifier

### ISSUE THREAD

**Issue by viciious** [mikke89/RmlUi#44]
This one is spewed at you on each RmlUi file or include when compiling for x86_64 in Visual studio.

**Comment by mikke89** [comment]
Hopefully that should remove the warning. Alignment is probably not so important on x86, but we might have problems on some architectures.

**Comment by viciious** [comment]
Yup, that fixed the warning indeed, thanks!

**Comment by mikke89** [comment]
No problem :)
