### ISSUE TITLE
document returns false every time with Rml::ContextLoadDocumentFromMemory

### ISSUE THREAD

**Issue by Sammyueru** [mikke89/RmlUi#447]
Hello,
I'm trying to create a game using SDL2 with RMLUI but I keep getting "`The program '[12404] IsoSim.exe' has exited with code 4294967295 (0xffffffff).`" whenever I try running it in visual studio 2022 using C++20

I know the error is from this line:
`Rml::ElementDocument* document = rmlctx->LoadDocumentFromMemory(load_compiled_txt(SIM_UI_MAIN_RML));`

Because I have this:
`if (!document)
{
    Rml::Shutdown();
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return -1;
}`

I've followed all the documentation but it still won't work.
Does anyone know how to fix this?
Or if it's just a bug?
Because "load_compiled_txt(SIM_UI_MAIN_RML)" does return a string equal to the contents of "sim_ui_main.rml" because it's in the resources.rc and resource.h file

Code that may have something to do with the error:
The file "sim_ui_main.rml" looks like:
```
<rml>
<head>
	<title>SIM MAIN</title>
	<link type="text/rcss" href="mainsimui.rcss"/>
</head>
<body data-model="sim-main">
	Piece <select name="piece-select">
		<option value="none">None</option>
		<optgroup label="Core">
			<option value="p1">Generic Block</option>
			<option value="p2">Breadboard Block - Varient #0</option>
			<option value="p3">PCB Block</option>
			<option value="p4">Breadboard Block - Variant #1</option>
		</optgroup>
		<optgroup label="Physics">
			<option value="p129">Physics Ball</option>
		</optgroup>
	</select>
	Time scale (milliseconds) <input type="textbox" default="1000"></input>
</body>
</rml>
```

And of course "mainsimui.rcss":
`body {
	background-color: #00;
	border-radius: 16px;
}`

"load_compiled_txt(int resource)":
```
inline std::string load_compiled_txt(int resource)
{
	std::string txt;
	HRSRC hRes = FindResource(GCM(), MAKEINTRESOURCE(resource), MAKEINTRESOURCE(TXTFILE));
	HGLOBAL hgRes = LoadResource(GCM(), hRes);
	DWORD hSize = SizeofResource(GCM(), hRes);
	char* data = (char*)LockResource(hgRes);
	txt.assign(data, hSize);

	return txt;
}

```

"GCM()":
```
inline HMODULE GCM()
{
	HMODULE hModule = NULL;
	GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS, (LPCTSTR)GCM, &hModule);
	return hModule;
}
```

Anyways thanks for your time.

**Comment by Sammyueru** [comment]
I figured out part of it but now it's not displaying the document

And I do have document->show);

(The thing I figured out was that the font was in the wrong directory)
Sorry I was being so stupid

**Comment by mikke89** [comment]
Hey, it's nice to hear from new people testing out the library.

There could be several reasons for the document not showing up, there's not really enough information to go on here. Did you use one of the included backends, or implement your own render interface? Did you follow the [integration and initialization documentation](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/integrating.html#initialising-rmlui)? How far along did you get?
