### ISSUE TITLE
[Support] Compiler error in datatyperegister.h (Probably SFINAE related)

### ISSUE THREAD

**Issue by Praind** [mikke89/RmlUi#456]
Hello,
Thanks for putting so much effort into this libRocket successor!
I'm trying to migrate to RmlUi from an old project I worked on about 10 years ago.

When trying to build the project, I get compiling errors in the file `datatyperegister.h` on `line 116`. The errors are:
- `C2039: 'type': is not a member of 'std::enable_if<false,int>'`
- `C4430: missing type specifier - int assumed. Note: C++ does not support default-int`

I went through all the points mentioned in the "Breaking Changes" sections in the release notes.
I also tried compiling with the pre-compiled library and by using vcpkg.
However from what I read in other forums, it might be an issue related to MSVC being really bad at SFINAE.

So my questions are:
- What compiler do you guys use to build RmlUi projects?
- Do you know of any fix/workaround for this issue?

Some more details:
- RmlUi version: 5.1
- C++ Version: C++14
- Compiler: MSVC v140 VS 2015

**Comment by mikke89** [comment]
Hey, and thanks for the kind comments!

Yes, unfortunately, VS 2015 is not supported, specifically due to issues like these. We only support VS 2017 and newer, I hope you're able to upgrade your toolchain.

**Comment by Praind** [comment]
Thanks for the hint! I got it working with the v141 VS 2017 toolset.
