### ISSUE TITLE
Button margin/padding

### ISSUE THREAD

**Issue by gleblebedev** [mikke89/RmlUi#471]
I'm trying to make a button with a ninepatch decorator:
```
input.button
{
    padding-left: 12px;
    padding-right: 12px;
    padding-top: 12px;
    padding-bottom: 12px;
    decorator: ninepatch( blue-button, blue-button-inner, 1.0 );
    font-effect: shadow(0px 2px #333);
    font-weight: bold;
}
```
But instead of pushing text inside of the button down the button itself seems to be pushed up and now overlaps previous lines of text. The text in the button seems to be aligned with another text in the same line.

How can I make position of the text inside of the button to be controlled by input padding? I would like to slightly shift it up and down with the button press.

https://gyazo.com/c026284abde72bde0d19a285c501fc66?token=adfc2a0ddb7f137a00f1bcd8daf1c2cf

**Comment by gleblebedev** [comment]
@mikke89 thanks for a timely reply!

Padding seems not to working as expected.  It isn't moving text inside button but it moves button keeping text stationary. I have a temporal workaround by adding "display: block" property into the input's css. But now the button wants to occupy all available space and I really would like it to have size evaluated from input's content.

**Comment by gleblebedev** [comment]
Ok, with display: inline-block and overflow: auto it is much better
![image](https://github.com/mikke89/RmlUi/assets/2943937/53c2bbeb-fb16-48c5-b8d9-c6b637ad5a55)
But I'm still struggling to move text inside of the input up and down. Can I combine padding with vertical-align in the same style?

**Comment by mikke89** [comment]
With inline-blocks you can add padding yes. It might also be useful to add `box-sizing: border-box` so that the size of the button doesn't change with that. Vertical-align will move the button relative to the surrounding text.

**Comment by gleblebedev** [comment]
Thanks! I'm sorry to bother you but I'm not a front-end developer and I have nobody to ask this.
Here is what it looks like now:
https://gyazo.com/52ff083a2aa28a546e87c09f083dc229
```input.blue-button
{
    padding-left: 12px;
    padding-right: 12px;
    padding-top: 12px;
    padding-bottom: 12px;
    display: inline-block;
    overflow: auto;
    vertical-align: center;
    box-sizing: border-box;
    decorator: ninepatch( blue-button, blue-button-inner, 1.0 );
    font-effect: shadow(0px 2px #333);
    font-weight: bold;
}

input.blue-button:hover
{
    decorator: ninepatch( blue-button-selected, blue-button-selected-inner, 1.0 );
}

input.blue-button:active
{
    decorator: ninepatch( blue-button-pressed, blue-button-pressed-inner, 1.0 );
}

input.blue-button:disabled
{
    decorator: ninepatch( blue-button-disabled, blue-button-disabled-inner, 1.0 );
    font-effect: none;
}
```
The last piece is to move text within the button up and down. If I add this to the css
```
input.blue-button:hover
{
    padding-top: 9px;
    padding-bottom: 15px;
    decorator: ninepatch( blue-button-selected, blue-button-selected-inner, 1.0 );
}
```
it moves the button, not the text:
https://gyazo.com/65d13b96b9b51331e8c714ecc962f2cc
Is there a way to achieve the desired effect?

**Comment by gleblebedev** [comment]
I've tried to add an internal span and do
vertical-align: -3px;
or
position:relative;
top:-3px;
on it with no luck :(

**Comment by mikke89** [comment]
To move the text down, add *more* to the padding-top, and subtract *the same amount* from padding-bottom.

This is working well for me:

```css
input.blue-button {
    padding: 12px;
    display: inline-block;
    overflow: auto;
    vertical-align: center;
	background: #933;
	color: white;
}
input.blue-button.lowered-text {
	padding-top: 20px;
	padding-bottom: 4px;
}
```

```html
Bla bla some text<br/>
Another line <input class="blue-button" type="button">Button text</input> line continues<br/>
Last line<br/>
Another line <input class="blue-button lowered-text" type="button">Button text</input> line continues<br/>
```

![image](https://github.com/mikke89/RmlUi/assets/5490330/8093bdf4-455c-4460-9e87-f3bcff9e5fcd)

**Comment by gleblebedev** [comment]
Is it something that was fixed since 2021?
Because this is what I see:
![image](https://github.com/mikke89/RmlUi/assets/2943937/cf70655c-a227-4df7-8dbb-56e217afac3e)

```
input.blue-button
{
    padding-left: 24px;
    padding-right: 24px;
    padding-top: 24px;
    padding-bottom: 24px;
    display: inline-block;
    overflow: auto;
    vertical-align: center;
    box-sizing: border-box;
    decorator: ninepatch( blue-button, blue-button-inner, 1.0 );
    font-effect: shadow(0px 2px #333);
    font-weight: bold;
}

input.blue-button.lowered-text
{
    padding-top: 34px;
    padding-bottom: 14px;
}
...
	<input type="button" class="blue-button"><span>New Game</span></input>
	<input type="button" class="blue-button lowered-text">Continue</input>
```

**Comment by mikke89** [comment]
Ah, I see, yeah, I've pretty much rewritten the entire inline layouting engine since then, so there are certainly differences since then.

Looks like it's still lining up the buttons based their inner text. Do you need inline layout? Another approach could be to use floating boxes: `display: block; float: left;`. Maybe some work-arounds are possible: Wrap the inside text inside a div? Not sure if that helps. The best thing would be to update the library.

**Comment by gleblebedev** [comment]
I'll try the library update first. Thank you for support!

**Comment by gleblebedev** [comment]
![image](https://gyazo.com/1bef39bb666bb504c9b0a21ebd87718f.gif)

**Comment by gleblebedev** [comment]
Case closed

**Comment by mikke89** [comment]
Nice, looking good!
