### ISSUE TITLE
std::istringstream usage in StringUtilities::DecodeRml makes customizing String type impossible

### ISSUE THREAD

**Issue by eugeneko** [mikke89/RmlUi#472]
Until these changes, it was possible to use any string type in RmlUI as long as it had standard interface (e.g. EASTL).
Now, it is impossible because `std::istringstream` cannot accept anything but `std::string`.

I am not saying that you should stop using `std::istringstream`, but maybe RmlUI needs a customization point to initialize `std::istringstream` with arbitrary string type.

**Comment by mikke89** [comment]
Ah, I see. As far as I can tell, the istream is only used to convert from hex-encoded number in a string to an integer. Maybe there are other approaches to consider? `std::stoi` possibly, or some scan-function?

**Comment by rokups** [comment]
I always use good old `sscanf`. Not something "modern C++" would advise, but rooted in reality at least 😁

**Comment by mikke89** [comment]
Yeah, I don't mind `sscanf` in this case. I think `std::stoi` throws, which might be problematic. PR incoming from any of you? :)

**Comment by gleblebedev** [comment]
@mikke89 if it looks ok I can make a PR later

**Comment by gleblebedev** [comment]
@mikke89 is &#00; not a valid symbol? Or what do you mean by checking for zero?

**Comment by gleblebedev** [comment]
Ha, github converted the html unicode symbol into symbol.

**Comment by mikke89** [comment]
I'm just looking over this, zero is returned if conversion can not be performed: https://en.cppreference.com/w/cpp/string/byte/strtoul.

**Comment by gleblebedev** [comment]
https://github.com/mikke89/RmlUi/pull/475
