### ISSUE TITLE
Is display: contents available, or is there any equivalent?

### ISSUE THREAD

**Issue by natinusala** [mikke89/RmlUi#473]
Hi, I am considering using RmlUi for my project but there is something crucial from the CSS standard that I need, and I don't think it's available yet : `display: contents`.

I need it to have flexbox perform its layout on elements deeper in the tree, and not on its immediate children. As described here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Relationship_of_flexbox_to_other_layout_methods#flexbox_and_display_contents

Can RmlUi do this? I didn't see `display: contents` in the documentation.

**Comment by mikke89** [comment]
Hey, I appreciate the interest.

I'm curious to hear more about your use case, where this is such an essential feature. We don't currently support this as you've noticed, and I haven't really seen any convincing reasons to consider adding it either.

**Comment by natinusala** [comment]
I would like to make an open source, multiplatform toy clone of SwiftUI. I intend to target desktop first, and maybe mobile later.

I already have the "virtual DOM" part more or less working (I say virtual DOM even though it has nothing to do with React or other web frameworks) but now I need a renderer (or layout engine) that is capable of having partial nodes in the tree. That is, I need the ability to add a layout node with, say, the padding property and ONLY the padding property. It needs to be ignored for all other layout passes / features.

The best example that I know is the Flutter RenderObject framework, that was made specially for Flutter and would perfectly meet my need if it wasn't made in Dart. They have atomic nodes that do one and only one thing. This reduces complexity in the "virtual DOM" part because it doesn't need to move, remove, merge or create artificial render nodes. The render tree is (almost) a perfect match of the widgets tree.

This also applies to graphics nodes, they have "background color" nodes that are no-op in terms of layout but apply a background color to themselves. They can be combined to a padding node to make a container, etc... It works by nesting different nodes together to achieve what you want. It would be normally horrible to use but this is actually perfect for the modifier based SwiftUI syntax.

For instance I would need to be able to do this (in pseudo code):
```
<flex direction=row>
    <p>Some text</p>
    <p>Some other text</p>
    <div display=contents padding=50px>
        <p>Some more text</p>
        <p>Last text I swear</p>
    </div>
</flex column>

The two paragraphs inside the div should be laid out as if they were direct children of the flexbox BUT with applied padding around both of them. Padding shouldn't be duplicated and applied to the two paragraphs, but rather applied on the container div. But it should be ignored for everything else than padding.

I don't know web development that much so I don't even know if `display: contents `would fit that need on a regular web browser. I would be happy to hear your thoughts on that.

**Comment by mikke89** [comment]
Alright, thanks for explaining the use case. I'm quite intrigued, this is completely outside what I'd expect the library to be used for. That said, this doesn't really align with the goals of the library, so not something I would put a lot of effort into accommodating.

Perhaps more importantly though, `display: contents` doesn't really behave like that. Its padding would have no effect, instead, the property would make the div's box be be completely ignored in terms of layouting.

**Comment by natinusala** [comment]
Oh I see, thanks for the clarification.

The search continues I guess. I might try to make a Yoga (or Stretch or whatever else exists) wrapper to mimick what I need, or try to get as close as I can.

Or maybe I have the same result in RmlUi actually? I guess I would need to have all flex properties (such as direction) be preserved across the whole tree

I considered RmlUi because it would have been an all-in-one solution for layout and rendering. Being able to do web rendering from C++ without depending on JS is great 😄

**Comment by mikke89** [comment]
No problem, cheers.

If you're mainly interested in flexbox layout with some custom bells and whistles, then you might also want to consider writing it yourself. It's certainly far from an insurmountable task, having done so myself.
