### ISSUE TITLE
how compile code dont use cmake 

### ISSUE THREAD

**Issue by huiseliming** [mikke89/RmlUi#474]

**Comment by huiseliming** [comment]
any example to set precompile macro and source file and ...

**Comment by mikke89** [comment]
There aren't enough details here to help out. Please take a good look at the [building documentation](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/building_with_cmake.html) for how to build the library. We only support CMake. For manual building, please take a look at the flags we add there.
