### ISSUE TITLE
any api to save modified Rml::ElementDocument  to file

### ISSUE THREAD

**Issue by huiseliming** [mikke89/RmlUi#476]

**Comment by huiseliming** [comment]
any method that supports serialization

**Comment by huiseliming** [comment]
I can use tinyxml to sequence html tags and attributes, but I can't get the stylesheet of a single tag

**Comment by huiseliming** [comment]
There are many classes that have not been exported and I cannot try to read them, such as Rml::ElementDefinition, Rml::ElementStyle, etc. Will these classes be exported in the next version

**Comment by huiseliming** [comment]
![a5aeeb82b2c00e443bd9c1a8880ac6a](https://github.com/mikke89/RmlUi/assets/16591229/096f7b7a-9b72-4cc8-83a6-a33b50fb77dd)

I integrated it into Unreal Engine

**Comment by mikke89** [comment]
The UE integration effort looks nice!

> There are many classes that have not been exported and I cannot try to read them, such as Rml::ElementDefinition, Rml::ElementStyle, etc. Will these classes be exported in the next version

There are no plans to make these internal classes public.
