### ISSUE TITLE
In case of multiple contexts I need the ActivateKeyboard of the system interface to provide the context parameter

### ISSUE THREAD

**Issue by huiseliming** [mikke89/RmlUi#477]
Can context be provided in this function
virtual void Rml::SystemInterface::ActivateKeyboard(Rml::Vector2f caret_position, float line_height) override;
like
virtual void Rml::SystemInterface::ActivateKeyboard(Rml::Context* context, Rml::Vector2f caret_position, float line_height) override;

I need to get context to implement unreal ITextInputMethodContext to use IME

In the following two functions I am missing context
bool FRmlTextInputMethodContext::GetTextBounds(const uint32 BeginIndex, const uint32 Length, FVector2D& Position, FVector2D& Size)
{
	if (RmlWidget.IsValid())
	{
		CUnrealRmlSystemInterface* SystemInterface = static_cast<CUnrealRmlSystemInterface*>(Rml::GetSystemInterface());
		if (SystemInterface)
		{
			//// Let the IME editor follow the cursor
			//Position = FVector2D(CachedGeometry.AbsolutePosition.X + ImGuiContext->PlatformImeLastPos.x,
			//	CachedGeometry.AbsolutePosition.Y + ImGuiContext->PlatformImeLastPos.y + 20);
		}
	}
	return false;
}

void FRmlTextInputMethodContext::EndComposition()
{
	if (bIsComposing)
	{
		bIsComposing = false;

		if (RmlWidget.IsValid())
		{
			CUnrealRmlSystemInterface* SystemInterface = static_cast<CUnrealRmlSystemInterface*>(Rml::GetSystemInterface());
			if (SystemInterface)
			{
				auto CharArray = CompositionString.GetCharArray();
				for (int i = 0; i < CharArray.Num(); i++)
				{
					CharArray[i];
					SystemInterface->pro();
				}
				CompositionString.Empty();
				CompositionBeginIndex = 0;
				CompositionLength = 0;
				SelectionRangeBeginIndex = 0;
				SelectionRangeLength = 0;
			}
		}
	}
}

**Comment by mikke89** [comment]
We don't provide the context here in this function, we don't necessarily assume that a keyboard is tied to a context. You will have to find another way to keep track of it.

**Comment by mikke89** [comment]
Let's continue this discussion in #489.
