### ISSUE TITLE
Crash when accessing the last property of LocalStyleProperties

### ISSUE THREAD

**Issue by huiseliming** [mikke89/RmlUi#479]
const Rml::PropertyMap& LocalStyleProperties = ChildRmlElement->GetLocalStyleProperties();
                        if (LocalStyleProperties.size() > 0)
                        {
                            auto NumLocalStyleProperties = LocalStyleProperties.size();
                            auto LocalPropertyIterator = LocalStyleProperties.begin();
                            for (int32 i = 0; i < NumLocalStyleProperties; i++)
                            {
                                if (i != 0)
                                    ++LocalPropertyIterator;
                                if (LocalPropertyIterator->second.value.GetType() != Rml::Variant::NONE)
                                {
                                    Rml::String StylePropertyName = Rml::StyleSheetSpecification::GetPropertyName(LocalPropertyIterator->first);
                                    Rml::String StylePropertyValue = LocalPropertyIterator->second.ToString();
                                    Style += StylePropertyName + ": " + ";";
                               }    //  crash here
                            }
                        }

Does the data need thread protection or am I overlooking something

**Comment by aquawicket** [comment]
where is Style initiated?

**Comment by huiseliming** [comment]
ChildRmlElement->GetLocalStyleProperties() returns template class PropertyMap = robin_hood::unordered_flat_map< Key, Value >
Template instantiation is likely to be incompatible in different compilation environments, it should be changed to Rml::PropertyDictionary which is an exported class

**Comment by huiseliming** [comment]
It seems that the so-called C++ ABI is different

**Comment by aquawicket** [comment]
If you are on arm/android   i had problem with robin_hood,    my fix was a CMAKE -DCHOBO_FLAT_MAP_NO_THROW

**Comment by huiseliming** [comment]
> 如果你使用的是arm/android，我遇到了robin_hood的问题，我的修复是CMAKE -DCHOBO_FLAT_MAP_NO_THROW

My environment is UE5 Window

**Comment by aquawicket** [comment]
There are 1 or 2 flags in RmlUi CMakeLists.txt that deal with robin_hood,   I'd start there.

**Comment by huiseliming** [comment]
I think it should be changed to Rml::PropertyDictionary Or export template instantiation of Rml::PropertyMap

**Comment by aquawicket** [comment]
Grab the thread ID at start and make sure you're on main thread there is my last guess.   I've only ever failed at robin_hood when I tried arm architecture.  Hope you find it :)

**Comment by huiseliming** [comment]
I'll go and try that first, but I think changing to Rml::PropertyDictionary or exporting a template instantiation of Rml::PropertyMap is necessary

**Comment by mikke89** [comment]
It's possible that the ABI issue is because the library is compiled with different settings than the project it is consumed from. In particular, make sure `RMLUI_NO_THIRDPARTY_CONTAINERS` is either defined, or not defined, in *both* projects (RmlUi and your application). Not doing so will result in ABI breakage.

**Comment by huiseliming** [comment]
> It's possible that the ABI issue is because the library is compiled with different settings than the project it is consumed from. In particular, make sure `RMLUI_NO_THIRDPARTY_CONTAINERS` is either defined, or not defined, in _both_ projects (RmlUi and your application). Not doing so will result in ABI breakage.

I fixed it by giving the source code to UBT to compile, but some modifications are needed, can these be added to the next version. I want to use the release you posted directly

Please add the following modification

https://github.com/huiseliming/RmlUi/commit/18d8904a01b38eae4a7b92cf50e9d6dd643eb89a

**Comment by mikke89** [comment]
Can you elaborate on these modifications? E.g. why do you need to change the `RMLUICORE_API` define, and what are you setting it to?

**Comment by huiseliming** [comment]
> Can you elaborate on these modifications? E.g. why do you need to change the `RMLUICORE_API` define, and what are you setting it to?


In UE, RMLUICORE_API is a precompiled macro of the module, if it is defined again, error will be reported

**Comment by mikke89** [comment]
This is a pretty common declaration for dynamic libraries, surely there must be a way to work with that in unreal, without introducing additional conditions. My suggestion is to make sure that the exports macro is undefined, or alternatively, work with the static macros.
