### ISSUE TITLE
Multiple windows/contexts (feature, sample request)

### ISSUE THREAD

**Issue by aquawicket** [mikke89/RmlUi#480]
**Multiple windows/contexts (feature, sample request)**

I'm attempting to create 2 SDL windows, with 2 seperate contexts.
I however run into 2 issues. 

1. The render interface must be initiated prior to Rml::Initialize(),  no further render interface changes are allowed after. So I understand I must make one render handler that can get the curent window and context, and process as needed. 
	
2. After creating a second SDL window, and using the SAME render interface, Rml fails to create a new context.

	Error @  Context.cpp:70        RMLUI_ASSERT(cursor_proxy_document);
	rmlui_dynamic_cast<ElementDocument*>(cursor_proxy.get()); returns a NULL when attempting to create a new context. 
	

Before I spend hours debugging, I must first ask. . .	
Is it possible to run 2 rml contexts in 2 seperate windows?
If so, can we create a basic sample, showing multiple rml window handling.

**Comment by huiseliming** [comment]
> **Multiple windows/contexts (feature, sample request)**
> 
> I'm attempting to create 2 SDL windows, with 2 seperate contexts. I however run into 2 issues.
> 
> 1. The render interface must be initiated prior to Rml::Initialize(),  no further render interface changes are allowed after. So I understand I must make one render handler that can get the curent window and context, and process as needed.
> 2. After creating a second SDL window, and using the SAME render interface, Rml fails to create a new context.
>    Error @  Context.cpp:70        RMLUI_ASSERT(cursor_proxy_document);
>    rmlui_dynamic_cast<ElementDocument*>(cursor_proxy.get()); returns a NULL when attempting to create a new context.
> 
> Before I spend hours debugging, I must first ask. . . Is it possible to run 2 rml contexts in 2 seperate windows? If so, can we create a basic sample, showing multiple rml window handling.

I render different Context to different windows in UE, so surely it is possible to run 2 rml contexts in 2 separate windows

**Comment by huiseliming** [comment]
![a5aeeb82b2c00e443bd9c1a8880ac6a](https://github.com/mikke89/RmlUi/assets/16591229/096f7b7a-9b72-4cc8-83a6-a33b50fb77dd)

look this

**Comment by mikke89** [comment]
I don't know SDL multi-windowing specifically, but there is nothing in RmlUi that should stop you from having as many contexts as you'd like. To your first point, yes, this is something you need to handle. The second point, I can't really help you here, I don't have any ideas why this would be crashing without further context.

It would be nice with a sample demonstrating this. The only issue is that it would require backend changes, and it's not really a feature we want to add to all the backends, for the sake of keeping complexity low.

**Comment by aquawicket** [comment]
Turns out I was making changes to the body element instancer, and needed restore it before calling a new context. So that issue is solved, And I can successfully render 2 separate contexts in 2 sperate windows.

My only issue now is telling the renderer which window to process at the right time. My first window renders correctly, but my second will now render textures. I get color boxed, underlines, and other primitive types to display, but no text or images. It's very close t working.

Is there a way to get the current context from within the Render handler?

Currently I'm cheating by setting the window pointer in the Render handler before calls to context->Render(); context->Update(); and context->ProcessMouseMove();  etc...

**Comment by mikke89** [comment]
Glad to hear you fixed the crash. Seems like multi-window setups are suddenly in the wind, see #481 for some of the same discussion :) Maybe you could share some solutions.

So we used to be able to set a different render interface for each context, and also get the context from the render interface. Since the last release, I removed this. The solution wasn't very robust, and essentially did the same thing you do now, set the active context before the call to Context::Render. So you might as well do that until we have a better solution.

**Comment by mikke89** [comment]
Alright, let's continue that discussion in #489. I think this one can be considered resolved. If anyone is interested, feel free to submit a multi-window sample as discussed :)
