### ISSUE TITLE
Luarocks?

### ISSUE THREAD

**Issue by Frityet** [mikke89/RmlUi#483]
Will this project ever be present on Luarocks, the Lua package manager?

**Comment by mikke89** [comment]
Appreciate the request. I don't have any plans for this, but I'd welcome any user contributions to submit the library.

**Comment by Frityet** [comment]
> Appreciate the request. I don't have any plans for this, but I'd welcome any user contributions to submit the library.

I will try.

**Comment by mikke89** [comment]
Closing this one, let us know if you decide to add the library.
