### ISSUE TITLE
Does the newly added decorator repeat tiling mode support the use of decorator sprites？

### ISSUE THREAD

**Issue by w4454962** [mikke89/RmlUi#495]
I need to use a sprite image in "decorator: tiled box" to modify the original stretching of the sprite image at the top, bottom, left, and right edges to a repeating tiled style.

**Comment by w4454962** [comment]
So I need to change the stretching of the top left and bottom right edges in the 'decorator: tiled box' to tiled, and need to recalculate to generate multiple polygons, right?

**Comment by mikke89** [comment]
I don't follow exactly what you propose. If all you need is 3x3 repeats, then I guess you can make it work with a `tiled-box` decorator. At that point you might want to consider using a custom decorator instead. Or simpler, just make some separate images out of those sprites.

**Comment by w4454962** [comment]
The situation may be quite complex, and I need to crop an image with 8 edges in the sprite. Among them, 2 edges need to be flipped 90 degrees, and the edges need to be repeated without stretching. The size of the center also needs to be adjusted, so I am already trying to customize the decorator.
