### ISSUE TITLE
Is there a Tooltip related style in Rml

### ISSUE THREAD

**Issue by w4454962** [mikke89/RmlUi#496]
How to automatically stretch the background control size based on the content of the text, the length of a single line, and the number of lines, similar to "tooltip" that needs to adapt the size according to the prompted content

**Comment by w4454962** [comment]
After using<br>line breaks, the background generated by the decorator will only take effect on the first line, including the padding attribute, which will only take effect on the text in the first line

**Comment by w4454962** [comment]
The display image size of the decorator can only be calculated based on all boxes through custom decorators, so that the background image can cover the entire control

**Comment by mikke89** [comment]
Sounds like you found a solution. But it might also be useful to know about e.g. `display: inline-block` which is able to shrink the element size to its contents. Then you can put any background color or decorators on that element, and voilà, you have you're tooltip-like look.
