### ISSUE TITLE
Border-image implementation

### ISSUE THREAD

**Issue by pgruenbacher** [mikke89/RmlUi#503]
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image

This is a pretty useful way to have decorative borders that repeat / stretch.
I'm working on a feature branch. Seems straight-forward enough, just need to implement it on ElementBackgroundBorder.

**Comment by pgruenbacher** [comment]
oh my apologies I realize this was the intent of Tiled-box decorator.

**Comment by mikke89** [comment]
Yeah, the tiled-box decorator will cover a lot of these use cases, and more generally custom decorators can be used for more advanced effects. Although it's not out of the question to consider things like this, that make it either friendlier for common use cases, or closer to CSS.

Feel free to make other suggestions, or pull requests :)

**Comment by pgruenbacher** [comment]
I'm wondering if I should implement a Decorator Fifteen Patch which implements center elements
![image](https://github.com/mikke89/RmlUi/assets/3332598/cbb95780-8de4-4994-971c-e5df95112a37)

**Comment by pgruenbacher** [comment]
Overlaying a nine-patch with a tiled-vertical element doesn't really scale that easy and too much of a headache.

**Comment by pgruenbacher** [comment]
Nvm tiled-vertical works fine so long as you hardcode the width of the tiled-vertical to match expected image dimensions and then use margin:auto to center it.
