### ISSUE TITLE
Get element size in pixels

### ISSUE THREAD

**Issue by Withaust** [mikke89/RmlUi#508]
I am currently using Rml as a foundation for my game, and I need to know how much an element is taking up in pixels in order to allocate GPU textures of this size. Is it possible to get this info? Because after searching through the `Element` and `StyleSheet` classes I could not find anything.

**Comment by mikke89** [comment]
Hey, cool to hear you're using the library for your game. Feel free to keep us updated and send some screenshots.

That is certainly possible. We're using the DOM methods for these sort of things: https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/elements.html#dom-interface
What you probably want is the offset size. Alternatively, you can retrieve the Box of the element directly (GetBox), and retrieve the size you want from that. Remember that any such methods should be called only after layout is complete, i.e. after Context::Update.

**Comment by Withaust** [comment]
Thanks! Turns out that `GetContainingBlock()` is what I needed all along.
