### ISSUE TITLE
Gradient decorator

### ISSUE THREAD

**Issue by viciious** [mikke89/RmlUi#51]
I know it's been suggested before, but here's a more less working implementation, which can be salvaged for RmlUI: https://github.com/Qfusion/qfusion/blob/master/source/ui/decorators/ui_gradient_decorator.cpp

I think it's missing three major things (but none are critical in my opinion):
- diagonal gradients, trivial to implement
- multiple colors: doable by subdividing the quad into smaller quads for each color transition
- radial gradients - non trivial, I'd rather skip this one for now

Comments and suggestions are welcome :)

**Comment by mikke89** [comment]
Yeah, this would be a nice addition!

I think for radial gradients and arbitrary rotated linear gradients we would probably have to generate a texture. But I'm happy with just a simpler implementation :)

**Comment by mikke89** [comment]
Horizontal and vertical color gradients implemented in #53.

**Comment by mikke89** [comment]
Closing this as we have basic support, potential improvements can be discussed in a new issue.
