### ISSUE TITLE
Compile error when using custom RTTI

### ISSUE THREAD

**Issue by doctorames** [mikke89/RmlUi#514]
Howdy

When using custom RTTI (`/DRMLUI_USE_CUSTOM_RTTI`), getting compile error:
```
....foo\Core\Traits.h(131): error C2039: 'RttiClassType': is not a member of 'Rml::InlineBox'
```

Just need a little macro love in InlineBox.h and InlineLevelBox.h:

InlineBox.h:
```c
class InlineBoxBase : public InlineLevelBox {
public:
	RMLUI_RTTI_DefineWithParent(InlineBoxBase, InlineLevelBox)
...
...
class InlineBox final : public InlineBoxBase {
public:
	RMLUI_RTTI_DefineWithParent(InlineBox, InlineBoxBase)
...
...
class InlineBoxRoot final : public InlineBoxBase {
public:
	RMLUI_RTTI_DefineWithParent(InlineBoxRoot, InlineBoxBase)
```

InlineLevelBox.h:
```c
class InlineLevelBox {
public:
	RMLUI_RTTI_Define(InlineLevelBox)
```

I fixed this in my local copy. Obviously I don't have PR access so if one of yall gets a chance, easy fix. (Assuming this is the proper fix. 😄  )

Thanks!
d

**Comment by mikke89** [comment]
Thanks for reporting! And for suggesting a solution. Please know that PRs are very much welcome and open for everybody, so don't be shy ;)

I went for a different solution than suggested. It would have worked perfectly fine, but we don't really need RTTI here as it was only used for a single assertion. Instead I made a semi-related change that should also fix this issue. I've wanted to implement something like this for a while, and this was a good excuse. Let me know if there are any issues with the changes.
