### ISSUE TITLE
Enabling Tracy profiling when Tracy is already used

### ISSUE THREAD

**Issue by p2004a** [mikke89/RmlUi#516]
I'm working on adding RmlUi to build of [engine](https://github.com/beyond-all-reason/spring) used by https://www.beyondallreason.info/. The issue I've ran into is that we are already using Tracy for profiling our engine, we include it and link the `TracyClient` target exported by library.

Unfortunately it looks like we can't have Tracy enabled for both our engine and RmlUi because RmlUi is literally including the tracy cpp file in https://github.com/mikke89/RmlUi/blob/master/Source/Core/Profiling.cpp When linking, this is breaking the One Definition Rule.

RmlUi should allow to link to the tracy client that is already used in the program that integrates it.

**Comment by mikke89** [comment]
Hey, always happy to hear about new integrations, and looks like a very cool project.

Yeah, we can definitely improve how we include Tracy. I mostly thought of the integration as an internal profiling tool, but I can see how it could be useful from client projects too. I'll take a look at it.

What do you think about the overloaded global new/delete operators, I guess this isn't a great idea to have enabled with external projects, or what are your thoughts?

For reference, its integration has also been discussed as part of: https://github.com/mikke89/RmlUi/pull/446#issuecomment-1714597648.

**Comment by p2004a** [comment]
(ops, sorry for a bit of spam caused by about tagging this issue in commit I amended a bunch of times)

> but I can see how it could be useful from client projects too. I'll take a look at it.

Thank you! We are very early in integration, and I don't know how zones-heavy is the library code but overall I hoped that having it on both places (and we also have enabled tracy lua integration so people can easily add zones from scripting side) can help paint a very detailed picture on where perf goes and get a better feeling about cost of certain things.

> What do you think about the overloaded global new/delete operators, I guess this isn't a great idea to have enabled with external projects, or what are your thoughts?

I think I would leave it to the projects, we currently already do [exactly the same thing in engine](
https://github.com/beyond-all-reason/spring/blob/87ccd01be8ef891528cc72a68b6344db8b641bcb/rts/System/TraceMemory.cpp#L4) but also [it's controlled by build option](https://github.com/beyond-all-reason/spring/blob/87ccd01be8ef891528cc72a68b6344db8b641bcb/rts/lib/CMakeLists.txt#L85) because it can get pretty heavy to profile all memory allocations in our case, and it's disabled in our default profiling enabled builds.

Thanks for linking that PR!

**Comment by mikke89** [comment]
Just made a new pull request #518 attempting to resolve this one, could you test and review? :)
