### ISSUE TITLE
Wrong mouse positions with GLFW GL2/GL3 on macOS

### ISSUE THREAD

**Issue by NaLiJa** [mikke89/RmlUi#521]
(Thanks a lot for your work with RmlUi, I have just learned about it and I am fascinated!)

When using RmlUi on macos Ventura with GLFW (either GL2 or GL3), I am seeing the strange effect that mouse corrdinates are wrong. See in the image, I have to click at the position with the red star to activate the Highscore button.
This does only happen with the GLFW backend, SDL is not affected. Printing out the positions to the console, it seems that there is somehow a factor of ~2 applied somewhere to the coordinates. And in fact if I change this in RmlUi_Platform_GLFW:
```
bool RmlGLFW::ProcessCursorPosCallback(Rml::Context* context, double xpos, double ypos, int mods)
{
	std::cout << "Pos x=" << xpos <<" y=" << ypos << "\n";
	if (!context)
		return true;

	bool result = context->ProcessMouseMove(int(xpos*2), int(ypos*2), RmlGLFW::ConvertKeyModifiers(mods));
	return result;
}
```
the problem is fixed, although I am quite sure that it can't be that simple. Do you perhaps have any idea where this factor 2 originates? Is it perhaps a matter of Retina/non-Retina-display? I am not sure if this is eventually happening in RmlUi or in Glfw (sorry, I am new to both frameworks, so that is not so easy to track)
<img width="568" alt="mouse_pos_error" src="https://github.com/mikke89/RmlUi/assets/9607773/f6bd524a-ee4a-4c6f-b62d-833d872cddab">

Thanks for helping and your great work!

**Comment by mikke89** [comment]
Thanks for the kind words and descriptive issue!

Yeah, this sounds very much like a retina thing. We are probably mixing framebuffer coordinates and window coordinates. Don't remember exactly how it worked in glfw, but I'll have a better look at it.

**Comment by NaLiJa** [comment]
Thanks for the fast reply! Yes, indeed it seems like a problem with a window/framebuffer mismatch. This is what I have (and this also explains the factor nof 2)

Windows size - width=1024 height=768
Framebuffer size - width=2048 height=1536

The coordinates I get for the mouse seem to be targeted tom the window size. The red star has the corrdinates ~900/~500. The BoxArea of the Highscore button has matching extends. Actually tzhese coordinates look right in relation to the framebuffer size, but they are applied to the window size. Wish I could be of more help!

**Comment by mikke89** [comment]
I made an attempt at fixing this, but I'm not able to test it on macOS. Can you try the above commit and report back?

Indeed, we were lacking a conversion between GLFW screen coordinates and pixel coordinates which RmlUi assumes. On several platforms, including Windows, these always map 1:1, but not on all platforms, and the correctness without this conversion also depends on dpi-ratio.

More details are found in the [GLFW documentation](https://www.glfw.org/docs/3.4/intro_guide.html#coordinate_systems), in particular:

> Pixels and screen coordinates may map 1:1 on your machine, but they won't on every other machine, for example on a Mac with a Retina display. The ratio between screen coordinates and pixels may also change at run-time depending on which monitor the window is currently considered to be on.

**Comment by NaLiJa** [comment]
Unfortunately it doesn't work yet. It almost seems as it should be the other way around from framebuffer coordinates to screen coordinates. From your solution I get this:
Pos x=856.435 y=739.033
New pos x=428 y=370

For testing I changed this in RmlUi_backend_GLFW_GL3.cpp yesterday and it seems to fix the problem:
	// Mouse input
	glfwSetCursorPosCallback(window, [](GLFWwindow* /*window*/, double xpos, double ypos) {
		float dp_ratio = 1.f;
		glfwGetWindowContentScale(data->window, &dp_ratio, nullptr);
		RmlGLFW::ProcessCursorPosCallback(data->context, xpos*dp_ratio, ypos*dp_ratio, data->glfw_active_modifiers);
	});

Now if I adapt this to your new commit I have to apply the ratio twice, to fix it again :)
So , if I do this with your latest commit
RmlGLFW::ProcessCursorPosCallback(data->context, window, xpos*dp_ratio*2, ypos*dp_ratio*2, data->glfw_active_modifiers);
It works:
Pos x=1502.78 y=2944.18
New pos x=751 y=1472

Thanks again for your kind help! Also send a small PR for fixing GL3 on macos.

**Comment by NaLiJa** [comment]
I had another look into your commit. Indeed if I replace
`const Vector2d mouse_pos = Vector2d(xpos, ypos) * (Vector2d(window_size) / Vector2d(framebuffer_size));`
with
`const Vector2d mouse_pos = Vector2d(xpos, ypos) / (Vector2d(window_size) / Vector2d(framebuffer_size));`
it seems to work as expected!

**Comment by mikke89** [comment]
Yeah, seems like I flipped the ratio as I suspected in my previous post edit, ops. I believe you accidentally forgot to fill in the change in the previous post.

Can you test this new commit again? Thanks.

**Comment by NaLiJa** [comment]
Fantastic! Seems to work s intended now! Thanks!

**Comment by mikke89** [comment]
Glad to hear that!
