### ISSUE TITLE
[Freetype] LNK1107

### ISSUE THREAD

**Issue by skaarj1989** [mikke89/RmlUi#529]
Caused by `${FREETYPE_LIBRARIES}` which equals to `vcpkg\installed\x64-windows\debug\bin\freetyped.dll`
https://github.com/mikke89/RmlUi/blob/d3876e62fb7a0aa0630272f27ac83ef1c67b01c5/CMakeLists.txt#L391C3-L391C52

This can be fixed by using:
`target_link_libraries(main PRIVATE Freetype::Freetype)`

I'm not sure if this should be fixed in **RmlUi** or in **vcpkg**.

**Comment by skaarj1989** [comment]
Looks like CMake 3.28 error.
https://github.com/microsoft/vcpkg/issues/34725

**Comment by mikke89** [comment]
Nice, thanks for following this up in upstream projects.
