### ISSUE TITLE
animation-timing-function steps

### ISSUE THREAD

**Issue by Paril** [mikke89/RmlUi#536]
I'm trying to do a sprite-based animation - which I'm surprised isn't talked about in the docs anywhere since it seems pretty fundamental to most game-based UIs - where it just plays a sequence of images as one single element. I considered just writing a custom element for it, which might be the better approach (although it's all separate images rather than a sheet in my case), but let's assume I wanted to do it in pure CSS - with CSS3 I could use the `animation-timing-function` `steps`, which ensures that it displays each image for the correct amount of time. Is this something that can be done in RMLUI currently? I'm using `linear` and it seems like it's incorrect timing-wise.

**Comment by Paril** [comment]
I ended up moving to a sub-discussion since I think it's a bit less of a feature request/bug report; https://github.com/mikke89/RmlUi/discussions/338

It's around the same issue, though. I think you're right, steps may not be required since linear can technically do it with a decorator, although somebody might find `steps` helpful for other use-cases?

**Comment by mikke89** [comment]
Sounds good. Yeah, `steps` might be useful, but let's wait for someone to have a specific use case for it :)
