### ISSUE TITLE
Documentation errors on Decorators

### ISSUE THREAD

**Issue by Paril** [mikke89/RmlUi#537]
The documentation appears to be incorrect here:

https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/decorators.html#defining-the-decorators-properties

`properties` is a private member, I assume it should be calling the protected functions. It also references "documentation on registering custom properties" but does not link to it, and I can't find such a thing in the rest of the documentation. Closest I can find is https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/rcss.html#defining-custom-properties but that appears to be something else.

`RegisterProperty` appears to not take a third argument any more (moved to shorthand type maybe?)
`RegisterShorthand` appears to take an additional argument that isn't explained in the docs.

**Comment by mikke89** [comment]
Hey, thanks for letting me know. The documentation was a bit out-of-date here, I've made some changes now, hopefully that should clear things up.

**Comment by Paril** [comment]
Cool! I think the parameters might still be out of date (ie `RegisterProperty`) but thanks for taking a look; I can throw more things in here if I come across any.

**Comment by mikke89** [comment]
Nice. If you come over some smaller things that can be improved, feel free to make a quick PR. You can make edits directly on GitHub.

The four parameters should be correct for the `StyleSheetSpecification::RegisterProperty` function which is considered in the custom properties documentation. This one is slightly different from the decorator properties, or rather, not all the parameters are appropriate for decorator properties, so they are omitted from `DecoratorInstancer::RegisterProperty`. I understand that it's not obvious that there are two different functions being described here.
