### ISSUE TITLE
How to use the rmlui rich text editor? Is there a suitable approach?

### ISSUE THREAD

**Issue by zsea** [mikke89/RmlUi#538]
I want to implement a rich text editor. I know that in a browser, we can use contentEditable to enable the editing state of an element, but there is no such attribute in rmlui. Is there any other way to achieve this?

**Comment by mikke89** [comment]
Hi. Sure, this will certainly be quite some effort, but the only proper way to implement rich text editing would be to create a custom element. I'd encourage you to take a look at the `WidgetTextInput` class, and work your way out from there. Let me know if I can answer any questions.

Good luck, and let us know how it goes!

**Comment by zsea** [comment]
Thanks, I'll give it a try.
