### ISSUE TITLE
Element::GetProperty<T> isn't safe

### ISSUE THREAD

**Issue by viciious** [mikke89/RmlUi#56]
```template < typename T >
T Element::GetProperty(const String& name)
{
	const Property* property = GetProperty(name);
	RMLUI_ASSERTMSG(property, "Invalid property name.");
	return property->Get< T >();
}
```

The code should also check for `property` not being `nullptr` after the assert because `RMLUI_ASSERTMSG` expands to nothing in release builds, and if `property` is a `nullptr` indeed, the program will crash with segmentation fault.

**Comment by mikke89** [comment]
Yeah, I agree this function should be safe.

**Comment by viciious** [comment]
Thanks!
