### ISSUE TITLE
`selectbox` does not automatically scroll options into view when using spatial navigation

### ISSUE THREAD

**Issue by Paril** [mikke89/RmlUi#565]
When arrows are used to select options, it will select options outside of the purview of the scroll area. I managed to 'patch' this with an event handler on `change` and using the following:

```
select->GetOption(select->GetSelection())->ScrollIntoView(Rml::ScrollIntoViewOptions { Rml::ScrollAlignment::Nearest, Rml::ScrollAlignment::Nearest });
```

this seems to do what you'd expect, where it always keeps the selected option visible but does not snap it to the top or bottom as you scroll. Not sure if this should just be shoved back into the main element code or if I'm maybe missing something.

It also makes me wonder if I'm going to run into the same issue when using a generic scrollable area with navigable elements inside of it, but I'll handle that as it comes up :)

EDIT: it also does not scroll the selected option into view automatically. still working on that one

**Comment by mikke89** [comment]
This one has been fixed with #566, thanks!
