### ISSUE TITLE
`body` size gets automatically calculated even if explicitly specified

### ISSUE THREAD

**Issue by Paril** [mikke89/RmlUi#569]
In HTML, the `body` element by default fills the entire viewport regardless of its contents; in RML, however, it seems like the body element ignores any explicit sizing and just fits to whatever its contents are.

I'm basically trying to use the body as the 'background' element, slap an image on it, and render the inner menu as an element with automatic margins; currently it seems like the only way to accomplish this is to have an inner div that fills the entire viewport, and then have my menu inside of that, which is doable but might be confusing coming from HTML where the body element can be given explicit sizing. I don't really see it mentioned anywhere either about sizing on body, unless I missed something.

**Comment by mikke89** [comment]
To make the body fill the whole viewport, you can e.g. use the style rule `body { top: 0; right: 0; bottom: 0; left: 0; }`.

In RCSS, unlike CSS, the body is absolutely positioned within the context. So, just think of it like any other absolutely positioned element and position it accordingly. It is mentioned in [the documentation here](https://mikke89.github.io/RmlUiDoc/pages/rcss/visual_formatting_model.html), however, it's possible that it could be better emphasized. Let me know if you have some suggestions.

You should be able to give an explicit size to the body element. I'm not sure what that is about, could you give some examples? Maybe you're specifying an overconstrained set of size (width/height) and inset properties (top/right/bottom/left)?

**Comment by Paril** [comment]
So basically what I have is something like this:

```
body
{
width: 100%;
height: 100%;
}

body .window
{
width: 240dp;
height: 320dp;
}
```

The viewport is set to the size of the resolution (say, 1920x1080). For some reason, the body only ends up consuming the 240x320 space.

**Comment by Paril** [comment]
Okay, now that I attempt this again, it seems like suddenly it's now working properly - I'm not sure what I had done wrong the first time around. If I manage to repro this again I'll open an issue with a minimal example, sorry!

**Comment by mikke89** [comment]
Hm, yeah, it's certainly not supposed to do that, and I cannot reproduce it here.

No worries, let us know if you can reproduce it.
