### ISSUE TITLE
Hiding an element should remove it from the focus tree

### ISSUE THREAD

**Issue by viciious** [mikke89/RmlUi#57]
This is somewhat a continuation of issue #40. Consider the following scenario:

1. A document is shown and it has a bunch of elements with the "autofocus" attribute.
2. The first element is focused as it should.
3. The OnShow script then decides it doesn't want that first element to be displayed and hides by setting "display" to "none".
4. Pressing ENTER will result in a click event on the hidden element.

**Comment by mikke89** [comment]
Does this work for you?

**Comment by viciious** [comment]
Yes, sort of. The next question is, should, in case of such event, the next autofocus element be focused?

**Comment by mikke89** [comment]
I don't know. What do web browsers do? It's not really something I want to spend time on :P

**Comment by viciious** [comment]
You're right, let's keep it the way it is.

**Comment by mikke89** [comment]
Cool :) I guess we can consider this fixed then.
