### ISSUE TITLE
Remove namespace Core, Debugger, Controls

### ISSUE THREAD

**Issue by mikke89** [mikke89/RmlUi#58]
Usage of RmlUi would be a lot simpler if we removed the sub-namespaces. I don't feel like they are really necessary.

Thus,
```cpp
Rml::Core::Element* element;
Rml::Controls::ElementFormControl* control_element;
Rml::Core::Log::Message(Rml::Core::Log::LT_WARNING, "...");
```
would become
```
Rml::Element* element;
Rml::ElementFormControl* control_element;
Rml::Log::Message(Rml::Log::LT_WARNING, "...");
```

We may need to keep the namespaces for some functions, so this stays the same:
```
Rml::Core::Initialise();
Rml::Controls::Initialise();
```
or, maybe remove it for core?
```
Rml::Initialise();
Rml::Controls::Initialise();
```
I haven't tried it to see if there are any name conflicts, but worst case is we need to do some renaming.

Thoughts?

**Comment by viciious** [comment]
It took me 40+ commits to move from libRocket to RmlUi, I'd rather prefer it to remain stable for a while :P

**Comment by mikke89** [comment]
Yeah, you have a point there. Okay, I'm putting this off for some time. Maybe for RmlUi 4.0 ;)

**Comment by uniquejack** [comment]
I do agree with @viciious , it's not easy to keep up with the huge amount of commits, but at the same time, I think the Controls namespace is useless. When one wants to use RmlUi they want to use the whole library, controls included. There is no need to do multiple Initialisations (I almost forgot I had to recently). The only module that doesn't require to be initialised is the Debugger, so probably the only namespace I suggest to leave unchanged is that one.

**Comment by viciious** [comment]
Do we even need the separate Controls lib at all? It has always bugged me that I need to compile two libs to get the most basic things working.

**Comment by uniquejack** [comment]
Yeah, an unique library would be optimal, I always compile them together when I setup my Visual Studio Projects. The only problem is that there are multiple .cpp files with the same name, that's probably the reason why they got separated in the first place.

**Comment by mikke89** [comment]
Yeah, integrating the Controls library into Core is very tempting, I don't see many people having the need for the library without it. On the other hand, it helps a bit with navigating the code, and also forcing a well defined separation of principles (ie. Core not depending on Control elements).

I think removing the Core and Controls namespaces would go a long way in making it easier and more comfortable to use the library.

**Comment by mikke89** [comment]
See e9844e3801079b6624c12dde1958b1e55a891bc7. I decided to merge the Controls library. Let me know if you have any comments before I merge into master.

Se the detailed changes here: https://github.com/mikke89/RmlUi/blob/merge_controls/changelog.md#restructuring-rmlui.
