### ISSUE TITLE
[Effects branch] box-shadow Asserts with No converter specified 

### ISSUE THREAD

**Issue by JailbreakPapa** [mikke89/RmlUi#590]
Not sure if the effects branch is still being maintained, but testing it with the demo in sandbox, seems to cause an assertion:
![image](https://github.com/mikke89/RmlUi/assets/67095081/8112cc74-1d4d-4fd7-a3fb-a199b332e877)

**Comment by mikke89** [comment]
I intend to make a pull request for the effects branch soon, in the mean time it shouldn't really be considered production ready. In any case, I'll take a look at this. It would be very helpful if you could list the RML and RCSS used here so I can reproduce it.

**Comment by JailbreakPapa** [comment]
No problem, i was mainly looking at the effects branch to just test out and build upon in a private fork of the library.

The HTML + CSS Code is adapted from [https://uiverse.io/ZacharyCrespin/dull-dragonfly-23](UIVerse) Just to give some context.

HTML:
`<button>Button</button>`

CSS:
`button {
  transition: all 0.5s;
  font-size: 17px;
  padding: 1ch 2ch;
  background-color: white;
  color: #000;
  border: none;
  border-radius: 2px;
  box-shadow: 2px 2px 0px,
   #00ff 4px 4px 0px,
   #00ff 6px 6px 0px,
   #00ff 8px 8px 0px,
   #00ff 10px 10px 0px,
    #00ff 12px 12px 0px,
    #00ff 14px 14px 0px,
    #00ff 16px 16px 0px,
   #00ff 18px 18px 0px inset;
}

button:hover {
  background-color: black;
  color: #fff;
  box-shadow: none;
}`

**Comment by mikke89** [comment]
I pushed a commit that I believe should fix this, let me know how it works for you.

**Comment by JailbreakPapa** [comment]
> I pushed a commit that I believe should fix this, let me know how it works for you.

About to test, currently building.

**Comment by JailbreakPapa** [comment]
Yep that seemed to fix it. Quick question, I know the given CSS was very broken in a way, but it seems the box shadows cant be interoplated? is it just the broken CSS or is that a limitation?

**Comment by mikke89** [comment]
Alright, good to hear! About interpolation: It just hasn't been implemented yet for box-shadow.

**Comment by JailbreakPapa** [comment]
> Alright, good to hear! About interpolation: It just hasn't been implemented yet for box-shadow.

Ill see if i can get interpolation working for box-shadow, and make a Quick PR.
