### ISSUE TITLE
CSS Custom Properties

### ISSUE THREAD

**Issue by JailbreakPapa** [mikke89/RmlUi#592]
TLDR; title. 

CSS Custom Properties are very useful despite not being a CSS 2 or 3 spec, and can help with getting a applications look down faster. 

[MDN Reference](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascading_variables)

**Comment by mikke89** [comment]
Thanks for the suggestion. This one has already been suggested in #517, so I'm closing this as a duplicate.
