### ISSUE TITLE
C Bindings, Arrays and Structs

### ISSUE THREAD

**Issue by enesaltinkaya** [mikke89/RmlUi#599]
Hi, I managed to make most of RmlUi work on my C project, by wrapper functions like these;

``` c
void rmlInitOpenGL(RmlInput* crmlui);
void* rmlLoadDocument(const char* path);

void rmlBindFloat(const char* modelName, const char* bindName, float* pFloat);
void rmlBindInt(const char* modelName, const char* bindName, int* pInt);
void rmlBindCString(const char* modelName, const char* bindName, char* pString);

void rmlBindFunction(const char* modelName, const char* eventName, void (*fn)(const char*));
void rmlBindArray(const char* modelName, const char* bindName, int size);
void rmlRegisterTransformFunc(const char* modelName, const char* transformName, void (*fn)(int, int, char*));

void rmlUpdateDirtyAll(const char* modelName);
void rmlUpdateDirtySingle(const char* modelName, const char* bindName);

void rmlRenderOpenGL(void);
void rmlDestroy(void);
```

But I'm having trouble with array of structs. Since I cant use templates on C side.

What I was able to do was, 
* Register an std::vector<int> for indices only
``` c
Rml::DataModelConstructor constructor = getConstructor(modelName);
constructor.RegisterArray<std::vector<int>>();
```
* Registering a Transform Function taking indices as argument, and calling C function "fn" with these indices.
```c
// c++ side
void rmlRegisterTransformFunc(const char* modelName, const char* transformName, void (*fn)(int, char*)) {
  Rml::DataModelConstructor constructor = getConstructor(modelName);

  constructor.RegisterTransformFunc(transformName, [fn](const Rml::VariantList& arguments) -> Rml::Variant {
    int index = arguments[0].Get<int>();
    char result[10] = {};
    fn(index, result);
    return Rml::Variant(Rml::CreateString(10, "%s", result));
  });
}

// c side
void systemInfo(int index, char* out) {
  sprintf(out, "%s", ecs.systems[index]->name);
}

void init(void) {
  rmlBindArray("statsModel", "systems", array_size(ecs.systems));
  rmlRegisterTransformFunc("statsModel", "systemInfo", systemInfo);
}
 
```
* And using it like this
```html
<div class="row spaceBetween" data-for="systems">
  <div class="column"><span>{{systemInfo(it_index)}}</span></div>
  <div class="column"><span>{{systemInfo(it_index)}}</span></div>
</div>
```

But the transform function "systemInfo" is only called once at the start.
And not called when I call DirtyVariable() on "systems" array or when I call DirtyAllVariables().

I thought of replicating the structs I'm planning to use on c++ side but that wouldn't be so dynamic.
And maybe looping my C array and using _Rml::ElementPtr CreateElement(const Rml::String& name);_ but that wouldn't be so performant I imagine.

Any ideas on how i can solve this?
Sorry for using here for asking support, if this is not appropriate we can close this issue.

**Comment by enesaltinkaya** [comment]
I made it work :)

I changed the rml part like this;

```html
<div class="row spaceBetween" data-for="it,it_index:systems">
  <div class="column"><span>{{systemInfo(it_index, it)}}</span></div>
  <div class="column"><span>{{systemInfo(it_index, it)}}</span></div>
</div>
```
I'm sending the "it" variable into systemInfo transform function eve though I'm not using it inside.
This way when i call DirtyVariable(), transform function is called again and values are updated.

Thanks for this awesome library!

**Comment by mikke89** [comment]
Hey, thanks for stopping by, and for the kind words. Glad to hear you managed to find a solution.

I know some users are interested in C bindings. It would be very cool if you would consider making them open source once they are mature. If you do that, let me know and I'll make sure to link it under the thirdparty resources.

**Comment by enesaltinkaya** [comment]
I made so many little changes to these, it wouldn't make sense to publish;
```  c
Rml::SetFileInterface(rmlFileHandle);
Rml::SetSystemInterface(rmlGLFWHandle);
Rml::SetRenderInterface(rmlGL3Handle);
```
That said I would be happy to help out anyone having trouble using RmlUi with C.

And while you are here a very quick question :)
Does data-for in rml files work for only arrays registered? 
Can we use index based loops, like regular for loops?
I could not find anything related on the docs.

**Comment by mikke89** [comment]
Alright, sounds good.

As for your questions: Yes, `data-for` only works for registered arrays, and only supports range-based loops.
