### ISSUE TITLE
RmlUi GLFW3 (Vulkan) causes amgpu driver crash

### ISSUE THREAD

**Issue by niansa** [mikke89/RmlUi#600]
On Debian Trixie with an AMD RX 5700 XT, the following code snippet causes a crash of the `amdgpu` driver when running with the GLFW3 Vulkan backend/renderer:

    if (!Backend::Initialize("Title", 1920, 1080, false)) {
        return;
    }

    Rml::SetSystemInterface(Backend::GetSystemInterface());
    Rml::SetRenderInterface(Backend::GetRenderInterface());

    Rml::Initialise();

    auto ctx = Rml::CreateContext("main", Rml::Vector2i(1920, 1080));

    Rml::LoadFontFace("documents/LatoLatin-Regular.ttf");
    auto doc = ctx->LoadDocument("documents/Home/index.rml");
    doc->Show();

    while (true) {
        Backend::ProcessEvents(ctx);
        doc->UpdateDocument();
        ctx->Update();
        Backend::BeginFrame();
        ctx->Render();
        Backend::PresentFrame();
    }

![image](https://github.com/mikke89/RmlUi/assets/20720267/22fbcd38-036b-4f1b-9733-8506fd502df6)

**Comment by wh1t3lord** [comment]
Can you compile in debug with RMLUI_VK_DEBUG (uncomment preprocessor)? Mostly we tested on nvidia videocards I don't know what could be wrong with AMD.  https://github.com/mikke89/RmlUi/blob/master/Backends/RmlUi_Renderer_VK.h#L83C2-L83C27

@niansa 

And which version of RmlUI do you use?

**Comment by mikke89** [comment]
Ouch, this pattern looks a lot like a dying GPU :/ You don't happen to be overclocking it? I'm sure it could also be a driver issue, and perhaps in combination with something we do. Enabling debug output and validation layers (as mentioned above) would be very helpful.

Did you try any other backends?

**Comment by niansa** [comment]
I'm on version `23b93483c576776c04f8eb7d221b0b0b4ad392bd`. I have also tried the GLFW GL3 backend, but only got a black screen with that.
I will get you more info as requested later when I'm on my PC.

**Comment by wh1t3lord** [comment]
@niansa can you test on current master branch please?

**Comment by niansa** [comment]
Here's a debug log:

```
Loaded font face 'LatoLatin' [regular] from 'documents/LatoLatin-Regular.ttf'.
Rml width: 3840 height: 2160 | Vulkan width: 3840 height: 2160
can't be, you must have a valid count that bounds from minImageCount to maxImageCount! Otherwise you will get a validation error that specifies that you created a swapchain with invalid image count
/home/nils/Programs/OSS/QSysLib/RmlUi/Backends/RmlUi_Renderer_VK.cpp:1782
can't be, you must have a valid count that bounds from minImageCount to maxImageCount! Otherwise you will get a validation error that specifies that you created a swapchain with invalid image count
/home/nils/Programs/OSS/QSysLib/RmlUi/Backends/RmlUi_Renderer_VK.cpp:1785
```

**Comment by niansa** [comment]
Oops

**Comment by wh1t3lord** [comment]
@niansa did you have VK_ICD_FILENAMES= thing?

**Comment by wh1t3lord** [comment]
@niansa you need to paste all information what vulkaninfo writes. It is important to understand on which side the problem, because if vulkaninfo doesn't print a valid information about your videocard that means it is driver's problem and you need to choose different version of drivers or just reinstall them.

**Comment by niansa** [comment]
Okay, here's something interesting. I had `libglfw3-wayland` installed instead of the normal X11 package. Installing the X11 package fixed the issue! Is there a known problem with GLFW3 wayland?

[vulkaninfo.txt](https://github.com/mikke89/RmlUi/files/14628804/vulkaninfo.txt)

**Comment by wh1t3lord** [comment]
@niansa I dont know do you install glfw with Wayland support?

**Comment by mikke89** [comment]
@niansa Which version of GLFWare you using? The most recent one (3.4) has several changes and fixes for Wayland in particular. Could you try that? Also would be interesting if you could test the `SDL_VK` backend with Wayland to see if that makes a difference.

**Comment by niansa** [comment]
Debian Trixie provides version 3.3.10, so that's what I'm using.
SDL Vulkan seems to be running with Wayland right out of the box and with no apparent issues.

**Comment by wh1t3lord** [comment]
Any reason for keeping this issue as opened?

**Comment by mikke89** [comment]
@niansa I would encourage you to test this on GLFW 3.4 and report back. In the meantime, it seems likely to be an issue outside the library, so I am closing this one.
