### ISSUE TITLE
SetDensityIndependentPixelRatio does not cause a change with GLFW3 GL3

### ISSUE THREAD

**Issue by niansa** [mikke89/RmlUi#602]
Hi. Currently trying to figure out if I can target devKitPro (Switch) with RmlUi. And indeed! It works:

![image](https://github.com/mikke89/RmlUi/assets/20720267/1701f128-d1b3-4fca-b3ed-b295b0104e4c)

However, the DPI is clearly wrong. So I'm doing this:

    ctx = Rml::CreateContext("main", resolution);
    ctx->SetDensityIndependentPixelRatio(2.f);

However, there is no visible difference even with values like 20. What could be wrong here?

**Comment by mikke89** [comment]
Nice, cool to hear it working in that environment.

Please try using `dp` units instead of `px` units if you're not already doing that.

**Comment by niansa** [comment]
Yes, I'm already using `dp` units.

**Comment by mikke89** [comment]
Are you using our backend directly? Please note that this backend handles DPI-changes automatically, so please check that you're not being overridden by the built-in behavior. Otherwise, please provide a full reproducible so we can understand exactly what is being done here.

**Comment by niansa** [comment]
Yes, I am using the backend directly. Should I copy it into my own source tree to remove the DPI handling code?

**Comment by mikke89** [comment]
Yeah, that would be one approach. For testing you could also try setting the dp-ratio during your update loop.
