### ISSUE TITLE
Input elements display nothing on screen

### ISSUE THREAD

**Issue by jakerieger** [mikke89/RmlUi#609]
Maybe I'm missing something, but `input` elements display nothing on screen, regardless of type. I have a settings screen with the following markup:

```html
<table>
    <colgroup>
        <col span="2"/>
        <col/>
    </colgroup>
    <tbody>
    <tr>
        <td>V-Sync</td>
        <td><input type="checkbox" name="vsync" checked/></td>
    </tr>
    <tr>
        <td>Fullscreen</td>
        <td><input type="checkbox" name="fullscreen" checked/></td>
    </tr>
    <tr>
        <td>Resolution</td>
        <td>
            <select name="graphics">
                <option value="720">1280 x 720</option>
                <option value="900">1600 x 900</option>
                <option value="1080" selected>1920 x 1080</option>
            </select>
        </td>
    </tr>
    <tr>
        <td>Master Volume</td>
        <td><input type="range"/></td>
    </tr>
    <tr>
        <td>UI Volume</td>
        <td><input type="range"/></td>
    </tr>
    <tr>
        <td>Effects Volume</td>
        <td><input type="range"/></td>
    </tr>
    <tr>
        <td>Music Volume</td>
        <td><input type="range"/></td>
    </tr>
    </tbody>
</table>
```

The only thing displaying on screen is the select box (albeit with no style whatsoever, just text). There are no styles being applied to the input elements.

![missing input elements](https://github.com/mikke89/RmlUi/assets/19679090/973e1006-d174-46ac-a387-31c49afd3795)

**Comment by mikke89** [comment]
Hey there. There are no built-in styles in RmlUi, so you have to define them all yourself. Of course, feel free to take a look at our samples and tests.

See also the documentation, it documents how to style some of the built-in elements: https://mikke89.github.io/RmlUiDoc/pages/style_guide.html

**Comment by jakerieger** [comment]
I checked out the documentation you linked and it seems like spritesheets are how you're defining different element states. Is this the approach I would take for the checkbox? Use a spritesheet containing unchecked and checked sprites and just switch between them?

**Comment by mikke89** [comment]
You can style them however you'd like using normal RCSS rules, spritesheets just being one way. For more complex shapes, like a checkmark, a sprite does make a lot of sense though.

By the way, I figured the documentation page wasn't entirely clear, so I made some changes just now to improve the introduction of it.

**Comment by jakerieger** [comment]
Makes sense, I'm gonna close this as I should be able to figure it out from here. Figured I missed something in the docs and looks like I did. Thanks for the help!
