### ISSUE TITLE
 I noticed that there are other licenses in the folder, one of which mentions the GNU protocol. 

### ISSUE THREAD

**Issue by RIKDXHQ11** [mikke89/RmlUi#611]
Hello, I noticed that there are other licenses in the folder, one of which mentions the GNU protocol. I would like to ask if it requires my project to disclose the source code because we don't like infectious licenses and prefer to close the source code, which is why I chose MIT. If it forces us to disclose the source code of the project, then I can only choose the imgui of a single license. Thank you!

**Comment by mikke89** [comment]
Just to be clear, the library is licensed under MIT. We have some third-party dependencies included, but make sure that any of them are in the same spirit. In fact for the core library, only MIT licenses are used. For the debugger, there is an additional SIL open font license, that I would consider in the same spirit.

The only thing I can think of you referring to here is the the `tiger.svg` sample asset, which is licensed under the GNU AGPL. This is only an asset used for the SVG sample, there is no reason for applications using RmlUi to include that (and normally they would not).

Please see the [license section of the readme](https://github.com/mikke89/RmlUi?tab=readme-ov-file#license) as all the details are listed there.
