### ISSUE TITLE
Multiple css styles are not supported

### ISSUE THREAD

**Issue by yingnierxiao** [mikke89/RmlUi#614]
Syntax error parsing property declaration 'border: 1px solid #b37f1f;' in assets/index.rcss: 4819.
Syntax error parsing property declaration 'background: linear-gradient(180deg, #04ff2c, #00e124);' in assets/index.rcss: 4854.
Syntax error parsing property declaration 'text-shadow: 0.7px 0.7px 0.8px #000000;' in assets/index.rcss: 4877.
Syntax error parsing property declaration 'background: url(./assets/images/e924d99f186d1064c15e8eb83e136c7caa3987b9.png)    no-repeat center;' in assets/index.rcss: 4886.
Syntax error parsing property declaration 'background-size: cover;' in assets/index.rcss: 4887.

**Comment by yingnierxiao** [comment]
[rmlui-editor.zip](https://github.com/mikke89/RmlUi/files/15282033/rmlui-editor.zip)

**Comment by mikke89** [comment]
Hi. Did you take a look at the [documentation](https://mikke89.github.io/RmlUiDoc/index.html)? We don't support all of those properties (`text-shadow` in particular), or they work a bit differently. But we have alternatives for all of these. Our border syntax does not support style, you can just remove `solid` as all borders are solid in RmlUi. Look into decorators and font-effects for the other properties.

**Comment by mikke89** [comment]
I converted the ones you listed to get you started, these should give equivalent results:

```css
border: 1px #b37f1f;

decorator: vertical-gradient(#00e124 #04ff2c); /* In RmlUi 6 */
decorator: gradient(vertical #00e124 #04ff2c); /* In RmlUi 5 */

font-effect: glow(0px 1px 1px 1px #000);
decorator: image("./assets/images/e924d99f186d1064c15e8eb83e136c7caa3987b9.png" cover);
```

**Comment by yingnierxiao** [comment]
https://github.com/ultralight-ux/Ultralight There was more support for css, and there was no cross-platform support at the time. I think css needs more general support and is mostly exported by other software so it can be used more widely,thanks for you work.

**Comment by mikke89** [comment]
Thanks for your input. You are of course free to choose whichever library fits best for your case. We do not aim to be fully compliant with CSS or HTML, especially when it conflicts with lightness and performance. This is quite a bit different philosophy to Ultralight, which is based on an actual web engine (webkit).

But there are some cases where we possible could be more compliant. For example I've been tinkering with making decorators possible to set through the `background` property. This would make some effects, like gradient, work with the same syntax as in CSS.

**Comment by mikke89** [comment]
Doing some cleanup of old issues. I am closing this one due to lack of activity, and as I consider it general feedback. Thanks for your input!
