### ISSUE TITLE
The default GLFW GL3 backend yields weird display

### ISSUE THREAD

**Issue by Dich0tomy** [mikke89/RmlUi#618]
Hello. I am trying to use the default GLFW GL3 backend, but the window I'm getting doesn't seem to be updating properly, and it captures the background and then stays still:

![image](https://github.com/mikke89/RmlUi/assets/75364377/2bc1027d-0d07-40ad-a771-419a961e2e96)

Here's the repro: https://github.com/Dich0tomy/repro
It has a flake which is buildable and runnable, but you can also just do
```
meson setup compile
meson compile -C build
```

I'm not sure what I'm doing wrong, especially since building your examples produces the desired output:
![image](https://github.com/mikke89/RmlUi/assets/75364377/c9c9dcdc-e9ef-4175-9d54-fc6972fc32cd)

Any help is appreciated.

**Comment by mikke89** [comment]
Hey there.

Based on you main.cpp file, it looks like you're game loop is missing both event processing and frame setup / present. Compare it to the `loaddocument` sample:

https://github.com/mikke89/RmlUi/blob/c84ed5de7877c467ca43abd9095f8dedeb92255b/Samples/basic/loaddocument/src/main.cpp#L82-L97

**Comment by Dich0tomy** [comment]
Indubitably that works! Stupid me for not reading the samples carefully enough, my bad.. While I'm here - the window is displayed in such a manner, that I can resize it and the rendered document doesn't resize with it:

1. What if I wanted to make a window that doesn't resize
2. What if I wanted to make a window that resizes but the document resizes with it?

If answer to these is somewhere in the docs, just say so, I'll find it later, but I am assuming it may be because of the fact I'm using a TWM, they typically tend to mess with windows a lot.

**Comment by mikke89** [comment]
What we provide in terms of windowing is intentionally very basic. You should provide your own keyboard shortcuts and so on, to fit your needs. Our samples demonstrate some keyboard shortcuts, so be sure to check out the Shell and individual samples.

To allow resizing or not, you'll notice that there is a boolean in `Backend::Initialize` for that exact purpose. But more to the point, check the GLFW documentation for more detailed window controls, and change the backend to your needs.

Some of our samples are resizable, some are not. Some of the sample documents scale to the window when that changes size, others do not. This is controlled by the combination of window settings and RCSS. For example, use top/right/bottom/left RCSS properties to make a document scale relative to the window edges. The document is really just an absolutely positioned RML element, so just keep that in mind and make your layout rules accordingly.

**Comment by Dich0tomy** [comment]
Thanks a lot!
