### ISSUE TITLE
Support for Modulus operation in expressions

### ISSUE THREAD

**Issue by YTN0** [mikke89/RmlUi#622]
Tried to do a modulus in an expression, and realized this isn't supported (via the error, and from looking at the docs).

Is there a reason this isn't currently supported?

**Comment by mikke89** [comment]
The data expressions are by design very simple and minimal. Instead, you can extend them with the functionality you need using [transform functions](https://mikke89.github.io/RmlUiDoc/pages/data_bindings/expressions.html#transform-functions).

**Comment by YTN0** [comment]
Thanks. That was easy enough to do.

One issue I ran into was assuming that the custom functions were specific to the current data model, but that doesn't seem to be the case I.e it's global to all.

I'm wondering if it makes sense to split that out into a separate class that makes that clearer.

I guess it doesn't really matter too much.

**Comment by mikke89** [comment]
Glad to hear!

Yeah, that's good feedback, I agree the API could have been separated a bit better in this aspect. I'm not sure if it's worth changing right now though.
