### ISSUE TITLE
Using glEnable(GL_DEPTH_TEST) when using GL3 renderer and SDL platform results in blank screen.

### ISSUE THREAD

**Issue by ben-metzger-z** [mikke89/RmlUi#626]
Hi!
I have been trying to integrate RmlUi into my codebase using the GL3 renderer (with GLES3) and SDL platform and kept getting a blank screen when rendering. I found the issue was where I was calling glEnable(GL_DEPTH_TEST) for my code. I understand that the depth testing may interfere with the layering of RmlUi, but as it was an annoying issue to track down I was wondering if this could be better handled? Other enable/disable attributes seem to have their state saved in RenderInterface_GL3::BeginFrame() and then restored in EndFrame() so could the same be done here for GL_DEPTH_TEST? Thanks ! :)

**Comment by mikke89** [comment]
Hey!

Yes, it sounds perfectly reasonable to add the depth test, especially considering that it is a fairly popular thing to use.

Currently, we have mainly added things to this list for state that we modify ourselves, depth testing not being one of them. Generally, I don't think we want to set *all of* the GL state before (and after) we render, there is just too much of it. But I think it is reasonable for such widely used features like depth testing. An alternative is to just have a debug check for it, and issue an error if the user doesn't configure the state correctly according to our assumptions, at least that should make it much easier to debug. For now, I am happy with either solution.

Could you make a pull request with this change? :)
