### ISSUE TITLE
source code of a game in the rmlui's galery 

### ISSUE THREAD

**Issue by Grise3** [mikke89/RmlUi#628]
Hello, in the RmlUI's galery ( https://mikke89.github.io/RmlUiDoc/pages/gallery.html ) 

there is that : 

https://mikke89.github.io/RmlUiDoc/pages/animations/game_main_menu.webm

where can we have the source code of this?

**Comment by mikke89** [comment]
Hey there, the source code for that project is not available, so you'll have to find some other way to recreate this.

**Comment by Grise3** [comment]
Ok, thanks. I wanted to see how the "screenmanager" is done

**Comment by mikke89** [comment]
Right. The logic for the menu transitions should be relatively simple. It's mainly showing and hiding documents, and setting a few classes on the documents.

**Comment by Grise3** [comment]
OK :) will search
