### ISSUE TITLE
Document window failed to auto scale after moving

### ISSUE THREAD

**Issue by AdjWang** [mikke89/RmlUi#637]
## The issue
The demo program `rmlui_sample_demo.exe` shows a responsive document window auto scaling with the main window. The auto scaling would not work if drag and move it somewhere.

## How to reproduce
```
vcpkg install freetype glfw3
git clone https://github.com/mikke89/RmlUi.git
cd RmlUi
cmake -B Build -S . --preset samples -DRMLUI_BACKEND=GLFW_GL3 -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
cmake --build Build
```

```
git log -1
commit 51af29b1b34c3d8c6b1790385e6584f004cfe3a9 (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Ragazzon <michael.ragazzon@gmail.com>
Date:   Sun Jul 14 18:24:36 2024 +0200

    Defer scroll offset clamping to after layout, fixes #452
```
- Execute `./Build/Debug/rmlui_sample_demo.exe` -> maximize window => works fine
![no_drag](https://github.com/user-attachments/assets/4052930d-a2dc-4fa0-9324-a912fd894a71)

- Execute `./Build/Debug/rmlui_sample_demo.exe` -> drag the document window somewhere -> maximize window => the document window is not scaling
![step1](https://github.com/user-attachments/assets/ecbdbe40-1098-4de6-9470-70684f3d7e05)
![step2](https://github.com/user-attachments/assets/5a051fb9-49c3-4cae-a56a-30a0225bbafc)

**Comment by mikke89** [comment]
Ah yes, this is really just how the handle element currently behaves, but I understand it might not be what one expects. When moving an element, the handle fixes the target's size, so that it doesn't accidentally resize it too. Hm, we could perhaps be smarter about how we do this though. Maybe it's fine to keep the `right` and `bottom` properties, but just adjust them accordingly so it doesn't change in size. I'll tinker a bit on it.

**Comment by AdjWang** [comment]
Ok, thanks for consideration. I think maybe separate them in different way? Like in web, an out-of-flow window uses absolute position and sets left, top, right and bottom to move and scale; a in-flow window uses margin in px and width and height in percent to move and scale. The out-of-flow window never scale with the outer container while the in-flow one does.

**Comment by mikke89** [comment]
Hey, I've pushed several changes now on how the handle element operates. Check it out on the master branch, and let me know if you have any feedback.

In particular, we now respect the anchoring to each edge, even after moving and sizing the target element through the handle. Which should resolve this issue.

In addition, we now automatically constrain the area that the target can be dragged in to its containing block. This can be further be customized with the new `edge_margin` attribute.
