### ISSUE TITLE
Flex formatting context triggered unexpected assert initial_box_size.y < 0

### ISSUE THREAD

**Issue by AdjWang** [mikke89/RmlUi#640]
Hi, I encountered an assertion stops interpreting the flex style, I'm not sure whether this is a bug.

Here's a minimal code snippet to reproduce the issue. Replace `Samples\tutorial\template\data\tutorial.rml` content as follow:
```
<rml>
<head>
	<title>Window</title>
	<style>
		body {
			font-family: LatoLatin;
			left: 0;
			top: 0;
			height: 768px;
			width: 100%;
		}
		#dialog {
			display: flex;
			width: 100%;
			height: 100%;
			justify-content: space-between;
		}
		#background {
			flex-direction: column;
			flex-grow: 1;
			width: 100%;
			height: 100%;
			border: 1px;
		}
		#sidebar {
			position: relative;
			width: 100px;
			height: 100vh;
			display: flex;
			flex-direction: column;
			border: 1px;
		}
		#temp-img {
			width: 10px;
		}
	</style>
</head>
<body>
	<div id="dialog">
		<div id="background">bkg</div>
		<div id="sidebar">
			<img id="temp-img" src="../../../assets/alien_small.tga" />
		</div>
	</div>
</body>
</rml>
```

The `rmlui_tutorial_template.exe` triggeres an assertion `RMLUI_ASSERT(initial_box_size.y < 0.f);`
https://github.com/mikke89/RmlUi/blob/51af29b1b34c3d8c6b1790385e6584f004cfe3a9/Source/Core/Layout/FlexFormattingContext.cpp#L342

Delete this line seems work.

The git node:
```
git log -1
commit 51af29b1b34c3d8c6b1790385e6584f004cfe3a9 (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Ragazzon <michael.ragazzon@gmail.com>
Date:   Sun Jul 14 18:24:36 2024 +0200

    Defer scroll offset clamping to after layout, fixes #452
```

**Comment by mikke89** [comment]
Hi, and thanks for reporting.

This assertion shouldn't trigger during normal layouting, so it looks like a bug. I will take a look at it. If the layout looks right, then I don't think this particular one should cause any other issues though.

**Comment by mikke89** [comment]
I believe I found a fix for this. This had to do with us not considering the intrinsic aspect ratio of the image used as a flex item. Let me know how it goes :)
