### ISSUE TITLE
Debugging modal documents

### ISSUE THREAD

**Issue by Paril** [mikke89/RmlUi#642]
If a document is loaded with the Modal flag, it can't be debugged with Rml::Debugger as the modal eats all of the inputs. Currently the only workaround I can spot is just removing Modal when the debugger is visible.

**Comment by mikke89** [comment]
Thanks for reporting, I see that the debugger doesn't receive focus when another document has modal focus. Another workaround that seemed to work for me is to make a separate context for the debugger.

Better than dealing with workarounds though, I took a stab at properly fixing this.

Could you help test this branch and see how it works for you (and checking for no regressions), cheers: https://github.com/mikke89/RmlUi/commits/debugger-modal/

**Comment by Paril** [comment]
Thanks, I will test this out when I have time to port us over to master. We're still using an older version internally (5.x) and haven't upgraded to the current master 6.x yet since we are using some of my PRs that haven't been merged in yet, so it may be a little bit before I can test this myself. I need to get to re-opening those!

**Comment by Paril** [comment]
Confirmed fixed with the given branch though; thanks!

**Comment by mikke89** [comment]
Thanks for testing! Merged to master just now, should be fixed in 263328ab5db3d30a3a33a58e248cde4d9ac607a0.
