### ISSUE TITLE
TranslateX doesn't change the div width

### ISSUE THREAD

**Issue by Lyuu17** [mikke89/RmlUi#652]
I picked one table sample and I'm modifying to look like a scoreboard, centering in the middle of the screen

```html
<rml>

    <head>
        <style>
            body {
                font-family: Source Sans Pro;
                font-weight: normal;
                font-style: normal;
                font-size: 14dp;
                overflow: auto;
            }

            table {
                height: 100%;
                width: 300px;
                color: black;
                margin: 2em 0;
                border: 2dp #666;
                gap: 5dp;
                text-align: center;
            }

            td {
                background: #bbb;
                vertical-align: middle;
                padding: 5dp;
            }

            table {
                box-sizing: border-box;
                display: table;
            }

            tr {
                box-sizing: border-box;
                display: table-row;
            }

            td {
                box-sizing: border-box;
                display: table-cell;
            }

            col {
                box-sizing: border-box;
                display: table-column;
            }

            colgroup {
                display: table-column-group;
            }

            thead,
            tbody,
            tfoot {
                display: table-row-group;
            }

            .scoreboard {
                position: relative; 
                left: 50%;
                transform: translateX(-50%);
            }
        </style>
    </head>

    <body>
        <table class="scoreboard">
            <tr>
                <td style="width: 50dp">A</td>
                <td>B</td>
                <td>C</td>
                <td>D</td>
                <td style="width: 50dp">E</td>
            </tr>
            <tr>
                <td style="width: 50dp">A</td>
                <td>B</td>
                <td>C</td>
                <td>D</td>
                <td style="width: 50dp">E</td>
            </tr>
        </table>
    </body>
</rml>
```

Result:

![image](https://github.com/user-attachments/assets/cdb83355-aeba-4cf2-b16f-41c98d64dd88)

**Comment by mikke89** [comment]
Hey there. I'm trying to understand what you expect to happen in this situation, can you elaborate?

The result looks as I would expect here. Transforms should not affect the width of parent elements, and neither should positioned elements. I believe this behavior is the same as in CSS.

By the way, the idiomatic way in RmlUi to center elements is to use `margin: 0 auto`. This has the advantage that it is determined at the layout stage, so you get the benefit of pixel-aligned boxes and textures. On the other hand, transforms are done at the rendering stage, with possibly subpixel positioning, which can lead to slightly blurred text and textures. This approach also works better with clipping in our library.

**Comment by Lyuu17** [comment]
> Hey there. I'm trying to understand what you expect to happen in this situation, can you elaborate?

`left: -50%; transform: translateX(50%);` is supposed to center horizontally the div (at least what it says in here: https://stackoverflow.com/questions/25982135/why-does-left-50-transform-translatex-50-horizontally-center-an-element) 

> The result looks as I would expect here. Transforms should not affect the width of parent elements, and neither should positioned elements. I believe this behavior is the same as in CSS.

yeah, sorry, i'm bad for titles

> By the way, the idiomatic way in RmlUi to center elements is to use `margin: 0 auto`. This has the advantage that it is determined at the layout stage, so you get the benefit of pixel-aligned boxes and textures. On the other hand, transforms are done at the rendering stage, with possibly subpixel positioning, which can lead to slightly blurred text and textures. This approach also works better with clipping in our library.

The thing is, I don't want to use the whole screen for the document so I wanted to use `position: absolute` but I guess this is easier and less headache

**Comment by mikke89** [comment]
By the way, make sure to give `body` a width. Otherwise, there is nothing to compute percentages relative to, so they will resolve to zero. For me, it works perfectly fine to center it with the way you mention here, after setting `width: 100%` on the body. If you have any issues, try to test with the latest master branch, as there are several layout changes since RmlUi 5.1.

> The thing is, I don't want to use the whole screen for the document so I wanted to use position: absolute but I guess this is easier and less headache

You can use `margin: auto` with `position: absolute` to center the element (at least if the sizes are fixed).
