### ISSUE TITLE
Scroll continuously reverts to the top when another element on the document is updated

### ISSUE THREAD

**Issue by Paril** [mikke89/RmlUi#656]
We have a document that serves as a vault of content - the left 33% of the screen or so is a scrollable list of items, and the right side is a preview window which sometimes is scrollable.

We're not sure why, but, whenever the left side is scrolled down and an item is hovered which updates the preview on the right, the scroll container on the left jumps to the top. Looking at the call stack (breaking in SetBarPosition), it appears to be because of a document re-layout, but it's not retaining the previous scroll position. 

![](https://i.imgur.com/QvOEqS0.png)

It seems to hit this block a few times, but, this seems to be what's resetting the scroll area. There's not really anything special CSS-wise on the inner element;

![](https://i.imgur.com/i7wkT0c.png)

Currently, this is my only workaround - it functions but it suggests to me that something is up:

```cpp
	auto inner = doc->GetElementById("vault_items");
	auto top = inner->GetScrollTop();

	doc->UpdateDocument();

	inner->SetScrollTop(top);
```

I don't really understand why it's trying to re-layout #vault_items because it's not touched by the hover, only the right side box is. Removing the call to `UpdateDocument` doesn't change anything either, just defers the update to when Context::Update gets called.

**Comment by mikke89** [comment]
Which commit of the library are you on? Could it be a duplicate of this one: #452? If so, try updating :)

**Comment by Paril** [comment]
Oh shoot I really should have searched closed issues. Darnit! I'm still on whatever the last 5.1 version was I think, and yeah that commit isn't in our build. I'm hesitant to upgrade to the full 6.x release for this project since we're so close to release - is there a commit you'd recommend that has bug fixes but is still 5.x interface?

**Comment by mikke89** [comment]
Yeah, you can use the commit linked in the issue: https://github.com/mikke89/RmlUi/commit/51af29b1b34c3d8c6b1790385e6584f004cfe3a9

You could cherry-pick that. There has been several changes around these parts though since 5.1, so it will likely need to be manually backported.

**Comment by Paril** [comment]
Ahh yeah I see. Okay. Thanks!

**Comment by mikke89** [comment]
Cheers, no problem!
