### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by mikke89** [mikke89/RmlUi#66]
Every UI library needs a gallery!

I started adding some screenshots in the documentation:
https://mikke89.github.io/RmlUiDoc/pages/gallery.html
And the idea is to put all or some of these in the `Readme` here. 

Ideally, we want something that showcases various parts of the library, and looks nice at the same time. Although, I'm not sure if all of those examples look too good?

Perhaps you're using RmlUi in a project yourself, and you'd be willing to share screenshots? Then please add them here with a reply :) 
It would also be nice to have some links to projects using RmlUi, so if you'd like you can leave a link with your screenshots and I'll add them to the gallery.

**Comment by viciious** [comment]
How about providing some gifs with animation? Sorta like you did in this PR: https://github.com/libRocket/libRocket/pull/295

**Comment by viciious** [comment]
Warsow/Warfork both use libRocket for its UI but it's definitely not something to write home about..

**Comment by mikke89** [comment]
Yeah more gifs would be good, we could add those examples in there. I don't have much more to show for animations though.

Examples like Warsow/Warfork are nice, although I think it makes more sense to include projects using RmlUi or derivatives.

**Comment by viciious** [comment]
> Yeah more gifs would be good, we could add those examples in there. I don't have much more to show for animations though.
> 

Speaking of which, a simplified version of the "gridlock traffic simulator" UI would make a nice animations example. The problem with the current example is that it's a bit too simplistic, while the gifs showcase menu transitions between multiple documents. The first thing that springs to my mind when I see these is "whoa, how do I do that?" but there's no actual code samples.

**Comment by Unicornum** [comment]
My hands haven’t reached RmlUi yet, I'm still using the old version (libRocket), but maybe you will find something useful: http://unicornum.github.io/Covellitepp/index.html

**Comment by mikke89** [comment]
@Unicornum Thanks, looks like some nice examples. I'd prefer that the gallery only showed examples from RmlUi, so let me know if you upgrade. :)
I'd also be interested to hear how compiling RmlUi for Android goes, I haven't tried that myself.

**Comment by Unicornum** [comment]
> @Unicornum Thanks, looks like some nice examples. I'd prefer that the gallery only showed examples from RmlUi, so let me know if you upgrade. :)
> I'd also be interested to hear how compiling RmlUi for Android goes, I haven't tried that myself.

Ok.

**Comment by Unicornum** [comment]
> @Unicornum Thanks, looks like some nice examples. I'd prefer that the gallery only showed examples from RmlUi, so let me know if you upgrade. :)
> I'd also be interested to hear how compiling RmlUi for Android goes, I haven't tried that myself.

I switched my framework to using RmlUi, everything is fine, loading time and occupied memory decreased by 3-5 times, on Android (NDK r16b) everything also works fine.

**Comment by mikke89** [comment]
@Unicornum Great to hear, nice to see the performance improvements. I'd be happy to add some of the screenshots to the RmlUi gallery if you'd like :)

**Comment by Unicornum** [comment]
> @Unicornum Great to hear, nice to see the performance improvements. I'd be happy to add some of the screenshots to the RmlUi gallery if you'd like :)

Take what you see fit :)
