### ISSUE TITLE
data-for doesn't have model when it's need it

### ISSUE THREAD

**Issue by gleblebedev** [mikke89/RmlUi#662]
beware: I'm using older version of the RmlUI, maybe this is a known bug and already fixed.

I have the following rmlui body:

```
	<body data-model="GameRmlUIComponent">
		<div class="gray-outer-panel" style="position:absolute; width:25vw; height:100vh">
			Inventory items: {{ inventory_items.size }}<br/>
			{{ inventory_items[0] }}<br/>
			{{ inventory_items[1] }}<br/>
			<div data-for="item_value : inventory_items">
				{{ item_value }}
			</div>
		</div>
	</body>
```

When I load the document I see ApplyDataViewsControllersInternal is executed from ReadCloseTag inner functions with construct_structural_view set to true. The element's DataModel is nullptr.

Then I see SetDataModel is executed from AppendChild/SetParent with data model.

After this I would expect ApplyDataViewsControllersInternal  to be executed again with construct_structural_view set to true but this never happens. It is only gets executed with construct_structural_view  set to false from ApplyDataViewsControllers.

Hence the internal list data is never populated.

**Comment by gleblebedev** [comment]
When I move data-model to div everything works fine. Is this intentional?

**Comment by mikke89** [comment]
Are you using templates on the body? If so, this is a known limitation, see #241.
