### ISSUE TITLE
ProgressBar & CircularBar

### ISSUE THREAD

**Issue by Unicornum** [mikke89/RmlUi#67]
Please add:

ProgressBar: https://github.com/crazyjul/libRocket/tree/master/Contrib
CircularBar: https://github.com/FishingCactus/libRocketCircularBar

**Comment by mikke89** [comment]
Looks like good suggestions to me! We previously discussed the progressbar in #33. Perhaps we can combine the circularbar into the same element.

**Comment by mikke89** [comment]
Implemented in 634543b.
