### ISSUE TITLE
Question: How to use font icon in generated elements?

### ISSUE THREAD

**Issue by AmaiKinono** [mikke89/RmlUi#679]
"Font icon" is just single-colored icon baked into a font file, so basically I'm wondering how to put text into generated elements, like `selectarrow`.

I've tried to programmatically set inner RML of `selectarrow`s, but seems that doesn't work.

It would be simple if we have `::before` and `::after` pseudo elements. Maybe allowing text to be used as decorator also solves the problem.

**Comment by mikke89** [comment]
Hey. Yeah, variations of this topic comes up from time to time. See e.g. #399 and #655, and this: https://github.com/mikke89/RmlUi/discussions/348#discussioncomment-3418438. So it's definitely on our radar.

**Comment by mikke89** [comment]
> Maybe allowing text to be used as decorator also solves the problem.

Just added this feature in https://github.com/mikke89/RmlUi/commit/66d0b7c4d548e38c8939d6eec9492cea162b43f3:

```
decorator: text("Hello 🌎 world!" blue bottom right);
```

With that, I am considering this one resolved. The `::before` and `::after` pseudo elements are still on our radar, as those might be useful for other reasons too.
