### ISSUE TITLE
Extra hyphen in closing comment marker breaks parsing and rendering

### ISSUE THREAD

**Issue by HyperLightResearch** [mikke89/RmlUi#681]
If a closing comment marker has an extra hyphen in it, like `--->`, rendering breaks and the parser reports errors.  The error that gets reported depends on where the marker is placed.

Repro case:

```html
<rml>
	<head>
		<title>Hello world</title>
		<link type="text/rcss" href="rml.rcss"/>
	</head>
	<body>
		<table>
			<tr>
				<td/>
			</tr>
			<-- bad closing marker --->
			<tr>
				<td/>
			</tr>
			<tr>
				<td/>
			</tr>
		</table>
	</body>
</rml>
```

RmlUI 4.4, x86, Windows

Also, thank you for this library.  It's very intuitive and has been extremely useful!

**Comment by mikke89** [comment]
Thanks a lot for the kind word! I appreciate it.

I am able to replicate this one. I made some changes, and believe it should be fixed now: edcd777ed0c80606a7b45fb03896e64b8d77357e

**Comment by HyperLightResearch** [comment]
Fantastic.  Thank you for the rapid fix and for being so pleasant!

**Comment by mikke89** [comment]
Cheers, no problem :)

I am closing this one as resolved then.
