### ISSUE TITLE
Cloned <img> elements do not resolve relative file paths

### ISSUE THREAD

**Issue by HyperLightResearch** [mikke89/RmlUi#682]
Example page:
```html
<rml>
	<body>
		<p id="CloneThis" >
			<img src="../some/image.png" />
		</p>
		<p>Put the clone in here somewhere</p>
	</body>
</rml>
```

Repro:
1. Load this page
2. Find the element `CloneThis` on the page
3. Clone the element
4. Add the clone as a child to some other page element so that it becomes viewable

Expected: Rml asks the renderer implementation for a texture whose path is resolved (e.g. `"path/resolved/to/some/image.png"`)
Actual: Rml asks the renderer implementation for a texture whose path is not resolved (e.g. `"../some/image.png"`)
Workaround: make `src` paths for `img` elements absolute

This appears to happen because `src` is resolved using the document root during element creation, but no root is provided when cloning, so the path remains relative.

I'm reporting this because I've implemented a pretty straightforward page templating system for templating controls, and this might be the only issue with it.

RmlUI 4.4, x86, Windows

**Comment by mikke89** [comment]
Hello, and thanks for reporting. I see that you're on a pretty old version though. Are you able to reproduce this in the latest master?

**Comment by HyperLightResearch** [comment]
Yeah, sorry about that.  Unfortunately I can't integrate latest at the moment.  I'm hoping the test case is small and easy enough to repro that is easily found if it's still in latest.

**Comment by mikke89** [comment]
I tried this on RmlUi 6, and the procedure seems to work well for me here.

![image](https://github.com/user-attachments/assets/c4eefc98-e817-4fdf-a0d3-fddccdc667c8)

So I'm closing this one as not reproducible. Feel free to re-open or post a new issue if you're able to reproduce this on 6.0.
