### ISSUE TITLE
Possibilities of supporting scripting engines other than lua?

### ISSUE THREAD

**Issue by std-microblock** [mikke89/RmlUi#694]
Lua is an awful language sometimes. Idk if it would be difficult to utilize things like quickjs to support JavaScript instead. Having seen a team in China rewriting whole scripting part of rmlui, I do think this is possible. Any ideas?

**Comment by mikke89** [comment]
These suggestions pop up from time to time. Please see #268 in particular. Also #104 and https://github.com/mikke89/RmlUi/discussions/186#discussioncomment-4249205.

It's certainly possible to add new language bindings, but it takes a lot of effort both to write and maintain. So for now there are no plans to add official bindings to other languages. Instead, that is better suited as a community effort.
