### ISSUE TITLE
Bundling the html/rml files

### ISSUE THREAD

**Issue by std-microblock** [mikke89/RmlUi#695]
It would make the distribution of softwares easier if we can bundle every file into one file instead of sending a folder containing all the files needed, in which the users can mess everything up.

**Comment by std-microblock** [comment]
I've been a sciter user for a long time. It made an tool like tar to bundle a folder into one file, then support loading it.
I think it should be ok if we use the tar format directly.

**Comment by std-microblock** [comment]
> I believe the library does not need to handle this at all. One usually uses RmlUi with an existing engine; for instance, Unity or Unreal have their own way of handling assets. If you use this with your engine, you also probably want to pack such assets together with them, which is connected with providing your file interface for handling such custom packages.

In my case, I'm using rmlui to implement normal applications, so it would be helpful.

**Comment by hyblocker** [comment]
You can use `context->LoadDocumentFromMemory` to load a document from a UTF-8 `char*`. You can thus embed your files internally and use that to load documents, and a custom FileInterface to handle file resolution to data loaded in memory instead of I/O reads.

**Comment by std-microblock** [comment]
> You can use `context->LoadDocumentFromMemory` to load a document from a UTF-8 `char*`. You can thus embed your files internally and use that to load documents, and a custom FileInterface to handle file resolution to data loaded in memory instead of I/O reads.

Yeah, if this process can be integrated into rmlui, it would be nice. Will the PR implementing this be accepted if I make one?

**Comment by mikke89** [comment]
Yeah, I don't think we'll find any one-size-fits-all solution to bundling these assets. I expect most users to have some way already to bundle assets, so it wouldn't really add much value. Thus, I don't think there is much for us to do here.

Closing this one as not planned.
