### ISSUE TITLE
Separate templates into different files.

### ISSUE THREAD

**Issue by std-microblock** [mikke89/RmlUi#696]
Now we have templates. It's all good but for bigger projects, it would be a disaster if we put everything in a single file. Is it possible to separate it into different files?
This might can be implemented by something like Loader component in qml, or some special element type lookup method. For example we can make tags like <c-SomeButton> load template in ./SomeButton.html automatically.

**Comment by mikke89** [comment]
Not sure if I'm following here, what is forcing you to put everything in a single file? I believe you should be able to add multiple [templates](https://mikke89.github.io/RmlUiDoc/pages/rml/templates.html#inline-template) to a single document.

**Comment by mikke89** [comment]
Added some new tests for this case, just to be sure: 6fe03a7d
