### ISSUE TITLE
Font alpha channel

### ISSUE THREAD

**Issue by igorsegallafa** [mikke89/RmlUi#698]
I see that the RmlUi 6 uses premultiplied alpha, but what should I do in my rendering engine with these changes?

I am already using the correct blending mode:
```
auto Desc = D3D11_BLEND_DESC{ };
Desc.AlphaToCoverageEnable = FALSE;
Desc.IndependentBlendEnable = FALSE;

Desc.RenderTarget[0].BlendEnable = TRUE;
Desc.RenderTarget[0].DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
Desc.RenderTarget[0].SrcBlend = D3D11_BLEND_ONE;
Desc.RenderTarget[0].BlendOp = D3D11_BLEND_OP_ADD;

Desc.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_ZERO;
Desc.RenderTarget[0].SrcBlendAlpha = D3D11_BLEND_ONE;
Desc.RenderTarget[0].BlendOpAlpha = D3D11_BLEND_OP_ADD;

Desc.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
``` 

Even so, fonts rendered in light colors, look a little weird.

![image](https://github.com/user-attachments/assets/b68b2839-7553-46f9-9dfb-39a408a1870a)

** For images the premultiplied alpha is working normally, it is something related to the font rendering:
![image](https://github.com/user-attachments/assets/1d8348d2-15c6-4cb8-b469-33f9f9c87495)

**Comment by mikke89** [comment]
Yes, you're right, all the textures provided by the library are in premultiplied alpha now.

It looks like you're blend equations are not set up correctly: The color and alpha blending factors should be the same. It should be 1 for the source, and `1-alpha` for the destination, for all RGBA channels. This great resource is really good at explaining it all: https://apoorvaj.io/alpha-compositing-opengl-blending-and-premultiplied-alpha/

Please note that we don't modify the images you provide yourself in any way, so I wonder if those are not in pre-multiplied alpha in your case? That could explain the differences between fonts and textures.

**Comment by igorsegallafa** [comment]
Thank you, it solved my issue.
