### ISSUE TITLE
Support for multiple pointers / mice

### ISSUE THREAD

**Issue by hyblocker** [mikke89/RmlUi#706]
I'm using RmlUI in a VR environment, where a pointer / mouse is defined by a ray shot from a user's controller towards a 2D surface displaying the UI. Since in VR people can use both hands independently, It would be wise to be able to support using multiple cursors simultaneously. This work would likely be beneficial for touch devices as well and other input systems.

Would re-factoring the `Rml::Context` class such that all cursor events take in a numbered index representing the pointer index (so that drag, hover, etc. events still work) make sense? I'm willing to draft a PR should this approach be desired.

**Comment by mikke89** [comment]
I am definitely interested in supporting this scenario. Would it make sense to use a (multi-)touch api for this? See #60 and the linked PR within.

**Comment by hyblocker** [comment]
Yeah, using a multi-touch API for my use case is probably better as it would then allow for touch screen support and novel hardware support such as my case, as long as some arbitrary amount of "mice" may be used in the system.

**Comment by mikke89** [comment]
Great. I do wonder more generally about what kind of behavior you are expecting in terms of focus/active/hover state and the like, can you elaborate a bit more on this?

We should take some inspiration from the [HTML touch events](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent). As far as I understand, things like hover, and focus are always singular in HTML, even with multi-touch.

**Comment by mikke89** [comment]
I'm not super excited about that change. Having multiple active and hover elements probably break a lot of assumptions, and diverge from HTML.

I would rather consider that we mainly implement the multi-touch events, and rather leave it up to the user to set their own similar states on the elements, for example by setting custom classes, based on those events.

**Comment by hyblocker** [comment]
That's fair. I completely forgot that I could indicate highlighted elements with my own classes too haha.

**Comment by mikke89** [comment]
Alright, I think the conclusion here is to implement touch events, which is already covered by #60. So for that reason, I am closing this issue.
