### ISSUE TITLE
Support for raylib as a backend?

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [mikke89/RmlUi#710]
I know raylib has an active opengl context but not sure if rmlui has support for the systems/non rendering parts of raylib.

**Comment by mikke89** [comment]
Right, I think it should just work with our OpenGL renderer, as you mention. The render interface is the only thing that's required to get started, but you'll probably also want to add input at least.

I'm not sure how raylib interacts with the window, looks like it can hook into glfw/sdl, so maybe you can just pick the right one out of those as a platform?

**Comment by mikke89** [comment]
Closing this one due to lack of activity. I think this is one of those cases that is better suited for thirdparty support, or users simply sharing their implementations in the discussions.
