### ISSUE TITLE
Overflow-y:scroll not working as expected

### ISSUE THREAD

**Issue by YTN0** [mikke89/RmlUi#711]
I have a div with overflow-y set to scroll, and within it I am generating a list of divs from an array. The problem is the overflow isn't being hidden as expected.

Here's the corresponding rml:

```
<div style="height:100dp; width:100%; overflow-y:scroll; background-color: #0000FF;">
 <div data-for="name : myArray" onclick="click" style="font-size:16dp; border: 1px; height:50dp; width:100%;">
      {{name}}
  </div>     
</div>

```
I am attaching screenshots of the results. Any ideas on why the overflow isn't being contained?

<img width="290" alt="Screenshot 2024-11-28 at 2 30 06 AM" src="https://github.com/user-attachments/assets/7d8d0d66-ce3a-45f6-ad16-d0756ccb2043">
<img width="304" alt="Screenshot 2024-11-28 at 2 29 53 AM" src="https://github.com/user-attachments/assets/e6aa11cf-ee1c-4c99-bdc4-8dffa031260d">
<img width="293" alt="Screenshot 2024-11-28 at 2 29 29 AM" src="https://github.com/user-attachments/assets/f29d4cf0-e35d-49a2-949f-27e9f2123113">

**Comment by mikke89** [comment]
Which renderer are you using? Does clipping work at all in other situations?

**Comment by YTN0** [comment]
I am using my own renderer... and I had assumed clipping had been working, but am not so sure now. I believe it was working previously with the older style RML render interface.

I only have scissor implemented, and not clip masks. I am assuming this relies on scissors?

To clarify how the new render interface works with scissors....  I am assuming the sequence of render calls / events is:

EnableScissorRegion(true)
SetScissorRegion(<blah>)
RenderGeometry(<blah>)
EnableScissorRegion(false)... assuming the same scissor isn't used for subsequent renders.

Is that about right?

**Comment by mikke89** [comment]
I see. Yeah generally, that should be the order. But please check what you're actually getting through the render interface. If you can test with our built-in backends too (or replicate in our code base), that would be helpful.

There are some situations where clip masks are needed. In particular if you are using any transforms, or border radius combined with hidden overflow. Then your assumptions might not be correct.

**Comment by YTN0** [comment]
@mikke89 I am not able to (easily) test with the built-in backends without significant work. My renderer and codebase is C#, and I wrote a proxy to bridge my C# code with the RML code.

I did set some breakpoints, and it doesn't look like the scissor methods are being called, so it looks like it's not using a scissor for this. It is breakpointing on the clipmask methods, so it looks like it needs clipmasks to be implemented for this.

Is there a way to force or get it to leverage scissors, or what should I change in my RML to use scissors instead of clipmasks? 

I currently don't have support for clipmasks implemented.

**Comment by mikke89** [comment]
Sounds interesting with the C# bindings, I understand if you can't easily test that. If you do suspect it's a bug on the RmlUi side, then it would be helpful if you could be able to reproduce it in our code base.

In terms of the rml and clip masks, the main culprits are those mentioned above, border radius with non-visible overflow, and transforms.

**Comment by YTN0** [comment]
I combed through my RML, and am not seeing use of radius or non-visible overflow anywhere, so can't see why it would attempt to use a clipmask instead of a clipmask. 

I'll do more digging to see if I can figure out what's going on. Worst case is I'll have to implement clipmasks.

Thanks.

**Comment by mikke89** [comment]
Just tested with the RML you posted and got these results (with 10 inner elements):

```
  Compile geometry: 13
  Render geometry: 13
  Release geometry: 0
  Texture load: 0
  Texture generate: 1
  Texture release: 0
  Scissor enable: 2
  Scissor set: 1
  Clip mask enable: 0
  Clip mask render: 0
  Transform set: 0
```

So no clip masks here, only a single scissor operation. If you are able to reproduce this in our codebase, I would be able to investigate and be a lot more helpful.

**Comment by YTN0** [comment]
@mikke89 Thanks for digging into this.

Can you show the entire RML you used so I can test using the exact same thing? 

It's possible I have some other RML that's triggering a clip mask instead of scissors.

I'll strip it down to the bare minimum to test.

**Comment by mikke89** [comment]
No problem, sounds good. Here is the RML I used:

```html
<rml>
	<head>
		<title>Demo</title>
		<link type="text/rcss" href="/assets/rml.rcss" />
		<style>
			body
			{
				font-family: LatoLatin;
				font-weight: normal;
				font-style: normal;
				font-size: 15dp;
				color: white;
				width: 500dp;
				height: 525dp;
				margin: auto;
			}
		</style>
	</head>
	<body>
<div style="height:100dp; width:100%; overflow-y:scroll; background-color: #0000FF;">
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
	<div style="font-size:16dp; border: 1px; height:50dp; width:100%;">blah</div>
</div>
	</body>
</rml>
```

**Comment by YTN0** [comment]
@mikke89 I found the problem... I had a perspective set on the background on which the above rml was a part of. Specifically, I had the following:

```
	perspective: 1000px;
	perspective-origin: 50% 50%;

```

That was causing it to use clip masks instead of scissors. After disabling the above, the scissors are working as expected.

**Comment by mikke89** [comment]
Ah, right, perspectives will also result in clip masks. Good to hear it was solved then :)

**Comment by YTN0** [comment]
It would be great if this was reflected in the documentation. A table showing what triggers a scissor vs clip mask would help in clearing up any potential confusion 😊

**Comment by mikke89** [comment]
Yeah, I added this table quite recently: https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/interfaces/render.html#feature-table

But I see that `perspective` is missing. I guess I didn't really expect to see that used without `transform`, but it's good to have it documented regardless. I'll go ahead and add that.

**Comment by mikke89** [comment]
I added that property, together with some notes:
https://github.com/mikke89/RmlUiDoc/commit/94cc7c81ccc2c15b638b02ad29676f8335873e45

Let me know if you have any suggestions for improvements.
