### ISSUE TITLE
OpenGL ES2 supports

### ISSUE THREAD

**Issue by colesnicov** [mikke89/RmlUi#715]
Hello. It is suppord OpenGL ES2? Thank you.

**Comment by mikke89** [comment]
Hi. We don't have a built-in backend directly for OpenGL ES2. However, you have some options:

- The `SDL_SDLrenderer` backend can be configured to use OpenGL ES2 using SDL hints.
- Our OpenGL 3 renderer supports OpenGL ES3, we use that for Emscripten in particular. You could go through that and strip it of the ES3-specific functionality.
- Of course, you always have the option of writing your own backend. Take a look at our GL2 and GL3 renderers in particular.
