### ISSUE TITLE
Input Range change event value returning the slider position instead of the value

### ISSUE THREAD

**Issue by andreasschultes** [mikke89/RmlUi#72]
I'm not sure if it's desired behavior that the value is normalized?
For example the a <input type="range" min="0" max="100" step="1" value="20" onchange="myevent"/> is changed to 21 it fires an value of 0.21. 
For other min max values the example wouldn't be nice anymore,  because the event is returning the slider position instead of the value.

**Comment by mikke89** [comment]
You're right, this is not intended behavior. Thanks for reporting, will take a look at it soon.

**Comment by andreasschultes** [comment]
I'll make a pull request to fix this

**Comment by andreasschultes** [comment]
https://github.com/mikke89/RmlUi/pull/73

**Comment by mikke89** [comment]
Thanks again!
