### ISSUE TITLE
CMake 3.10 doesn't know "add_compile_definitions"

### ISSUE THREAD

**Issue by jhasse** [mikke89/RmlUi#77]
4397a8471969a4c69203caf7b0e7be8b2daa05e8 broke configuring with CMake < 3.12 as `add_compile_definitions` was added in 3.12.

I'm still using CMake 3.10 as that's the newest version that ships with the Android NDK.

**Comment by mikke89** [comment]
Thanks, I wasn't aware. I hope this fixes it.

**Comment by jhasse** [comment]
Yes, works! Thank you very much, that was fast :)

btw: I'm currently upgrading from libRocket to RmlUi. Is it okay to ask questions by creating an issue or should I use something else (stackoverflow?)?

**Comment by mikke89** [comment]
Great, happy to have new people onboard! Appreciate all the contributions, keep them up.

Feel free to create an issue, at least if it's something you think might help other people as well. Otherwise we have a gitter chat, shoot away anything you'd like there: https://gitter.im/RmlUi/community
