### ISSUE TITLE
Rml::Core::RenderInterface::GetPixelsPerInch() is not working

### ISSUE THREAD

**Issue by maruime** [mikke89/RmlUi#80]
The methods that worked in libRocket are gone.
Please implement it because you want to change the pixel size according to the screen size.

**Comment by mikke89** [comment]
This functionality has been replaced by the `dp`-unit. See more [in the documentation](https://mikke89.github.io/RmlUiDoc/pages/rcss/syntax.html#lengths).

**Comment by maruime** [comment]
The problem has been resolved.
Thank you!
