### ISSUE TITLE
Long compilation times

### ISSUE THREAD

**Issue by viciious** [mikke89/RmlUi#81]
A whole game engine can be compiled in the time it takes to compile RmlUI alone :P

It would be nice if the compilation time of RmlUI could be reduced. The precompiled header helps but not that much because of the heavy use of templates.

I recall profiling it using MSVC's /d2cgsummary flag (see https://aras-p.info/blog/2017/10/23/Best-unknown-MSVC-flag-d2cgsummary/ ), but I can't remember any details anymore. My best guess would be that most of the time comes from the monstrous Core.h include file but we need that to be re-verified.

**Comment by mikke89** [comment]
Yeah, I mean, faster compilation is always better :)

When compiling without PCH one of the issues is that we still include the precompiled header in every file, which basically includes everything. With the CMake integration of PCH we don't need to do this anymore, which would probably speed up things a lot without PCH. But also introduce lots of compile errors as the code has probably been leaning on this header too much. Meaning we need to include individual headers instead in many places.

Although, I'm not sure where to start with speeding up the PCH build. We could perhaps experiment with reducing what gets included there. And perhaps see if there are any headers that can be removed or moved into cpp-files. These things are notoriously hard to measure though, unfortunately. I don't really feel like the library is very heavy on templates, but we could try to look into that.

With that said, for me, RmlCore compiles in around 2 sec. with precompiled headers, so I'm generally satisfied with that. The removal of the old font system was a pretty big win.

**Comment by viciious** [comment]
I would generally be satisfied if we managed to reduce the clean build time to under 2 minutes. At the moment, Travis builds take around 5 minutes to complete.

**Comment by mikke89** [comment]
I've cleaned up a lot of the header files now, and added precompiled headers compilation for more of the projects (Controls and shell). Combined with your CMake upgrade on Travis @viciious to make use of the PCH header we see about two and a half minutes compile times there. Nice improvement.

I don't really have any more ideas on how to improve it further. Perhaps utilize the pimpl idiom in more places, but I'd rather not to be honest.

**Comment by mikke89** [comment]
I'm closing this for now, we can open a new issue if we have concrete suggestions on how to improve compile times further.
