### ISSUE TITLE
Build fails with Clang5.0 (C ++ 17)

### ISSUE THREAD

**Issue by maruime** [mikke89/RmlUi#87]
Build error occurs in VisualStdio Android development environment.
The build is RMLUI_STATIC_LIB only
gnustl_static

Code I tentatively addressed

./Include/RmlUi/Core/Types.h
``
template <class T> struct hash {
	using utype = typename ::std::underlying_type<T>::type;
	size_t operator() (const T& t) const { ::std::hash<utype> h; return h(static_cast<utype>(t)); }
``

to

``
#ifdef __ANDROID__

template <> struct hash<::Rml::Core::PropertyId> {
	using utype = typename ::std::underlying_type<::Rml::Core::PropertyId>::type;
	size_t operator() (const ::Rml::Core::PropertyId& t) const { ::std::hash<utype> h; return h(static_cast<utype>(t)); }
#endif
``

**Comment by maruime** [comment]
errors

重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー		call to non-static member function without an object argument	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1344	
エラー		call to non-static member function without an object argument	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1339	
エラー		call to non-static member function without an object argument	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1269	
エラー		call to non-static member function without an object argument	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1922	
エラー		call to non-static member function without an object argument	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1269	
エラー		call to non-static member function without an object argument	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1964	
エラー		call to non-static member function without an object argument	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	2021	
エラー		cannot initialize object parameter of type 'const std::equal_to<Rml::Core::Character>' with an expression of type 'const robin_hood::detail::Table<true, 80, Rml::Core::Character, Rml::Core::FontGlyph, robin_hood::hash<Rml::Core::Character>, std::equal_to<Rml::Core::Character> >'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1339	
エラー		cannot initialize object parameter of type 'const std::equal_to<Rml::Core::Character>' with an expression of type 'const robin_hood::detail::Table<true, 80, Rml::Core::Character, Rml::Core::FontGlyph, robin_hood::hash<Rml::Core::Character>, std::equal_to<Rml::Core::Character> >'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1344	
エラー		implicit instantiation of undefined template 'std::hash<Rml::Core::Character>'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	747	
エラー		implicit instantiation of undefined template 'std::hash<Rml::Core::Character>'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	747	
エラー		implicit instantiation of undefined template 'std::hash<Rml::Core::Character>'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	747	
エラー		implicit instantiation of undefined template 'std::hash<Rml::Core::Character>'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	747	
エラー		implicit instantiation of undefined template 'std::hash<Rml::Core::Character>'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	747	
エラー		no matching member function for call to 'keyToIdx'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1958	
エラー		no matching member function for call to 'keyToIdx'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	2016	
エラー		no member named 'align' in namespace 'std'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Source\Core\Memory.h	66	
エラー		no member named 'align' in namespace 'std'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Source\Core\Memory.h	66	
エラー		no member named 'operator()' in 'robin_hood::detail::WrapHash<robin_hood::hash<Rml::Core::Character> >'	Library_RmlUi (Android\01_Library\Library_RmlUi)	C:\dev\c\MMDAgent-1.4\Library_RmlUi\Include\RmlUi\Core\Containers\robin_hood.h	1269

**Comment by maruime** [comment]
ndk is std::align not supported

fix plan

``
./Include/RmlUi/Core/Types.h
namespace std {
inline void* align(std::size_t alignment, std::size_t size,
  void*& ptr, std::size_t& space) {
  std::uintptr_t pn = reinterpret_cast<std::uintptr_t>(ptr);
  std::uintptr_t aligned = (pn + alignment - 1) & -alignment;
  std::size_t padding = aligned - pn;
  if (space < size + padding) return nullptr;
  space -= padding;
  return ptr = reinterpret_cast<void*>(aligned);
}
}
``

**Comment by maruime** [comment]
std::hash<::Rml::Core::Character> need add.

Now the build passes.

``
namespace std {
// Hash specialization for enum class types (required on some older compilers)
template <> struct hash<::Rml::Core::PropertyId> {
	using utype = typename ::std::underlying_type<::Rml::Core::PropertyId>::type;
	size_t operator() (const ::Rml::Core::PropertyId& t) const { ::std::hash<utype> h; return h(static_cast<utype>(t)); }
};

template <> struct hash<::Rml::Core::Character> {
  using utype = typename ::std::underlying_type<::Rml::Core::Character>::type;
  size_t operator() (const ::Rml::Core::Character& t) const { ::std::hash<utype> h; return h(static_cast<utype>(t)); }
};

inline void* align(std::size_t alignment, std::size_t size,
  void*& ptr, std::size_t& space) {
  std::uintptr_t pn = reinterpret_cast<std::uintptr_t>(ptr);
  std::uintptr_t aligned = (pn + alignment - 1) & -alignment;
  std::size_t padding = aligned - pn;
  if (space < size + padding) return nullptr;
  space -= padding;
  return ptr = reinterpret_cast<void*>(aligned);
}
}
``

**Comment by viciious** [comment]
Isn't gnustl_static deprecated in favor of c++_static?

**Comment by maruime** [comment]
In my project, I built using gnustl_static because c ++ _ static did not have enough functions to build.

**Comment by mikke89** [comment]
I'm unable to test this, so please let me know if it works :)

**Comment by mikke89** [comment]
Great!
