### ISSUE TITLE
Child element is not cleared even if a character string is assigned to inner_rml in select element

### ISSUE THREAD

**Issue by maruime** [mikke89/RmlUi#88]
ElementFormControlSelect.RemoveAll has been cleared, so provisional support.

 `` ElementFormControlSelect.RemoveAll("accessory-window", "actor-selector") -- Bug fixes
  local select = AsSelect(document:GetElementById('actor-selector'))
  select.inner_rml = contents
  select.value = ''
``

**Comment by mikke89** [comment]
Not sure if I understand correctly. Are you talking about missing Lua support for RemoveAll?

Generally, using inner_rml on the control elements may not work as expected, since they often control their children separately from the underlying RML document.

It should we pretty straightforward to add RemoveAll to Lua though, if that solves the problem?

**Comment by maruime** [comment]
If you assign to inner_rml, it is added for some reason.

[Original content]

```html:sample
<select>
<option>1</option>
<option>2</option>
</select>
```

[run code]

```html:sample
select.inner_rml = '<option>a</option><option>b</option>'
```

[The result I expect]

```html:sample
<select>
<option>a</option>
<option>b</option>
</select>
```

[Actual consequences]
```html:sample
<select>
<option>1</option>
<option>2</option>
<option>a</option>
<option>b</option>
</select>
```

**Comment by mikke89** [comment]
Ah, I see. That is quite inconsistent. We can probably make it replace the existing elements. Hopefully, that doesn't have unintended consequences.

**Comment by mikke89** [comment]
Actually, there is a problem with that, since then doing `AppendChild` would remove all the options. I'd rather we just add the Lua function, if that would solve the problem.

**Comment by maruime** [comment]
ElementFormControlSelect.RemoveAll was already present and working. Is it not possible to call RemoveAll inside inner_rml?

**Comment by mikke89** [comment]
What do you mean RemovaAll was already present? I could only see Remove, so I added it?

We can't really remove the existing options due to the aforementioned issue.

**Comment by maruime** [comment]
ElementFormControlSelect.RemoveAll is working from the beginning.
I have not added anything.

**Comment by mikke89** [comment]
Unfortunately, we cannot easily fix the `inner_rml` issue. InnerRml on the control elements generally may not work as expected. Instead, use the functions associated with these elements.

**Comment by maruime** [comment]
I'm sorry, I added RemoveAll and SetValue.

````c++
namespace ElementFormControlSelect {
static int RemoveAll(lua_State* L)
{
  const char *bodyId = luaL_checkstring(L, 1);
  const char *elementId = luaL_checkstring(L, 2);

  Rml::Core::ElementDocument *document = g_RmlUiManager->context()->GetDocument(bodyId);
  if (NULL == document) return 0;

  Rml::Controls::ElementFormControlSelect *element = static_cast<Rml::Controls::ElementFormControlSelect*>(document->GetElementById(elementId));
  if (NULL == element) return 0;

  element->RemoveAll();

  return 0;
}

static int SetValue(lua_State* L)
{
  const char *bodyId = luaL_checkstring(L, 1);
  const char *elementId = luaL_checkstring(L, 2);
  const char *value = luaL_checkstring(L, 3);

  Rml::Core::ElementDocument *document = g_RmlUiManager->context()->GetDocument(bodyId);
  if (NULL == document) return 0;

  Rml::Controls::ElementFormControlSelect *element = static_cast<Rml::Controls::ElementFormControlSelect*>(document->GetElementById(elementId));
  if (NULL == element) return 0;

  element->SetValue(value);

  return 0;
}
````

**Comment by mikke89** [comment]
Alright, I was a bit confused there, no worries. I added RemoveAll in https://github.com/mikke89/RmlUi/commit/c2b2669426b7575f5647db6e6f10d72d950bd2d2. The value can already be set with `el.value = '...'`, so you should be able to remove your custom functions when you update your master branch.

**Comment by mikke89** [comment]
Consider this resolved then. Let me know if you disagree :)
