### ISSUE TITLE
Changing the class of an element does not reflect the change

### ISSUE THREAD

**Issue by maruime** [mikke89/RmlUi#90]
If you try to change the class name from lua side, the style will not be applied.

````lua
document:GetElementById('idname'):SetAttribute("class", "newclass")
````

**Comment by mikke89** [comment]
Hm, it works fine for me here.

**Comment by maruime** [comment]
I tried again and it worked fine.
It looks like you did something wrong when you tried it before.
Sorry for the trouble.

**Comment by mikke89** [comment]
Glad it's working for you, no worries :)
