### ISSUE TITLE
 I want to display the option selection display of the select element at the top if it can not be displayed below

### ISSUE THREAD

**Issue by maruime** [mikke89/RmlUi#91]
There is a problem that cannot be selected when the select element is displayed at the bottom of the screen.

**Comment by uniquejack** [comment]
You have to style the selectbox in order to show the values on top of the bar.
So set a height to your selectbox and then use margin-bottom to align vertically the element.

**Comment by mikke89** [comment]
This can be handled on the user side, but I think we should consider handling this situtation on the llibrary side. Need to think a bit more about this and see how it works out in practice.

**Comment by mikke89** [comment]
Alright, I did try to implement this feature. Let me know how it works or if there are any issues with the solution.

**Comment by aquawicket** [comment]
I think this should be done user side.

**Comment by aquawicket** [comment]
I'll test this and give feedback soon.

**Comment by mikke89** [comment]
Closing this, as it is now available since version 3.3.
