### ISSUE TITLE
Overflow-X not working properly

### ISSUE THREAD

**Issue by uniquejack** [mikke89/RmlUi#94]
When I use white-space: nowrap, overflow-x: scroll and max-width on a container, the container stretches to the size of the children elements.

How to reproduce:
[demo.txt](https://github.com/mikke89/RmlUi/files/4412233/demo.txt)

The size of the window body doesn't get 100px, but it gets as big as the content gets.

EDIT: same issue in the databinding branch.

**Comment by uniquejack** [comment]
I think I found the problem:
LayoutBlockBox.cpp line 229:

`				if (!wrap_content)
					box.SetContent(Vector2f(content_box.x, box.GetSize().y));`
Why are we disabling the overflow-x when wrapping is disabled? should actually be the opposite

**Comment by mikke89** [comment]
Thank you! I don't see why the box should ever be extended at this point. I removed the condition you refer to which should fix this particular issue.
