### ISSUE TITLE
Problem with lua bindings overriding global table functions

### ISSUE THREAD

**Issue by JFT90** [mikke89/RmlUi#95]
Hi,
first of all thank you for all the great work on rmlui!

I am currently replacing cegui with rmlui in a project of mine.
I am trying to use as much lua code for UI event handling etc.  as possible and noticed that
the global table overrides in
https://github.com/mikke89/RmlUi/blob/c170c24401d6ec1f7cb9b84e122ee428eefb7b73/Source/Core/Lua/GlobalLuaFunctions.cpp#L146

break some of my other lua code using the iterators `pairs` , `ipairs` ( I simply iterate over elements 
in a lua table and the iterators return `nil` where the standard iterator returns a valid entry. )

At the moment I temporarily fixed this problem by deleting the overrides, which breaks the iteration over `ElementAttributes` for example. 

A correct fix would be to only override the iterators for the tables that need the special iterators instead of overriding iteration behavior globally.

Edit: I am using lua 5.3

**Comment by mikke89** [comment]
Hi, and thank you for the encouragement. Glad to see more people involved.

Unfortunately, the Lua implementation is not my strong suite, and I don't really know it well enough to be able to help in this case. Any help fixing this would be appreciated.

**Comment by JFT90** [comment]
Ok, I will try to dive into the Lua implementation when I have some time.
