### ISSUE TITLE
<StringCache>: Do we really want this?

### ISSUE THREAD

**Issue by crackedmind** [mikke89/RmlUi#96]
This is strange piece of code, some of constants not used anywhere. 

When i replaced this constants with char* instead of String RmlCore.dll was reduced from 963 to 946 kb.

**Comment by mikke89** [comment]
I think the memory reduction alone is a good enough reason to remove it, thanks for reporting it.

**Comment by mikke89** [comment]
I removed the whole file, most of the variables were only used in a single place so I didn't see a reason to keep them.
