### ISSUE TITLE
v3.2: For button:active ignored font-effect

### ISSUE THREAD

**Issue by Unicornum** [mikke89/RmlUi#98]
For the following styles, when the button is pressed, the color changes, but the outline does not.

```
button {  
  color: white;
  font-effect: outline(2px grey);
}

  button:active {
    color: grey;
    font-effect: outline(2px white);
  }
```

UPD: The same is true for font-effect: shadow (2px 2px gray);

**Comment by mikke89** [comment]
Looks like the font-effect property is not properly dirtied. Thanks for reporting, will have a look at it.

**Comment by mikke89** [comment]
I hope this change works for you :)
